/*//////////////////////////////////////////////////////////////////////////////

 ---------- Document Info ---------------

        Author : Anonymous
       Created : 20:42:59, May 19 2009
 Last modified : 15:18:17, Mar 22 2013
   Making tool : UI Designer Studio
   File format : C language header file

 ----------- Object Info ----------------

         Class : IMAGE_TABLE
          Name : DemoKit_Image

*///////////////////////////////////////////////////////////////////////////////

#ifndef _DEMOKIT_IMAGE_H_
#define _DEMOKIT_IMAGE_H_

// IMAGE_TABLE
extern const
unsigned char gDemoKit_Image[];

// IMAGE ID
#define ICON_ACT_RELEASE_BTN                     0x0000
#define ICON_ADAS_CAL                            0x0001
#define ICON_ADAS_CAL_M                          0x0002
#define ICON_ADAS_OFF                            0x0003
#define ICON_ADAS_OFF_M                          0x0004
#define ICON_ADAS_ON                             0x0005
#define ICON_ADAS_ON_M                           0x0006
#define ICON_ALARM_LEFT_R                        0x0007
#define ICON_ALARM_LEFT_Y                        0x0008
#define ICON_ALARM_RIGHT_R                       0x0009
#define ICON_ALARM_RIGHT_Y                       0x000A
#define ICON_AUTOSHUTDOWN                        0x000B
#define ICON_AUTOSHUTDOWN_3MIN                   0x000C
#define ICON_AUTOSHUTDOWN_5MIN                   0x000D
#define ICON_AUTOSHUTDOWN_10MIN                  0x000E
#define ICON_AUTOSHUTDOWN_M                      0x000F
#define ICON_AUTOSHUTDOWN_OFF                    0x0010
#define ICON_BACKLIGHT                           0x0011
#define ICON_BACKLIGHT_HIGH                      0x0012
#define ICON_BACKLIGHT_LOW                       0x0013
#define ICON_BACKLIGHT_M                         0x0014
#define ICON_BACKLIGHT_MID                       0x0015
#define ICON_BACKLIGHT_OFF                       0x0016
#define ICON_BACKLIGHT_PRESS                     0x0017
#define ICON_BATTERY_CHARGE                      0x0018
#define ICON_BATTERY_EMPTY                       0x0019
#define ICON_BATTERY_FULL                        0x001A
#define ICON_BATTERY_LOW                         0x001B
#define ICON_BATTERY_MED                         0x001C
#define ICON_BATTERY_TYPE                        0x001D
#define ICON_BATTERY_ZERO                        0x001E
#define ICON_BSD_OFF                             0x001F
#define ICON_BSD_OFF_M                           0x0020
#define ICON_BSD_ON                              0x0021
#define ICON_BSD_ON_M                            0x0022
#define ICON_BTN_EMBOSS                          0x0023
#define ICON_BUST                                0x0024
#define ICON_BUST_3SHOT                          0x0025
#define ICON_BUST_CONTINUE                       0x0026
#define ICON_BUST_M                              0x0027
#define ICON_BUST_OFF                            0x0028
#define ICON_CAM_PTZ_OFF                         0x0029
#define ICON_CAM_PTZ_ON                          0x002A
#define ICON_CAM_PTZ_ON_M                        0x002B
#define ICON_CANCEL                              0x002C
#define ICON_CANCEL_M                            0x002D
#define ICON_CLOUD_CONNECTED                     0x002E
#define ICON_CLOUD_CONNECTED_M                   0x002F
#define ICON_CLOUD_CONNECTING                    0x0030
#define ICON_CLOUD_CONNECTING_M                  0x0031
#define ICON_CLOUD_DOWNLOAD1                     0x0032
#define ICON_CLOUD_DOWNLOAD2                     0x0033
#define ICON_CLOUD_FAIL                          0x0034
#define ICON_CLOUD_OFF                           0x0035
#define ICON_CLOUD_OFF_M                         0x0036
#define ICON_CLOUD_ON                            0x0037
#define ICON_CLOUD_ON_M                          0x0038
#define ICON_CLOUD_UPLOAD1                       0x0039
#define ICON_CLOUD_UPLOAD2                       0x003A
#define ICON_COLOR                               0x003B
#define ICON_COPY_FROM_CARD                      0x003C
#define ICON_CYCLIC_REC                          0x003D
#define ICON_CYCLIC_REC_1MIN                     0x003E
#define ICON_CYCLIC_REC_2MIN                     0x003F
#define ICON_CYCLIC_REC_3MIN                     0x0040
#define ICON_CYCLIC_REC_5MIN                     0x0041
#define ICON_CYCLIC_REC_10MIN                    0x0042
#define ICON_CYCLIC_REC_15MIN                    0x0043
#define ICON_CYCLIC_REC_M                        0x0044
#define ICON_DATE_PRINT                          0x0045
#define ICON_DATE_PRINT_M                        0x0046
#define ICON_DATE_STAMPING                       0x0047
#define ICON_DATE_TIME                           0x0048
#define ICON_DATETIME_SETUP                      0x0049
#define ICON_DATETIME_SETUP_M                    0x004A
#define ICON_DDD_OFF                             0x004B
#define ICON_DDD_OFF_M                           0x004C
#define ICON_DDD_ON                              0x004D
#define ICON_DDD_ON_M                            0x004E
#define ICON_DEFAULT                             0x004F
#define ICON_DEFAULT_M                           0x0050
#define ICON_DELETE                              0x0051
#define ICON_DELETE_ALL                          0x0052
#define ICON_DELETE_CURRENT                      0x0053
#define ICON_DELETE_M                            0x0054
#define ICON_DIR_DOWN                            0x0055
#define ICON_DIR_LEFT                            0x0056
#define ICON_DIR_RIGHT                           0x0057
#define ICON_DIR_UP                              0x0058
#define ICON_DPOF                                0x0059
#define ICON_DUALCAM_BEHIND                      0x005A
#define ICON_DUALCAM_BOTH                        0x005B
#define ICON_DUALCAM_BOTH_M                      0x005C
#define ICON_DUALCAM_FRONT                       0x005D
#define ICON_EV                                  0x005E
#define ICON_EV_M                                0x005F
#define ICON_EV_M0P3                             0x0060
#define ICON_EV_M0P6                             0x0061
#define ICON_EV_M1P0                             0x0062
#define ICON_EV_M1P3                             0x0063
#define ICON_EV_M1P6                             0x0064
#define ICON_EV_M2P0                             0x0065
#define ICON_EV_P0P0                             0x0066
#define ICON_EV_P0P3                             0x0067
#define ICON_EV_P0P6                             0x0068
#define ICON_EV_P1P0                             0x0069
#define ICON_EV_P1P3                             0x006A
#define ICON_EV_P1P6                             0x006B
#define ICON_EV_P2P0                             0x006C
#define ICON_FACE_OFF                            0x006D
#define ICON_FACE_ON                             0x006E
#define ICON_FACE_ON_M                           0x006F
#define ICON_FB_LEFT                             0x0070
#define ICON_FCW_FAR_ALERT                       0x0071
#define ICON_FCW_NEAR_ALERT                      0x0072
#define ICON_FCW_OFF                             0x0073
#define ICON_FCW_OFF_M                           0x0074
#define ICON_FCW_ON                              0x0075
#define ICON_FCW_ON_M                            0x0076
#define ICON_FF_RIGHT                            0x0077
#define ICON_FILE_VIDEO                          0x0078
#define ICON_FIRMWARE_UPDATE                     0x0079
#define ICON_FIRMWARE_UPDATE_M                   0x007A
#define ICON_FLASH_AUTO                          0x007B
#define ICON_FLASH_OFF                           0x007C
#define ICON_FLASH_ON                            0x007D
#define ICON_FLASH_ON_M                          0x007E
#define ICON_FLASH_REC                           0x007F
#define ICON_FLASH_REC_M                         0x0080
#define ICON_FLASH_RED_EYE                       0x0081
#define ICON_FLICK_50HZ                          0x0082
#define ICON_FLICK_60HZ                          0x0083
#define ICON_FORMAT                              0x0084
#define ICON_FORMAT_M                            0x0085
#define ICON_G_SENSOR                            0x0086
#define ICON_G_SENSOR_HIGH                       0x0087
#define ICON_G_SENSOR_LOW                        0x0088
#define ICON_G_SENSOR_M                          0x0089
#define ICON_G_SENSOR_MID                        0x008A
#define ICON_G_SENSOR_OFF                        0x008B
#define ICON_GOLF_REC                            0x008C
#define ICON_GOLF_REC_M                          0x008D
#define ICON_GPS_OFF                             0x008E
#define ICON_GPS_ON                              0x008F
#define ICON_GPS_ON_M                            0x0090
#define ICON_HDR                                 0x0091
#define ICON_HDR_M                               0x0092
#define ICON_HDR_OFF                             0x0093
#define ICON_HELP                                0x0094
#define ICON_HELP_M                              0x0095
#define ICON_HZ                                  0x0096
#define ICON_HZ_50                               0x0097
#define ICON_HZ_60                               0x0098
#define ICON_HZ_M                                0x0099
#define ICON_INFO                                0x009A
#define ICON_INFO_M                              0x009B
#define ICON_INTERNAL_FLASH                      0x009C
#define ICON_IRCUT_AUTO                          0x009D
#define ICON_IRCUT_OFF                           0x009E
#define ICON_IRCUT_ON_M                          0x009F
#define ICON_ISO                                 0x00A0
#define ICON_ISO_100                             0x00A1
#define ICON_ISO_200                             0x00A2
#define ICON_ISO_400                             0x00A3
#define ICON_ISO_800                             0x00A4
#define ICON_ISO_1600                            0x00A5
#define ICON_ISO_AUTO                            0x00A6
#define ICON_ISO_M                               0x00A7
#define ICON_LANDSCAPE                           0x00A8
#define ICON_LANGUAGE                            0x00A9
#define ICON_LANGUAGE_M                          0x00AA
#define ICON_LDWS_LEFT_ALERT                     0x00AB
#define ICON_LDWS_OFF                            0x00AC
#define ICON_LDWS_OFF_M                          0x00AD
#define ICON_LDWS_ON                             0x00AE
#define ICON_LDWS_ON_M                           0x00AF
#define ICON_LDWS_RIGHT_ALERT                    0x00B0
#define ICON_LOCK                                0x00B1
#define ICON_LOCK_ALL                            0x00B2
#define ICON_LOCK_ALL_M                          0x00B3
#define ICON_LOCK_CURRENT                        0x00B4
#define ICON_LOCK_CURRENT_M                      0x00B5
#define ICON_LOCK_M                              0x00B6
#define ICON_LOCK_UNLOCK                         0x00B7
#define ICON_LOCK_UNLOCK_M                       0x00B8
#define ICON_LOCK_UNLOKC_ALL                     0x00B9
#define ICON_LOCK_UNLOKC_ALL_M                   0x00BA
#define ICON_LPR_OFF                             0x00BB
#define ICON_LPR_OFF_M                           0x00BC
#define ICON_LPR_ON                              0x00BD
#define ICON_LPR_ON_M                            0x00BE
#define ICON_MENU_BACKLIGHT                      0x00BF
#define ICON_MENU_BACKLIGHT_F                    0x00C0
#define ICON_MENU_BL                             0x00C1
#define ICON_MENU_BL_F                           0x00C2
#define ICON_MENU_MODECHANG                      0x00C3
#define ICON_MENU_MODECHANG_M                    0x00C4
#define ICON_MENU_PRINT_OFF                      0x00C5
#define ICON_MENU_RETURN                         0x00C6
#define ICON_MENU_RETURN_M                       0x00C7
#define ICON_MENU_SETUP_ON_M                     0x00C8
#define ICON_MENU_SETUP_ON_PRESS                 0x00C9
#define ICON_MENU_WDR                            0x00CA
#define ICON_MENU_WDR_M                          0x00CB
#define ICON_MENU_WDR_OFF                        0x00CC
#define ICON_METERING                            0x00CD
#define ICON_METERING_M                          0x00CE
#define ICON_MODE_CAPTURE                        0x00CF
#define ICON_MODE_CAPTURE_M                      0x00D0
#define ICON_MODE_PLAYBACK                       0x00D1
#define ICON_MODE_PLAYBACK_M                     0x00D2
#define ICON_MODE_PLAYBACK_PRESS                 0x00D3
#define ICON_MODE_VIDEO                          0x00D4
#define ICON_MODE_VIDEO_M                        0x00D5
#define ICON_MODE_VIDEO_PRESS                    0x00D6
#define ICON_MOTION_DET_OFF                      0x00D7
#define ICON_MOTION_DET_ON                       0x00D8
#define ICON_MOTION_DET_ON_M                     0x00D9
#define ICON_NO                                  0x00DA
#define ICON_NO_M                                0x00DB
#define ICON_OK                                  0x00DC
#define ICON_OK_M                                0x00DD
#define ICON_OK_M_2                              0x00DE
#define ICON_OK2                                 0x00DF
#define ICON_OPERATE_BL                          0x00E0
#define ICON_OPERATE_BL_F                        0x00E1
#define ICON_OPERATE_DEL                         0x00E2
#define ICON_OPERATE_DEL_F                       0x00E3
#define ICON_OPERATE_EXIT                        0x00E4
#define ICON_OPERATE_EXIT_F                      0x00E5
#define ICON_OPERATE_FRONT                       0x00E6
#define ICON_OPERATE_LEFT                        0x00E7
#define ICON_OPERATE_LEFT_F                      0x00E8
#define ICON_OPERATE_LOCK                        0x00E9
#define ICON_OPERATE_LOCK_F                      0x00EA
#define ICON_OPERATE_PB                          0x00EB
#define ICON_OPERATE_PB_F                        0x00EC
#define ICON_OPERATE_PIP                         0x00ED
#define ICON_OPERATE_PIP_F                       0x00EE
#define ICON_OPERATE_PLAY                        0x00EF
#define ICON_OPERATE_PLAY_F                      0x00F0
#define ICON_OPERATE_RETURN                      0x00F1
#define ICON_OPERATE_RETURN_F                    0x00F2
#define ICON_OPERATE_RIGHT                       0x00F3
#define ICON_OPERATE_RIGHT_F                     0x00F4
#define ICON_OPERATE_SELECT                      0x00F5
#define ICON_OPERATE_SELECT_F                    0x00F6
#define ICON_OPERATE_SENSOR_B                    0x00F7
#define ICON_OPERATE_SENSOR_B_F                  0x00F8
#define ICON_OPERATE_SENSOR_F                    0x00F9
#define ICON_OPERATE_SENSOR_F_F                  0x00FA
#define ICON_OPERATE_SETUP                       0x00FB
#define ICON_OPERATE_SETUP_F                     0x00FC
#define ICON_OPERATE_URG                         0x00FD
#define ICON_OPERATE_URG_F                       0x00FE
#define ICON_OPTION_SELECT                       0x00FF
#define ICON_OPTION_SELECTF                      0x0100
#define ICON_PARK_MONITOR                        0x0101
#define ICON_PBMENU_LOOP                         0x0102
#define ICON_PBMENU_LOOP_F                       0x0103
#define ICON_PBMENU_PHOTO                        0x0104
#define ICON_PBMENU_PHOTO_F                      0x0105
#define ICON_PBMENU_URG                          0x0106
#define ICON_PBMENU_URG_F                        0x0107
#define ICON_PD_OFF                              0x0108
#define ICON_PD_OFF_M                            0x0109
#define ICON_PD_ON                               0x010A
#define ICON_PD_ON_M                             0x010B
#define ICON_PICTBRIDGE_S                        0x010C
#define ICON_PIM_OFF                             0x010D
#define ICON_PIM_OFF_M                           0x010E
#define ICON_PIM_ON                              0x010F
#define ICON_PIM_ON_M                            0x0110
#define ICON_PLAY_BACKWARD                       0x0111
#define ICON_PLAY_FORWARD                        0x0112
#define ICON_PLAY_PAUSE                          0x0113
#define ICON_PLAY_PLAY                           0x0114
#define ICON_PLAY_STEP                           0x0115
#define ICON_PLAY_STOP                           0x0116
#define ICON_POWER_OFF                           0x0117
#define ICON_POWER_OFF_M                         0x0118
#define ICON_PRINT                               0x0119
#define ICON_PROTECT                             0x011A
#define ICON_PROTECT_M                           0x011B
#define ICON_QUALITY                             0x011C
#define ICON_QUALITY_BASIC                       0x011D
#define ICON_QUALITY_FINE                        0x011E
#define ICON_QUALITY_M                           0x011F
#define ICON_QUALITY_NORMAL                      0x0120
#define ICON_QUICK_REVIEW                        0x0121
#define ICON_QUICK_REVIEW_M                      0x0122
#define ICON_REC_ELLIPSE                         0x0123
#define ICON_REC_M                               0x0124
#define ICON_REC_RECOVERY                        0x0125
#define ICON_REC_STOP_M                          0x0126
#define ICON_REC_TRANSPAENT                      0x0127
#define ICON_RESOLUTION                          0x0128
#define ICON_RESOLUTION_M                        0x0129
#define ICON_ROTATE                              0x012A
#define ICON_RSC_OFF                             0x012B
#define ICON_RSC_ON                              0x012C
#define ICON_RSC_ON_M                            0x012D
#define ICON_SCENE_MODE                          0x012E
#define ICON_SCENE_MODE_AUTO                     0x012F
#define ICON_SCENE_MODE_LANDSCPE                 0x0130
#define ICON_SCENE_MODE_M                        0x0131
#define ICON_SCENE_MODE_PORTRIAL                 0x0132
#define ICON_SCREENSAVER                         0x0133
#define ICON_SCREENSAVER_3MIN                    0x0134
#define ICON_SCREENSAVER_5MIN                    0x0135
#define ICON_SCREENSAVER_10MIN                   0x0136
#define ICON_SCREENSAVER_M                       0x0137
#define ICON_SCREENSAVER_OFF                     0x0138
#define ICON_SD_CARD                             0x0139
#define ICON_SD_LOCK                             0x013A
#define ICON_SELFTIMER                           0x013B
#define ICON_SELFTIMER_2SEC                      0x013C
#define ICON_SELFTIMER_5SEC                      0x013D
#define ICON_SELFTIMER_10SEC                     0x013E
#define ICON_SELFTIMER_M                         0x013F
#define ICON_SELFTIMER_OFF                       0x0140
#define ICON_SEQUENCE_NO                         0x0141
#define ICON_SETUP                               0x0142
#define ICON_SETUP_ABOUT                         0x0143
#define ICON_SETUP_ABOUT_F                       0x0144
#define ICON_SETUP_ALARM                         0x0145
#define ICON_SETUP_ALARM_F                       0x0146
#define ICON_SETUP_ANFA_ADAS                     0x0147
#define ICON_SETUP_ANFA_ADAS_F                   0x0148
#define ICON_SETUP_APP                           0x0149
#define ICON_SETUP_APP_F                         0x014A
#define ICON_SETUP_AUDIO                         0x014B
#define ICON_SETUP_AUDIO_F                       0x014C
#define ICON_SETUP_CYCLIC                        0x014D
#define ICON_SETUP_CYCLIC_F                      0x014E
#define ICON_SETUP_DATE                          0x014F
#define ICON_SETUP_DATE_F                        0x0150
#define ICON_SETUP_FORMAT                        0x0151
#define ICON_SETUP_FORMAT_F                      0x0152
#define ICON_SETUP_MOVIESIZE                     0x0153
#define ICON_SETUP_MOVIESIZE_F                   0x0154
#define ICON_SETUP_PARK                          0x0155
#define ICON_SETUP_PARK_F                        0x0156
#define ICON_SETUP_RESET                         0x0157
#define ICON_SETUP_RESET_F                       0x0158
#define ICON_SETUP_SCREENLIGHT                   0x0159
#define ICON_SETUP_SCREENLIGHT_F                 0x015A
#define ICON_SETUP_URGSENSE                      0x015B
#define ICON_SETUP_URGSENSE_F                    0x015C
#define ICON_SETUP_VOLUME                        0x015D
#define ICON_SETUP_VOLUME_F                      0x015E
#define ICON_SETUP_WIFI                          0x015F
#define ICON_SETUP_WIFI_F                        0x0160
#define ICON_SETUP_WIFIINFO                      0x0161
#define ICON_SETUP_WIFIINFO_F                    0x0162
#define ICON_SHAKE_OFF                           0x0163
#define ICON_SHAKE_ON                            0x0164
#define ICON_SHAKE_ON_M                          0x0165
#define ICON_SHARPNESS                           0x0166
#define ICON_SHARPNESS_HIGH                      0x0167
#define ICON_SHARPNESS_LOW                       0x0168
#define ICON_SHARPNESS_M                         0x0169
#define ICON_SHARPNESS_MED                       0x016A
#define ICON_SIGNAL_0STEP                        0x016B
#define ICON_SIGNAL_0STEP_M                      0x016C
#define ICON_SIGNAL_1STEP                        0x016D
#define ICON_SIGNAL_1STEP_M                      0x016E
#define ICON_SIGNAL_2STEP                        0x016F
#define ICON_SIGNAL_2STEP_M                      0x0170
#define ICON_SLIDESHOW                           0x0171
#define ICON_SLIDESHOW_2SEC                      0x0172
#define ICON_SLIDESHOW_5SEC                      0x0173
#define ICON_SLIDESHOW_8SEC                      0x0174
#define ICON_SLIDESHOW_M                         0x0175
#define ICON_SLIDESHOW_OFF                       0x0176
#define ICON_SMILE                               0x0177
#define ICON_SMILE_M                             0x0178
#define ICON_SNG_ALERT                           0x0179
#define ICON_SNG_OFF                             0x017A
#define ICON_SNG_OFF_M                           0x017B
#define ICON_SNG_ON                              0x017C
#define ICON_SNG_ON_M                            0x017D
#define ICON_SOUND_REC_OFF                       0x017E
#define ICON_SOUND_REC_ON                        0x017F
#define ICON_SOUND_REC_ON_M                      0x0180
#define ICON_SPEAKER                             0x0181
#define ICON_SYS_CAL                             0x0182
#define ICON_SYS_CAL_M                           0x0183
#define ICON_TIME_0                              0x0184
#define ICON_TIME_1                              0x0185
#define ICON_TIME_2                              0x0186
#define ICON_TIME_3                              0x0187
#define ICON_TIME_4                              0x0188
#define ICON_TIME_5                              0x0189
#define ICON_TIME_6                              0x018A
#define ICON_TIME_7                              0x018B
#define ICON_TIME_8                              0x018C
#define ICON_TIME_9                              0x018D
#define ICON_TIME_DOWN                           0x018E
#define ICON_TIME_DOWN_F                         0x018F
#define ICON_TIME_LAPSE_OFF                      0x0190
#define ICON_TIME_LAPSE_ON                       0x0191
#define ICON_TIME_LAPSE_ON_M                     0x0192
#define ICON_TIME_MARK                           0x0193
#define ICON_TIME_SELECT                         0x0194
#define ICON_TIME_SELECT_F                       0x0195
#define ICON_TIME_UP                             0x0196
#define ICON_TIME_UP_F                           0x0197
#define ICON_TOP_2K                              0x0198
#define ICON_TOP_AUDIO                           0x0199
#define ICON_TOP_AUDIO_OFF                       0x019A
#define ICON_TOP_BACK                            0x019B
#define ICON_TOP_BACK_OFF                        0x019C
#define ICON_TOP_BATTERY                         0x019D
#define ICON_TOP_FRONT                           0x019E
#define ICON_TOP_FRONT_OFF                       0x019F
#define ICON_TOP_PARK                            0x01A0
#define ICON_TOP_URG                             0x01A1
#define ICON_TOP_WIFI                            0x01A2
#define ICON_TSR_OFF                             0x01A3
#define ICON_TSR_OFF_M                           0x01A4
#define ICON_TSR_ON                              0x01A5
#define ICON_TSR_ON_M                            0x01A6
#define ICON_TV_MODE                             0x01A7
#define ICON_TV_MODE_M                           0x01A8
#define ICON_TV_NTSC                             0x01A9
#define ICON_TV_PAL                              0x01AA
#define ICON_URGENT_PROTECT_AUTO                 0x01AB
#define ICON_URGENT_PROTECT_AUTO_M               0x01AC
#define ICON_URGENT_PROTECT_MANUAL               0x01AD
#define ICON_URGENT_PROTECT_MANUAL_M             0x01AE
#define ICON_USB_MSDC                            0x01AF
#define ICON_USB_OFF                             0x01B0
#define ICON_USB_ON                              0x01B1
#define ICON_USB_ON_M                            0x01B2
#define ICON_USB_UVC                             0x01B3
#define ICON_VERSION                             0x01B4
#define ICON_VERSION_M                           0x01B5
#define ICON_VIDEO_FLIP_OFF                      0x01B6
#define ICON_VIDEO_FLIP_ON                       0x01B7
#define ICON_VIDEO_FLIP_ON_M                     0x01B8
#define ICON_VOICE                               0x01B9
#define ICON_VOICE_M                             0x01BA
#define ICON_VOL_0                               0x01BB
#define ICON_VOL_1                               0x01BC
#define ICON_VOL_2                               0x01BD
#define ICON_WB                                  0x01BE
#define ICON_WB_AUTO                             0x01BF
#define ICON_WB_CLOUDY                           0x01C0
#define ICON_WB_DAYLIGHT                         0x01C1
#define ICON_WB_FLUORESCENT                      0x01C2
#define ICON_WB_M                                0x01C3
#define ICON_WB_TUNGSTEN                         0x01C4
#define ICON_WIFI_CONNECTED                      0x01C5
#define ICON_WIFI_CONNECTING1                    0x01C6
#define ICON_WIFI_CONNECTING2                    0x01C7
#define ICON_WIFI_CONNECTING3                    0x01C8
#define ICON_WIFI_DOT_CONNECTING_OFF             0x01C9
#define ICON_WIFI_DOT_CONNECTING_ON              0x01CA
#define ICON_WIFI_FAIL                           0x01CB
#define ICON_WIFI_OFF                            0x01CC
#define ICON_WIFI_OFF_M                          0x01CD
#define ICON_WIFI_ON                             0x01CE
#define ICON_WIFI_ON_M                           0x01CF
#define ICON_YES                                 0x01D0
#define ICON_YES_M                               0x01D1
#define ICON_ACT_PUSH_BTN                        0x01D2

#endif //_DEMOKIT_IMAGE_H_
