//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPVERSION_H
#define UIMENUWNDSETUPVERSION_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupVersionCtrl;//Panel type 

extern VControl UIMenuSetupVersion_Static_TitleCtrl;//Static type 

extern VControl UIMenuSetupVersion_Static_VerCtrl;//Static type 

extern VControl UIMenuSetupVersion_Static_EthVerCtrl;//Static type 

extern VControl UIMenuSetupVersion_Static_SNCtrl;//Static type 

extern VControl UIMenuWndSetupVersion_Static_VerTxtCtrl;//Static type 

extern VControl UIMenuWndSetupVersion_Static_EthVerTxtCtrl;//Static type 

extern VControl UIMenuWndSetupVersion_Static_SNTxtCtrl;//Static type 

extern VControl UIMenuWndSetupVersion_Panel_OperateCtrl;//Panel type 

extern VControl UIMenuWndSetupVersion_BTN_ReturnCtrl;//Button type 

extern VControl UIMenuWndSetupVersion_BTN_ExitCtrl;//Button type 

//---------------------UIMenuWndSetupVersionCtrl User Export---------------------------
#endif
