//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPFORMATCONFIRM_H
#define UIMENUWNDSETUPFORMATCONFIRM_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupFormatConfirmCtrl;//Panel type 

extern VControl UIMenuWndSetupFormatConfirm_Static_TxtTopCtrl;//Static type 

extern VControl UIMenuWndSetupFormatConfirm_PanelCtrl;//Panel type 

extern VControl UIMenuWndSetupFormatConfirm_Static_TxtTipCtrl;//Static type 

extern VControl UIMenuWndSetupFormatConfirm_Static_TxtResetCtrl;//Static type 

extern VControl UIMenuWndSetupFormatConfirm_BTN_OKCtrl;//Button type 

extern VControl UIMenuWndSetupFormatConfirm_BTN_CancleCtrl;//Button type 

//---------------------UIMenuWndSetupFormatConfirmCtrl User Export---------------------------
#endif
