//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupVersionRes.c"
#include "UIMenuWndSetupVersion.h"
//#include "UIMenuWndSetupLoaderVersion.h"
#include "MenuCommonItem.h"
#include "UIFlow.h"
#include "EthCamAppCmd.h"

#define LD_VERSION_DISPLAY      ENABLE//DISABLE

//---------------------UIMenuWndSetupVersionCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupVersion)
CTRL_LIST_ITEM(UIMenuSetupVersion_Static_Title)
CTRL_LIST_ITEM(UIMenuSetupVersion_Static_Ver)
CTRL_LIST_ITEM(UIMenuSetupVersion_Static_EthVer)
CTRL_LIST_ITEM(UIMenuSetupVersion_Static_SN)
CTRL_LIST_ITEM(UIMenuWndSetupVersion_Static_VerTxt)
CTRL_LIST_ITEM(UIMenuWndSetupVersion_Static_EthVerTxt)
CTRL_LIST_ITEM(UIMenuWndSetupVersion_Static_SNTxt)
CTRL_LIST_ITEM(UIMenuWndSetupVersion_Panel_Operate)
CTRL_LIST_END

//----------------------UIMenuWndSetupVersionCtrl Event---------------------------
INT32 UIMenuWndSetupVersion_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupVersion)
EVENT_ITEM(NVTEVT_OPEN_WINDOW, UIMenuWndSetupVersion_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW, UIMenuWndSetupVersion_OnClose)
EVENT_ITEM(NVTEVT_KEY_LEFT, UIMenuWndSetupVersion_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT, UIMenuWndSetupVersion_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER, UIMenuWndSetupVersion_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndSetupVersion_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndSetupVersion_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2, UIMenuWndSetupVersion_OnKeyShutter2)
EVENT_END
extern char gEthcamFWVersion[33];
INT32 UIMenuWndSetupVersion_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
//currentInfo.
	EthCam_SendXMLCmd(0, ETHCAM_PORT_DEFAULT ,ETHCAM_CMD_TX_FW_VERSION, 0);
	UxStatic_SetData(&UIMenuWndSetupVersion_Static_VerTxtCtrl, STATIC_VALUE, Txt_Pointer(Prj_GetVersionString()));
	UxStatic_SetData(&UIMenuWndSetupVersion_Static_SNTxtCtrl, STATIC_VALUE, Txt_Pointer(Prj_GetVersionString()));
	debug_msg("ethcam version:%s\r\n",gEthcamFWVersion);
	debug_msg("ethcam version:%s\r\n",gEthcamFWVersion);
	UxStatic_SetData(&UIMenuWndSetupVersion_Static_EthVerTxtCtrl, STATIC_VALUE, Txt_Pointer(gEthcamFWVersion));
	Ux_DefaultEvent(pCtrl, NVTEVT_OPEN_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_DefaultEvent(pCtrl, NVTEVT_CLOSE_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndSetupVersionCtrl, 0);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if (LD_VERSION_DISPLAY == ENABLE)
	//Ux_OpenWindow(&UIMenuWndSetupLoaderVersionCtrl,0);
#endif
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndSetupVersionCtrl, 0);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if 0
	Ux_SendEvent(&UISetupObjCtrl, NVTEVT_FORCETO_LIVEVIEW_MODE, 0);
	return NVTEVT_CONSUME;
#else
	// the same behavior as ENTER key!
	return UIMenuWndSetupVersion_OnKeyEnter(pCtrl, paramNum, paramArray);
#endif
}


//----------------------UIMenuSetupVersion_Static_TitleCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupVersion_Static_Title)
EVENT_END

//----------------------UIMenuSetupVersion_Static_VerCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupVersion_Static_Ver)
EVENT_END

//----------------------UIMenuSetupVersion_Static_EthVerCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupVersion_Static_EthVer)
EVENT_END

//----------------------UIMenuSetupVersion_Static_SNCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupVersion_Static_SN)
EVENT_END

//----------------------UIMenuWndSetupVersion_Static_VerTxtCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupVersion_Static_VerTxt)
EVENT_END

//----------------------UIMenuWndSetupVersion_Static_EthVerTxtCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupVersion_Static_EthVerTxt)
EVENT_END

//----------------------UIMenuWndSetupVersion_Static_SNTxtCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupVersion_Static_SNTxt)
EVENT_END

//---------------------UIMenuWndSetupVersion_Panel_OperateCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupVersion_Panel_Operate)
CTRL_LIST_ITEM(UIMenuWndSetupVersion_BTN_Return)
CTRL_LIST_ITEM(UIMenuWndSetupVersion_BTN_Exit)
CTRL_LIST_END

//----------------------UIMenuWndSetupVersion_Panel_OperateCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupVersion_Panel_Operate)
EVENT_END

//----------------------UIMenuWndSetupVersion_BTN_ReturnCtrl Event---------------------------
INT32 UIMenuWndSetupVersion_BTN_Return_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_BTN_Return_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_BTN_Return_OnTouchPanelClick(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuWndSetupVersion_BTN_Return)
EVENT_ITEM(NVTEVT_PRESS,UIMenuWndSetupVersion_BTN_Return_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_USER_RELEASE,UIMenuWndSetupVersion_BTN_Return_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_CLICK,UIMenuWndSetupVersion_BTN_Return_OnTouchPanelClick)

EVENT_END

INT32 UIMenuWndSetupVersion_BTN_Return_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxButton_SetItemData(&UIMenuWndSetupVersion_BTN_ReturnCtrl, 0, BTNITM_ICONID, ICON_OPERATE_RETURN_F);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupVersion_BTN_Return_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxButton_SetItemData(&UIMenuWndSetupVersion_BTN_ReturnCtrl, 0, BTNITM_ICONID, ICON_OPERATE_RETURN);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupVersion_BTN_Return_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndSetupVersionCtrl, 0);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupVersion_BTN_ExitCtrl Event---------------------------
INT32 UIMenuWndSetupVersion_BTN_Exit_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_BTN_Exit_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_BTN_Exit_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupVersion_BTN_Exit)
EVENT_ITEM(NVTEVT_PRESS,UIMenuWndSetupVersion_BTN_Exit_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_USER_RELEASE,UIMenuWndSetupVersion_BTN_Exit_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_CLICK,UIMenuWndSetupVersion_BTN_Exit_OnTouchPanelClick)
EVENT_END

INT32 UIMenuWndSetupVersion_BTN_Exit_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxButton_SetItemData(&UIMenuWndSetupVersion_BTN_ExitCtrl, 0, BTNITM_ICONID, ICON_OPERATE_EXIT_F);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupVersion_BTN_Exit_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxButton_SetItemData(&UIMenuWndSetupVersion_BTN_ExitCtrl, 0, BTNITM_ICONID, ICON_OPERATE_EXIT);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupVersion_BTN_Exit_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndSetupVersionCtrl, 1, 0);

    return NVTEVT_CONSUME;
}
