//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPDEFAULTSETTING_H
#define UIMENUWNDSETUPDEFAULTSETTING_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupDefaultSettingCtrl;//Panel type 

extern VControl UIMenuWndSetupDefaultSetting_Static_TxtTopCtrl;//Static type 

extern VControl UIMenuWndSetupDefaultSetting_PanelCtrl;//Panel type 

extern VControl UIMenuWndSetupDefaultSetting_Static_TxtTipCtrl;//Static type 

extern VControl UIMenuWndSetupDefaultSetting_Static_TxtResetCtrl;//Static type 

extern VControl UIMenuWndSetupDefaultSetting_BTN_OKCtrl;//Button type 

extern VControl UIMenuWndSetupDefaultSetting_BTN_CancleCtrl;//Button type 

//---------------------UIMenuWndSetupDefaultSettingCtrl User Export---------------------------
#endif
