//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupWiFiInfoRes.c"
#include "UIMenuWndSetupWiFiInfo.h"
#include "PrjCfg.h"
#include "UIInfo.h"

//---------------------UIMenuWndSetupWiFiInfoCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPWIFIINFO_ERROR_MSG        1
#define _UIMENUWNDSETUPWIFIINFO_TRACE_MSG        0

#if (_UIMENUWNDSETUPWIFIINFO_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupWiFiInfoErrMsg(...)            debug_msg ("^R UIMenuWndSetupWiFiInfo: "__VA_ARGS__)
#else
#define UIMenuWndSetupWiFiInfoErrMsg(...)
#endif

#if (_UIMENUWNDSETUPWIFIINFO_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupWiFiInfoTraceMsg(...)          debug_msg ("^B UIMenuWndSetupWiFiInfo: "__VA_ARGS__)
#else
#define UIMenuWndSetupWiFiInfoTraceMsg(...)
#endif

//---------------------UIMenuWndSetupWiFiInfoCtrl Global Variables -----------------------------

//---------------------UIMenuWndSetupWiFiInfoCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupWiFiInfoCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupWiFiInfoCtrl Private API  ---------------------------------
//---------------------UIMenuWndSetupWiFiInfoCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupWiFiInfo)
CTRL_LIST_ITEM(UIMenuWndSetupWiFiInfo_Static_Title)
CTRL_LIST_ITEM(UIMenuWndSetupWiFiInfo_Static_QRCode)
CTRL_LIST_ITEM(UIMenuWndSetupWiFiInfo_Panel_Info)
CTRL_LIST_ITEM(UIMenuWndSetupWiFiInfo_Panel_Operate)
CTRL_LIST_END

//----------------------UIMenuWndSetupWiFiInfoCtrl Event---------------------------
INT32 UIMenuWndSetupWiFiInfo_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupWiFiInfo_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupWiFiInfo)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupWiFiInfo_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupWiFiInfo_OnClose)
EVENT_END
static CHAR WIFINAME[64] ={0};
static CHAR WIFIPASSPHRASE[64] ={0};
extern char *UINet_GetPASSPHRASE(void);

#include "UIDisplay.h"
#include "QR_Encode.h"
#include "WiFiIpcAPI.h"
#include "UIInfo.h"
#include "UICfgDefault.h"

UINT32 g_QRWidth;
unsigned char g_QRBuf[MAX_BITDATA];
extern char gMacAddr[6];
#define WbeSite 	"http://www.cruise-cloud.com/mt_app_download/download_WIFI_mt.html"
static INT32 InputNum = -1;
INT32 UIMenuWndSetupWiFiInfo_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	InputNum =  paramNum;
	char *pMacAddr;
	UIMenuStoreInfo *ptMenuStoreInfo = UI_GetMenuInfo();
	memset(WIFINAME,0,sizeof(WIFINAME));
	memset(WIFIPASSPHRASE,0,sizeof(WIFIPASSPHRASE));
	if ( paramNum == 0)
	{
		UxCtrl_SetShow(&UIMenuWndSetupWiFiInfo_Static_IDCtrl, FALSE);
		UxCtrl_SetShow(&UIMenuWndSetupWiFiInfo_Static_IDTxtCtrl, FALSE);
		UxCtrl_SetShow(&UIMenuWndSetupWiFiInfo_Static_PWDCtrl, FALSE);
		UxCtrl_SetShow(&UIMenuWndSetupWiFiInfo_Static_PWDTxtCtrl, FALSE);

		UxStatic_SetData(&UIMenuWndSetupWiFiInfo_Static_TitleCtrl, STATIC_VALUE, STRID_SETUP_APP);

		char ChargeWebSit[128]={0};
		 sprintf(ChargeWebSit,WbeSite);
		g_QRWidth = QRCode_Encode((unsigned char *)ChargeWebSit, g_QRBuf, sizeof(g_QRBuf));
		debug_msg("QRCode width = %d mac:%s\r\n", g_QRWidth, ChargeWebSit);
		
		Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
	    	return NVTEVT_CONSUME;
	}
			 
	if (ptMenuStoreInfo->strSSID[0] == 0) {
		CHKPNT;
			pMacAddr = (char *)UINet_GetMAC();
			snprintf(WIFINAME, sizeof(WIFINAME), "%s%02x%02x", UINet_GetSSID(), pMacAddr[4], pMacAddr[5]);
			
		}//pMacAddr[0], pMacAddr[1], pMacAddr[2], pMacAddr[3],% 02x%02x%02x%02x
		else {
				snprintf(WIFINAME, sizeof(WIFINAME), "%s", UINet_GetSSID());
			}
		debug_msg("%02x %02x \r\n", pMacAddr[4], pMacAddr[5]);
		if (ptMenuStoreInfo->strPASSPHRASE[0] != 0) 
		{
			snprintf(WIFIPASSPHRASE, sizeof(WIFIPASSPHRASE), "%s", UINet_GetPASSPHRASE());

		}else{
			snprintf(WIFIPASSPHRASE, sizeof(WIFIPASSPHRASE), "%s", UINet_GetPASSPHRASE());
		}

	
		UxStatic_SetData(&UIMenuWndSetupWiFiInfo_Static_IDTxtCtrl, STATIC_VALUE, Txt_Pointer(WIFINAME));
		UxStatic_SetData(&UIMenuWndSetupWiFiInfo_Static_PWDTxtCtrl, STATIC_VALUE, Txt_Pointer(WIFIPASSPHRASE));
		UxCtrl_SetShow(&UIMenuWndSetupWiFiInfo_Static_IDCtrl, TRUE);
		UxCtrl_SetShow(&UIMenuWndSetupWiFiInfo_Static_IDTxtCtrl, TRUE);
		UxCtrl_SetShow(&UIMenuWndSetupWiFiInfo_Static_PWDCtrl, TRUE);
		UxCtrl_SetShow(&UIMenuWndSetupWiFiInfo_Static_PWDTxtCtrl, TRUE);
		UxStatic_SetData(&UIMenuWndSetupWiFiInfo_Static_TitleCtrl, STATIC_VALUE, STRID_SETUP_WIFIINFO);

	{
		  UINT32 result =0;
       			

	//	  if (g_uiUpdateInfoTimerID == NULL_TIMER) {
	//		  g_uiUpdateInfoTimerID = GxTimer_StartTimer(TIMER_HALF_SEC, NVTEVT_05SEC_TIMER, CONTINUE);
	//	  }
	  
		  result = WiFiIpc_init_wlan0_netdev(0); 
		  debug_msg("Liwk ---- Wifi Result :%d \r\n", result);
		  if (WiFiIpc_get_wlan0_efuse_mac(gMacAddr) < 0)
		  {
			 debug_msg("Liwk --- GetMac Fail!!!\r\n");
		  }
		  else
		  {
			 /* Generate QRCode */
			 //#NT#2016/12/27#KCHong -begin
			 //#NT#QRCode sample code
			 char WiFiInfo[64];
			 char sMacStr[32];
			 CHKPNT;
			 sprintf(sMacStr,"%s%02x%02x",UINet_GetSSID(), gMacAddr[4], gMacAddr[5]);//%02x%02x%02x%02x ssid gMacAddr[0],gMacAddr[1],gMacAddr[2],gMacAddr[3],
			 snprintf(WiFiInfo, 50, "SSID:%s \n  PWD:%s", sMacStr, UINet_GetPASSPHRASE() );
			 g_QRWidth = QRCode_Encode(WiFiInfo, g_QRBuf, sizeof(g_QRBuf));
			 debug_msg("QRCode width = %d mac:%s\r\n", g_QRWidth, sMacStr);
			 //#NT#2016/12/27#KCHong -end
		}
	}
	
	Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupWiFiInfo_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	InputNum = -1;
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

//----------------------UIMenuWndSetupWiFiInfo_Static_TitleCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupWiFiInfo_Static_Title)
EVENT_END

//----------------------UIMenuWndSetupWiFiInfo_Static_QRCodeCtrl Event---------------------------
INT32 UIMenuWndSetupWiFiInfo_Static_QRCode_OnRedraw(VControl *, UINT32, UINT32 *);


EVENT_BEGIN(UIMenuWndSetupWiFiInfo_Static_QRCode)
EVENT_ITEM(NVTEVT_REDRAW,UIMenuWndSetupWiFiInfo_Static_QRCode_OnRedraw)

EVENT_END

void _DrawQRCode(UIScreen ScreenObj, URECT QRBase, UINT32 Margin, unsigned char *QRBuf, UINT32 QRWidth)
{
	UPOINT Current;
	UINT32 i, j;
	UINT32 ByteIdx, BitIdx;

	if (QRWidth == 0)
		return;

   
	// Draw background
	GxGfx_SetShapeColor(CLRID_IDX_WHITE, CLRID_IDX_WHITE, NULL);
	GxGfx_FillRect(((DC**)ScreenObj)[GxGfx_OSD], QRBase.x, QRBase.y, QRBase.x+(QRWidth+Margin*2)*QRBase.w, QRBase.y + (QRWidth+Margin*2)*QRBase.h);
	Current.x = QRBase.x+Margin*QRBase.w;
	Current.y = QRBase.y+Margin*QRBase.h;

	// Draw qrcode
	GxGfx_SetShapeColor(CLRID_IDX_BLACK, CLRID_IDX_BLACK, NULL);
	for (i = 0; i < QRWidth; i++) {
		for (j = 0; j < QRWidth; j++) {
			ByteIdx = (i*QRWidth+j)/8;
			BitIdx = (i*QRWidth+j)%8;
			if (QRBuf[ByteIdx] & (0x80 >> BitIdx)) {
				GxGfx_FillRect(((DC**)ScreenObj)[GxGfx_OSD], Current.x, Current.y, Current.x+QRBase.w, Current.y+QRBase.h);
			}
			Current.x += QRBase.w;
		}  
		Current.x = QRBase.x+Margin * QRBase.w;
		Current.y = QRBase.y+(Margin+i+1)*QRBase.h;
	}
}

void _ShowOSDString(UIScreen ScreenObj,CHAR *pString, UINT16 uiX, UINT16 uiY, UINT16 uiColor)
{
    #if 1
    GxGfx_SetTextColor(uiColor, _OSD_INDEX_GRAY, 0);
    GxGfx_Text(((DC**)ScreenObj)[GxGfx_OSD], uiX, uiY, pString);
    #else
    debug_err(("SenFP_ShowOSDString is empty function\r\n"));
    #endif
}

extern UIMenuStoreInfo  currentInfo;
extern char gSSID[NVT_WSC_MAX_SSID_LEN];
extern char gPASSPHRASE[NVT_MAX_WEP_KEY_LEN];
extern char unicode_string0[32];
extern char  unicode_string1[32];
extern char unicode_string2[26];


INT32 UIMenuWndSetupWiFiInfo_Static_QRCode_OnRedraw(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIScreen ScreenObj = *paramArray;
	//URECT QRBase = {0};
	URECT	 QRBase;
	if ( InputNum == 0){ 
			 QRBase.x =30;
			 QRBase.y = 3;
			 QRBase.w = 4;
			 QRBase.h = 4;// app 
	}else{ 
			QRBase.x = 0;
			 QRBase.y = 36;
			 QRBase.w = 4;
			 QRBase.h = 4; // wifi info 
	}   
	  
	UINT32 QRMargin = 2;
	BOOL bReadMenuInfo;
	char pString[128];
	
    Ux_DefaultEvent(pCtrl, NVTEVT_REDRAW, paramNum, paramArray);
	if(1)
	{  
	CHKPNT;
		_DrawQRCode(ScreenObj, QRBase, QRMargin, (unsigned char *)g_QRBuf, g_QRWidth);
	
        
//*		
	//	memset(&pString[0], 0, 128);
	//	sprintf(pString,"%s", unicode_string0);
         //    _ShowOSDString(ScreenObj,pString, 10, 120, 4);

	//	memset(&pString[0], 0, 128);
       //      sprintf(pString, "%s",unicode_string1);
      //       _ShowOSDString(ScreenObj, pString, 10,130, 4); //120

	//	memset(&pString[0], 0, 128);
      //       sprintf(pString, "%s",unicode_string2);
      //       _ShowOSDString(ScreenObj, pString, 10,140, 4); //120
     //        */
		#if 0

		//run every 500ms 
        if(Load_MenuInfoForDisp())
        {
              memset(&pString[0], 0, 128);
     			 sprintf(pString, "VER: %s", Prj_GetVersionString());
             _ShowOSDString(ScreenObj,pString, 10, 120, 4);
             
             
             memset(&pString[0], 0, 128);
             sprintf(pString, "MAC:");
             _ShowOSDString(ScreenObj, pString, 120,35, 1); //120
             
             memset(&pString[0], 0, 128);
             sprintf(pString, "%02x%02x%02x%02x%02x%02x",gMacAddr[0], gMacAddr[1],gMacAddr[2], gMacAddr[3],gMacAddr[4], gMacAddr[5]);
             _ShowOSDString(ScreenObj, pString, 120,60, 1); //120
             
             if(!strcmp(UI_GetSNInfo(), DEFAULT_SN))
             {
                memset(&pString[0], 0, 128);
                sprintf(pString, "UID: Not Written Error!!!");	    
                _ShowOSDString(ScreenObj, pString, 10, 140, 3);//10
             }else{
                memset(&pString[0], 0, 128);
                sprintf(pString, "UID: %s", UI_GetSNInfo());
                _ShowOSDString(ScreenObj, pString, 10,140, 4);//10
             }
             
             if(currentInfo.strSSID[0] == 0)
             {
                #if (MAC_APPEN_SSID==ENABLE)
                sprintf(currentInfo.strSSID,"CAR-DVR-%02x%02x",gMacAddr[4], gMacAddr[5]);
                #else
                sprintf(currentInfo.strSSID,"%s",gSSID);
                #endif
                sprintf(currentInfo.strPASSPHRASE,"%s",gPASSPHRASE);
             }
             
             memset(&pString[0], 0, 128);
             sprintf(pString, "SSID:%s",currentInfo.strSSID);
             _ShowOSDString(ScreenObj, pString, 10,160, 1);
             
             memset(&pString[0], 0, 128);
             sprintf(pString, "PSW:%s",currentInfo.strPASSPHRASE);
             _ShowOSDString(ScreenObj, pString, 10,180, 1);	
             
             if(1)
             {
                memset(&pString[0], 0, 128);
                sprintf(pString, "%s %s",__DATE__, __TIME__);
                _ShowOSDString(ScreenObj, pString, 10,200, 1);
             }  
        }
		#endif
	}

    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndSetupWiFiInfo_Panel_InfoCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupWiFiInfo_Panel_Info)
CTRL_LIST_ITEM(UIMenuWndSetupWiFiInfo_Static_ID)
CTRL_LIST_ITEM(UIMenuWndSetupWiFiInfo_Static_IDTxt)
CTRL_LIST_ITEM(UIMenuWndSetupWiFiInfo_Static_PWD)
CTRL_LIST_ITEM(UIMenuWndSetupWiFiInfo_Static_PWDTxt)
CTRL_LIST_END

//----------------------UIMenuWndSetupWiFiInfo_Panel_InfoCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupWiFiInfo_Panel_Info)
EVENT_END

//----------------------UIMenuWndSetupWiFiInfo_Static_IDCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupWiFiInfo_Static_ID)
EVENT_END

//----------------------UIMenuWndSetupWiFiInfo_Static_IDTxtCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupWiFiInfo_Static_IDTxt)
EVENT_END

//----------------------UIMenuWndSetupWiFiInfo_Static_PWDCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupWiFiInfo_Static_PWD)
EVENT_END

//----------------------UIMenuWndSetupWiFiInfo_Static_PWDTxtCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupWiFiInfo_Static_PWDTxt)
EVENT_END

//---------------------UIMenuWndSetupWiFiInfo_Panel_OperateCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupWiFiInfo_Panel_Operate)
CTRL_LIST_ITEM(UIMenuWndSetupWiFiInfo_BTN_Return)
CTRL_LIST_ITEM(UIMenuWndSetupWiFiInfo_BTN_Exit)
CTRL_LIST_END

//----------------------UIMenuWndSetupWiFiInfo_Panel_OperateCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupWiFiInfo_Panel_Operate)
EVENT_END

//----------------------UIMenuWndSetupWiFiInfo_BTN_ReturnCtrl Event---------------------------
INT32 UIMenuWndSetupWiFiInfo_BTN_Return_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupWiFiInfo_BTN_Return_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupWiFiInfo_BTN_Return_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupWiFiInfo_BTN_Return)
EVENT_ITEM(NVTEVT_PRESS,UIMenuWndSetupWiFiInfo_BTN_Return_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_USER_RELEASE,UIMenuWndSetupWiFiInfo_BTN_Return_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_CLICK,UIMenuWndSetupWiFiInfo_BTN_Return_OnTouchPanelClick)
EVENT_END

INT32 UIMenuWndSetupWiFiInfo_BTN_Return_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
//UIMenuWndSetupWiFiInfo_Static_IDTxtCtrl,
    UxButton_SetItemData(&UIMenuWndSetupWiFiInfo_BTN_ReturnCtrl, 0, BTNITM_ICONID, ICON_OPERATE_RETURN_F);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupWiFiInfo_BTN_Return_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxButton_SetItemData(&UIMenuWndSetupWiFiInfo_BTN_ReturnCtrl, 0, BTNITM_ICONID, ICON_OPERATE_RETURN);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupWiFiInfo_BTN_Return_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	InputNum = -1;
    Ux_CloseWindow(&UIMenuWndSetupWiFiInfoCtrl, 0);
    return NVTEVT_CONSUME;
}


//----------------------UIMenuWndSetupWiFiInfo_BTN_ExitCtrl Event---------------------------
INT32 UIMenuWndSetupWiFiInfo_BTN_Exit_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupWiFiInfo_BTN_Exit_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupWiFiInfo_BTN_Exit_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupWiFiInfo_BTN_Exit)
EVENT_ITEM(NVTEVT_PRESS,UIMenuWndSetupWiFiInfo_BTN_Exit_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_USER_RELEASE,UIMenuWndSetupWiFiInfo_BTN_Exit_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_CLICK,UIMenuWndSetupWiFiInfo_BTN_Exit_OnTouchPanelClick)
EVENT_END

INT32 UIMenuWndSetupWiFiInfo_BTN_Exit_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxButton_SetItemData(&UIMenuWndSetupWiFiInfo_BTN_ExitCtrl, 0, BTNITM_ICONID, ICON_OPERATE_EXIT_F);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupWiFiInfo_BTN_Exit_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxButton_SetItemData(&UIMenuWndSetupWiFiInfo_BTN_ExitCtrl, 0, BTNITM_ICONID, ICON_OPERATE_EXIT);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndSetupWiFiInfo_BTN_Exit_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//	    Ux_CloseWindow(&MenuCommonItemCtrl, 0);
	InputNum = -1;
    Ux_CloseWindow(&UIMenuWndSetupWiFiInfoCtrl, 1, 0);

    return NVTEVT_CONSUME;
}

