//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPWIFIINFO_H
#define UIMENUWNDSETUPWIFIINFO_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupWiFiInfoCtrl;//Panel type 

extern VControl UIMenuWndSetupWiFiInfo_Static_TitleCtrl;//Static type 

extern VControl UIMenuWndSetupWiFiInfo_Static_QRCodeCtrl;//Static type 

extern VControl UIMenuWndSetupWiFiInfo_Panel_InfoCtrl;//Panel type 

extern VControl UIMenuWndSetupWiFiInfo_Static_IDCtrl;//Static type 

extern VControl UIMenuWndSetupWiFiInfo_Static_IDTxtCtrl;//Static type 

extern VControl UIMenuWndSetupWiFiInfo_Static_PWDCtrl;//Static type 

extern VControl UIMenuWndSetupWiFiInfo_Static_PWDTxtCtrl;//Static type 

extern VControl UIMenuWndSetupWiFiInfo_Panel_OperateCtrl;//Panel type 

extern VControl UIMenuWndSetupWiFiInfo_BTN_ReturnCtrl;//Button type 

extern VControl UIMenuWndSetupWiFiInfo_BTN_ExitCtrl;//Button type 

//---------------------UIMenuWndSetupWiFiInfoCtrl User Export---------------------------
#endif
