//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDWAITMOMENT_H
#define UIFLOWWNDWAITMOMENT_H

#include "UIFramework.h"

extern VControl UIFlowWndWaitMomentCtrl;//Panel type

extern VControl UIFlowWndWaitMoment_StatusTXT_MsgCtrl;//Status type

typedef enum
{
	UIFlowWndWaitMoment_StatusTXT_Msg_STRID_ENTER_PARKING,
	UIFlowWndWaitMoment_StatusTXT_Msg_STRID_PLEASE_WAIT,
	UIFlowWndWaitMoment_StatusTXT_Msg_STRID_FORMACT_SD,
	UIFlowWndWaitMoment_StatusTXT_Msg_STRID_ETHCAM_DETFAIL,
	UIFlowWndWaitMoment_StatusTXT_Msg_STRID_RESTART_REC,
	UIFlowWndWaitMoment_StatusTXT_Msg_STRID_STOPREC_WAIT,
	UIFlowWndWaitMoment_StatusTXT_Msg_STRID_ETHCAM_UDFW_SENDFW,
	UIFlowWndWaitMoment_StatusTXT_Msg_STRID_ETHCAM_UDFW_START,
	UIFlowWndWaitMoment_StatusTXT_Msg_STRID_ETHCAM_UDFW_FINISH,
	UIFlowWndWaitMoment_StatusTXT_Msg_STRID_MOVIE_BACK_MSG,
	UIFlowWndWaitMoment_StatusTXT_Msg_STRID_ETHCAM_CHANGE_BEHINDCAM,
	UIFlowWndWaitMoment_StatusTXT_Msg_STRID_ENTER_SHUTDOWN,
	UIFlowWndWaitMoment_StatusTXT_Msg_STRID_ETHCAM_CHANGE_FRONTCAM,
	UIFlowWndWaitMoment_StatusTXT_Msg_STRID_SLOW_CARD,
	UIFlowWndWaitMoment_StatusTXT_Msg_STRID_ETHCAM_FW_LOSTED,
	UIFlowWndWaitMoment_StatusTXT_Msg_STRID_ETHCAM_UPDATE_FAILED,
	UIFlowWndWaitMoment_StatusTXT_Msg_STRID_ETHCAM_SENDFW_FAILED,
	UIFlowWndWaitMoment_StatusTXT_Msg_MAX
} UIFlowWndWaitMoment_StatusTXT_Msg_Setting;

extern VControl UIFlowWndWaitMomentButtonNoCtrl;//Button type 

extern VControl UIFlowWndWaitMomentButtonYesCtrl;//Button type 

extern VControl UIFlowWndWaitMoment_ProgressBarCtrl;//ProgressBar type 
//---------------------UIFlowWndWaitMomentCtrl User Export---------------------------
#endif
