//This source code is generated by UI Designer Studio.

#include "stdio.h"
#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "NVTToolCommand.h"
#include "UIMenuWndWiFiMobileLinkOKRes.c"
#include "WifiAppCmd.h"
#include "UIFlow.h"
#include "UIAppNetwork.h"
//#NT#2016/05/31#Ben Wang -begin
//#NT#Add UVC multimedia function.
#if(UVC_MULTIMEDIA_FUNC == ENABLE)
#include "ImageUnit_UsbUVAC.h"
#include "UsbCmdAPI.h"
#endif
//#NT#2016/05/31#Ben Wang -end
//---------------------UIMenuWndWiFiMobileLinkOKCtrl Debug Definition -----------------------------
#define _UIMENUWNDWIFIMOBILELINKOK_ERROR_MSG        1
#define _UIMENUWNDWIFIMOBILELINKOK_TRACE_MSG        1

#if (_UIMENUWNDWIFIMOBILELINKOK_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndWiFiMobileLinkOKErrMsg(...)            debug_msg ("^R UIMenuWndWiFiMobileLinkOK: "__VA_ARGS__)
#else
#define UIMenuWndWiFiMobileLinkOKErrMsg(...)
#endif

#if (_UIMENUWNDWIFIMOBILELINKOK_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndWiFiMobileLinkOKTraceMsg(...)          debug_msg ("^B UIMenuWndWiFiMobileLinkOK: "__VA_ARGS__)
#else
#define UIMenuWndWiFiMobileLinkOKTraceMsg(...)
#endif

//---------------------UIMenuWndWiFiMobileLinkOKCtrl Global Variables -----------------------------

//---------------------UIMenuWndWiFiMobileLinkOKCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndWiFiMobileLinkOKCtrl Public API  ----------------------------------

//---------------------UIMenuWndWiFiMobileLinkOKCtrl Private API  ---------------------------------
//---------------------UIMenuWndWiFiMobileLinkOKCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiMobileLinkOK)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_RE)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Panel_TopNormal)
//CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Panel_Operate) //cancle this function
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_BackLightLvl_Panel)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Panel_Datetime)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_Alarm_L)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_Alarm_R)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_PanelExitWifi)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Panel_EMRBar)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_ENRTime)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_EmrStatusTxT_Title)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_PlaybackModePanel)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Panel_RecUrg)
CTRL_LIST_END
  
char StringTmpBuf[32] = {0};
//#MT CJ 2020/7/6 BEGIN
static UINT32  gUIMenuWndWiFiTimerID = NULL_TIMER;
static UINT32 g_UILCAAlarmTimerID = NULL_TIMER;

extern BOOL  bflag_EthLinkFinish;
static BOOL bLCA_Alarm_L = FALSE;
static BOOL bLCA_Alarm_R = FALSE;
static UINT8 uiLCA_Alarm_level_Left = 0;
static UINT8 uiLCA_Alarm_level_Right = 0;
static BOOL bFocusBackLightAdj = FALSE;
static INT32 iTouchBLAdjHoldPointInit = 0;
static INT32 iTouchBLAdjHoldPointCur = 0;
static INT32 iTouchBLAdjHoldPointPrev = 0;
static UINT32 uiIgnoreTimerID = NULL_TIMER;
#define LCD_BRI_LVL_DISP_TIME  10
BOOL 	bDisplayWifiExit = FALSE;
UINT32 	WifiExitCount = 0;
static UINT32  g_WifiCurrTime = 0;
static CHAR    g_WifiEMRCurrTimeStr[20] = {0};
  UINT32	g_WifiEmergencyRecSetp ;
 UINT32   g_WifiEmergencyRecTime ;
 UINT32   g_WifiEmergencyRecSetpTotail ;
//extern void UIFlowWndMovie_SetBriAdjBarShowTime(INT32 value);
//extern void UIFlowWndMovie_DecBriAdjBarShowTime(void);
extern UINT32 EthCamNet_GetEthLinkStatus(ETHCAM_PATH_ID path_id);
extern UINT32  socketCliEthData1_IsRecv(ETHCAM_PATH_ID path_id);
extern UINT32 CalWeek_CurDay(UINT32 year, UINT32 month, UINT32 day);
void   FlowWifiMovie_IconDrawDateTime(void);
void   FlowWifiMovie_IconHideDateTime(void);
void   FlowWifiMovie_IconDrawBackLightLvl_Panel(void);
void	 FlowWifiMovie_IconHideBackLightLvl_Panel(void);
void	 FlowWifiMovie_IconDrawTopIcon(void);
void	 FlowWifiMovie_IconHideTopIcon(void);
void	 FlowWifiMovie_IconHideAlarm(void);
void  FlowWifiMovie_IconHideEmr(void);
void  FlowWifiMovie_IconDrawEmr(void);
void  FlowWifiMovie_IconHideExitWifiMsg(void);
void  FlowWifiMovie_IconDrawExitWifiMsg(void);
void 	Fun_WifiUpdateIcon(BOOL bShow);
//#MT CJ 2020/7/6 end
#if 1
//#MT CJ 2020/7/6 begin
void FlowWifiMovie_IconDrawDateTime(void)
{
    struct tm Curr_DateTime;
    Curr_DateTime = HwClock_GetTime(TIME_ID_CURRENT);

    static CHAR date_strMonth[20] = {0}, date_strDay[3] = {0};
    CHAR cTime_HourH, cTime_HourL, cTime_MinH, cTime_MinL;
    static BOOL bDot_draw = FALSE;

    //Date
    snprintf(date_strMonth, sizeof(date_strMonth), "%02d", Curr_DateTime.tm_mon);
    snprintf(date_strDay, 3, "%02d", Curr_DateTime.tm_mday);
    UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_Static_DateTxtMCtrl, STATIC_VALUE, Txt_Pointer(date_strMonth));
    UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_Static_DateTxtDCtrl, STATIC_VALUE, Txt_Pointer(date_strDay));

    //Time
    cTime_HourH = Curr_DateTime.tm_hour / 10;
    cTime_HourL = Curr_DateTime.tm_hour % 10;
    cTime_MinH = Curr_DateTime.tm_min / 10;
    cTime_MinL = Curr_DateTime.tm_min % 10;
    UxState_SetData(&UIMenuWndWiFiMobileLinkOK_Status_TimeHourHCtrl, STATE_CURITEM, cTime_HourH);
    UxState_SetData(&UIMenuWndWiFiMobileLinkOK_Status_TimeHourLCtrl, STATE_CURITEM, cTime_HourL);
    UxState_SetData(&UIMenuWndWiFiMobileLinkOK_Status_TimeMinHCtrl, STATE_CURITEM, cTime_MinH);
    UxState_SetData(&UIMenuWndWiFiMobileLinkOK_Status_TimeMinLCtrl, STATE_CURITEM, cTime_MinL);

    //week
    Curr_DateTime.tm_wday = CalWeek_CurDay(Curr_DateTime.tm_year, Curr_DateTime.tm_mon, Curr_DateTime.tm_mday);
    UxState_SetData(&UIMenuWndWiFiMobileLinkOK_Status_WeekCtrl, STATE_CURITEM, Curr_DateTime.tm_wday);


    //DOT
    if(bDot_draw){
        bDot_draw = FALSE;
        UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Static_MarkCtrl, FALSE);
    } else {
        bDot_draw = TRUE;
        UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Static_MarkCtrl, TRUE);
    }

    UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Panel_DatetimeCtrl, TRUE);
}

void FlowWifiMovie_IconHideDateTime(void)
{
    UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Panel_DatetimeCtrl, FALSE);
}

void 	FlowWifiMovie_IconDrawBackLightLvl_Panel(void)
{

	    UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_BackLightLvl_BarCtrl, TRUE);
	    UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_BackLightLvl_PanelCtrl, TRUE);

}

void	FlowWifiMovie_IconHideBackLightLvl_Panel(void)
{
	    UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_BackLightLvl_BarCtrl, FALSE);
	    UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_BackLightLvl_PanelCtrl, FALSE);

}
void	FlowWifiMovie_IconDrawTopIcon(void)
{
//CHKPNT;
	if(UIFlowWndMovie_GetRecLockStatus()){
		UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Panel_TopNormalCtrl,FALSE);
		UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Panel_RecUrgCtrl,TRUE);
	}
	else{
		
		UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Panel_RecUrgCtrl,FALSE);
		
		// AUDIO
		if (UI_GetData(FL_MOVIE_AUDIO ) == MOVIE_AUDIO_ON)
		{
			UxState_SetData(&UIMenuWndWiFiMobileLinkOK_Status_Icon0Ctrl, STATE_CURITEM, UIMenuWndWiFiMobileLinkOK_Status_Icon0_ICON_TOP_AUDIO);
			UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Status_Icon0Ctrl, TRUE);

		}else if ( UI_GetData(FL_MOVIE_AUDIO ) == MOVIE_AUDIO_OFF )
		{
			UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Status_Icon0Ctrl, FALSE);
		}
		
		//WIFI 
		if (UI_GetData(FL_WIFI ) == WIFI_ON)
		{
		///CHKPNT;
			UxState_SetData(&UIMenuWndWiFiMobileLinkOK_Status_Icon1Ctrl, STATE_CURITEM, UIMenuWndWiFiMobileLinkOK_Status_Icon1_ICON_TOP_WIFI);
			UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Status_Icon1Ctrl, TRUE);

		}else if (UI_GetData(FL_WIFI ) == WIFI_OFF)
		{
		//	CHKPNT;
			UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Status_Icon1Ctrl, FALSE);
		}
		
		//PARK 
		if (UI_GetData(FL_MOVIE_PARK) != MOVIE_PARK_OFF)
		{
		  
			UxState_SetData(&UIMenuWndWiFiMobileLinkOK_Status_Icon2Ctrl, STATE_CURITEM, UIMenuWndWiFiMobileLinkOK_Status_Icon2_ICON_TOP_PARK);
			UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Status_Icon2Ctrl, TRUE);
		}else if (UI_GetData(FL_MOVIE_PARK) == MOVIE_PARK_OFF)
		{
			UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Status_Icon2Ctrl, FALSE);
		}

		//后拉显示 和分辨率   
		 if( ( EthCamNet_GetEthLinkStatus(0) == ETHCAM_LINK_UP &&socketCliEthData1_IsRecv(ETHCAM_PATH_ID_1 ) )  && bflag_EthLinkFinish )
		 { 
		 	if ( bflag_EthLinkFinish ) {
				UxState_SetData(&UIMenuWndWiFiMobileLinkOK_StatusTextCtrl, STATE_CURITEM, UIMenuWndWiFiMobileLinkOK_StatusText_STRID_DUAL_1920P30);

				UxState_SetData(& UIMenuWndWiFiMobileLinkOK_Status_Movie_BCtrl, STATE_CURITEM, UIMenuWndWiFiMobileLinkOK_Status_Movie_B_ICON_TOP_BACK);
		 	}
		 }else if(EthCamNet_GetEthLinkStatus(0) == ETHCAM_LINK_DOWN || bflag_EthLinkFinish == FALSE || (!socketCliEthData1_IsRecv(ETHCAM_PATH_ID_1 ) ) )
		 {
		 	if ( bflag_EthLinkFinish == FALSE ) {
		 		
				UxState_SetData(&UIMenuWndWiFiMobileLinkOK_StatusTextCtrl, STATE_CURITEM, UIMenuWndWiFiMobileLinkOK_StatusText_STRID_1920P30);

				UxState_SetData(& UIMenuWndWiFiMobileLinkOK_Status_Movie_BCtrl, STATE_CURITEM, UIMenuWndWiFiMobileLinkOK_Status_Movie_B_ICON_TOP_BACK_OFF);
		 	}
		 }
		 
		UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Panel_TopNormalCtrl,  TRUE);
	}
	
#if 1
	switch (gMovData.State) {
	case MOV_ST_REC:
	case MOV_ST_REC|MOV_ST_ZOOM:
		{
			if (UxState_GetData(&UIMenuWndWiFiMobileLinkOK_Status_RECtrl, STATE_CURITEM) == UIMenuWndWiFiMobileLinkOK_Status_RE_ICON_REC_TRANSPAENT) {
				//CHKPNT;
				UxState_SetData(&UIMenuWndWiFiMobileLinkOK_Status_RECtrl, STATE_CURITEM, UIMenuWndWiFiMobileLinkOK_Status_RE_ICON_REC_ELLIPSE);
			} else {
				//CHKPNT;
				UxState_SetData(&UIMenuWndWiFiMobileLinkOK_Status_RECtrl, STATE_CURITEM, UIMenuWndWiFiMobileLinkOK_Status_RE_ICON_REC_TRANSPAENT);
			}
		}  
	default:
	//	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Status_RECtrl, FALSE);
	break;
	}
#endif 
	if (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE)
	{
		UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Status_RECtrl, FALSE);

	}
}
//#MT CJ 2020/7/6 END
void	FlowWifiMovie_IconHideTopIcon(void)
{
		UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Status_RECtrl,  FALSE);
		UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Panel_TopNormalCtrl,  FALSE);
}

void	FlowWifiMovie_IconHideAlarm(void)
{
		UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Status_Alarm_LCtrl,  FALSE);
		UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Status_Alarm_RCtrl,  FALSE);
 
}
void FlowWifiMovie_IconHideEmr(void)
{
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Panel_EMRBarCtrl,  FALSE);
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_ProgressBarCtrl,  FALSE);
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_EmrStatusTxT_TitleCtrl,  FALSE);
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Static_ENRTimeCtrl,  FALSE);
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Panel_RecUrgCtrl, FALSE);
}

void FlowWifiMovie_IconDrawEmr(void)
{
	if (	UIFlowWndMovie_GetRecLockStatus() ){
		g_WifiEmergencyRecTime ++;
	}
	if (g_WifiEmergencyRecTime <= g_WifiEmergencyRecSetpTotail)
    {
    	// 紧急录像取消标志?
        if (g_WifiEmergencyRecTime > 10)
        {
           // g_CancelEmergency = TRUE;
        }
		g_WifiCurrTime = FlowMovie_GetRecCurrTime();
		memset((void *)g_WifiEMRCurrTimeStr, 0, sizeof(g_WifiEMRCurrTimeStr));
		snprintf(g_WifiEMRCurrTimeStr, 20, "%02d:%02d:%02d", g_WifiCurrTime / 3600, (g_WifiCurrTime % 3600) / 60, (g_WifiCurrTime % 3600) % 60);
	    g_WifiEmergencyRecSetp  = g_WifiCurrTime;// g_EmergencyRecTime;
	    UxProgressBar_SetData(&UIMenuWndWiFiMobileLinkOK_ProgressBarCtrl, PROBAR_TOTSTP, g_WifiEmergencyRecSetpTotail);
	    UxProgressBar_SetData(&UIMenuWndWiFiMobileLinkOK_ProgressBarCtrl, PROBAR_CURSTP, g_WifiEmergencyRecSetp);
		debug_msg("PROBAR_CURSTP: %d\r\n",UxProgressBar_GetData(&UIMenuWndWiFiMobileLinkOK_ProgressBarCtrl, PROBAR_CURSTP) );
		//UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_EmrStatusTxT_TitleCtrl, STATIC_VALUE, Txt_Pointer(g_WifiEMRCurrTimeStr));
		UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_Static_ENRTimeCtrl, STATIC_VALUE, Txt_Pointer(g_WifiEMRCurrTimeStr));

    }else{
		UIFlowWndMovie_SetRecLockStatus(FALSE);
		g_WifiEmergencyRecSetp = 0;
		g_WifiEmergencyRecTime = 0;
	}
 
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Panel_EMRBarCtrl,TRUE);
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_ProgressBarCtrl, TRUE);
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Static_ENRTimeCtrl,TRUE);
} 
void  FlowWifiMovie_IconHideExitWifiMsg(void)
{
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_PanelExitWifiCtrl,FALSE);
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_StatusTxT_TitleCtrl,FALSE);
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Tab_YES_NOCtrl,FALSE);

}
void  FlowWifiMovie_IconDrawExitWifiMsg(void)
{
	if (	UIFlowWndMovie_GetRecLockStatus() == TRUE )
	{CHKPNT;
		UxState_SetItemData(&UIMenuWndWiFiMobileLinkOK_StatusTxT_TitleCtrl,0, STATE_ITEM_STRID, STRID_EXITURG_TXT);
	}else{CHKPNT;
		UxState_SetItemData(&UIMenuWndWiFiMobileLinkOK_StatusTxT_TitleCtrl,0, STATE_ITEM_STRID, STRID_EXITWIFI);

	}
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_PanelExitWifiCtrl,TRUE);
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_StatusTxT_TitleCtrl,TRUE);
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Tab_YES_NOCtrl,TRUE);

}

void Fun_WifiUpdateIcon(BOOL bShow)
{
	if ( bShow )
	{
		FlowWifiMovie_IconDrawDateTime();
		//FlowWifiMovie_IconDrawBackLightLvl_Panel();
		FlowWifiMovie_IconHideBackLightLvl_Panel();
		FlowWifiMovie_IconDrawTopIcon();
	}else{
		FlowWifiMovie_IconHideExitWifiMsg();
		FlowWifiMovie_IconHideEmr();
		FlowWifiMovie_IconHideDateTime();
		FlowWifiMovie_IconHideBackLightLvl_Panel();
		FlowWifiMovie_IconHideTopIcon();
		FlowWifiMovie_IconHideAlarm();
		FlowWifiMovie_IconHideTopIcon();
	}  
}
#endif

//---------------------UIMenuWndWiFiMobileLinkOK_Panel_DatetimeCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiMobileLinkOK_Panel_Datetime)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_TimeHourH)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_TimeHourL)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_TimeMinH)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_TimeMinL)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_Mark)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_DateTxtM)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_DateM)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_DateTxtD)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_DateD)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_Week)

CTRL_LIST_END

//----------------------UIMenuWndWiFiMobileLinkOK_Panel_DatetimeCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Panel_Datetime)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_TimeHourHCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_TimeHourH)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_TimeHourLCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_TimeHourL)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_TimeMinHCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_TimeMinH)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_TimeMinLCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_TimeMinL)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Static_MarkCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_Mark)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Static_DateTxtMCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_DateTxtM)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Static_DateMCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_DateM)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Static_DateTxtDCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_DateTxtD)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Static_DateDCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_DateD)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_WeekCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_Week)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_Alarm_LCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_Alarm_L)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_Alarm_RCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_Alarm_R)
EVENT_END
//----------------------UIMenuWndWiFiMobileLinkOK_Status_RECtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_RE)
EVENT_END
//---------------------UIMenuWndWiFiMobileLinkOK_Panel_TopNormalCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiMobileLinkOK_Panel_TopNormal)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_StatusText)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_Movie_F)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_Movie_B)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_Icon0)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_Icon1)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_Icon2)
CTRL_LIST_END

//----------------------UIMenuWndWiFiMobileLinkOK_Panel_TopNormalCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Panel_TopNormal)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_StatusTextCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_StatusText)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_Movie_FCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_Movie_F)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_Movie_BCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_Movie_B)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_Icon0Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_Icon0)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_Icon1Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_Icon1)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_Icon2Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_Icon2)
EVENT_END


//---------------------UIMenuWndWiFiMobileLinkOK_Panel_OperateCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiMobileLinkOK_Panel_Operate)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_BTN_PIP)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_BTN_BackLightLvl)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_BTN_Setup)
CTRL_LIST_END
//----------------------UIMenuWndWiFiMobileLinkOK_Panel_OperateCtrl Event---------------------------
INT32 UIMenuWndWiFiMobileLinkOK_Panel_Operate_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Panel_Operate)
EVENT_ITEM(NVTEVT_CLICK,UIMenuWndWiFiMobileLinkOK_Panel_Operate_OnTouchPanelClick)
EVENT_END

INT32 UIMenuWndWiFiMobileLinkOK_Panel_Operate_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLICK,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndWiFiMobileLinkOK_BTN_PIPCtrl Event---------------------------
INT32 UIMenuWndWiFiMobileLinkOK_BTN_PIP_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_BTN_PIP_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_BTN_PIP)
EVENT_ITEM(NVTEVT_CLICK,UIMenuWndWiFiMobileLinkOK_BTN_PIP_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_USER_RELEASE,UIMenuWndWiFiMobileLinkOK_BTN_PIP_OnTouchPanelRelease)

EVENT_END
INT32 UIMenuWndWiFiMobileLinkOK_BTN_PIP_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
debug_msg("EthCamNet_GetEthLinkStatus: %d \r\n",EthCamNet_GetEthLinkStatus(0));
	if(!bFocusBackLightAdj) {
		if(EthCamNet_GetEthLinkStatus(0) == ETHCAM_LINK_UP) {
			if(SysGetFlag(FL_DUAL_CAM) == DUALCAM_FRONT  ) {
				CHKPNT;
				SysSetFlag(FL_DUAL_CAM,DUALCAM_BEHIND);
				
			}else {
			
				SysSetFlag(FL_DUAL_CAM,DUALCAM_FRONT);
			}
		}else{
			Ux_OpenWindow(&UIFlowWndWaitMomentCtrl, 1, UIFlowWndWaitMoment_StatusTXT_Msg_STRID_ETHCAM_DETFAIL);
			
		}
	}
  //      Ux_PostEvent(NVTEVT_KEY_SELECT, 1, NVTEVT_KEY_PRESS);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_BTN_PIP_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	      UxButton_SetItemData(&UIMenuWndWiFiMobileLinkOK_BTN_PIPCtrl, 0, BTNITM_ICONID, ICON_OPERATE_PIP);

	return NVTEVT_CONSUME;
}
//----------------------UIMenuWndWiFiMobileLinkOK_BTN_BackLightLvlCtrl Event---------------------------
INT32 UIMenuWndWiFiMobileLinkOK_BTN_BackLightLvl_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_BTN_BackLightLvl_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_BTN_BackLightLvl)

EVENT_ITEM(NVTEVT_CLICK,UIMenuWndWiFiMobileLinkOK_BTN_BackLightLvl_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_USER_RELEASE,UIMenuWndWiFiMobileLinkOK_BTN_BackLightLvl_OnTouchPanelRelease)

EVENT_END

INT32 UIMenuWndWiFiMobileLinkOK_BTN_BackLightLvl_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	    if(!UxCtrl_IsShow(&UIMenuWndWiFiMobileLinkOK_BackLightLvl_PanelCtrl))
    {
    	
	   CHKPNT;
   //      FlowMovie_DrawBrightnessBar(TRUE);
   FlowWifiMovie_IconDrawBackLightLvl_Panel();
      UxProgressBar_SetData(&UIMenuWndWiFiMobileLinkOK_BackLightLvl_BarCtrl,PROBAR_CURSTP, SysGetFlag(FL_LCD_BRIGHTNESS) ); //iCur_BL_Value_Bar
	
		 	
         //UIFlowWndMovie_SetBriAdjBarShowTime(LCD_BRI_LVL_DISP_TIME);
         //UI_SetTouchEventMask(NVTEVT_USER_SLIDE_LEFT);
         //UI_SetTouchEventMask(NVTEVT_USER_SLIDE_RIGHT);
		 
		 //UI_SetTouchEventMask(NVTEVT_USER_SLIDE_UP);
		 //UI_SetTouchEventMask(NVTEVT_USER_SLIDE_DOWN);
    }else
	{
	 
		//FlowMovie_DrawBrightnessBar(FALSE);  
		FlowWifiMovie_IconHideBackLightLvl_Panel();
		//UIFlowWndMovie_SetBriAdjBarShowTime(LCD_BRI_LVL_DISP_TIME);
		//UI_CancelTouchEventMask(NVTEVT_USER_SLIDE_LEFT);
		//UI_CancelTouchEventMask(NVTEVT_USER_SLIDE_RIGHT);
		//UI_CancelTouchEventMask(NVTEVT_USER_SLIDE_UP);
		//UI_CancelTouchEventMask(NVTEVT_USER_SLIDE_DOWN);
		CHKPNT;
		//Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_SETLCDBRIGHTLVL, 1, SysGetFlag(FL_LCD_BRIGHTNESS));

	}
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_BTN_BackLightLvl_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxButton_SetItemData(&UIMenuWndWiFiMobileLinkOK_BTN_BackLightLvlCtrl, 0, BTNITM_ICONID,ICON_OPERATE_BL );

    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndWiFiMobileLinkOK_BTN_SetupCtrl Event---------------------------
INT32 UIMenuWndWiFiMobileLinkOK_BTN_Setup_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_BTN_Setup_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_BTN_Setup)
EVENT_ITEM(NVTEVT_CLICK,UIMenuWndWiFiMobileLinkOK_BTN_Setup_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_USER_RELEASE,UIMenuWndWiFiMobileLinkOK_BTN_Setup_OnTouchPanelRelease)

EVENT_END



INT32 UIMenuWndWiFiMobileLinkOK_BTN_Setup_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	switch (gMovData.State) {
		case MOV_ST_VIEW:
			break;
		case MOV_ST_REC:
			
			Ux_PostEvent(NVTEVT_KEY_SHUTTER2, 1, NVTEVT_KEY_PRESS);
			break;
		default:
			break;
		}

	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_PanelExitWifiCtrl, TRUE);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_BTN_Setup_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	        UxButton_SetItemData(&UIMenuWndWiFiMobileLinkOK_BTN_SetupCtrl, 0, BTNITM_ICONID,ICON_OPERATE_SETUP_F );

    return NVTEVT_CONSUME;
}

//----------------------UIMenuWndWiFiMobileLinkOKCtrl Event---------------------------
INT32 UIMenuWndWiFiMobileLinkOK_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_Authorized_OK(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_DHCP_REQ(VControl *, UINT32, UINT32 *);

INT32 UIMenuWndWiFiModuleLinkOK_OnStorageInit(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiModuleLinkOK_OnStorageChange(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnBackgroundDone(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieFull(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieWrError(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnStorageSlow(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieOneSec(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncJpgOKCB(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnBatteryLow(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnDeAuthenticated(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieVedioReady(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeChangeModeDone(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnTimer(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnCustom1(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnTouchSlideUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnTouchSlideDown(VControl *, UINT32, UINT32 *);

INT32 UIMenuWndWiFiMobileLinkOK_OnTouchSlideLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnTouchSlideRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnTouchMove(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnTouchRelease(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnLCA_Alarm(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnTouchPanelClick(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK)
EVENT_ITEM(NVTEVT_OPEN_WINDOW, UIMenuWndWiFiMobileLinkOK_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW, UIMenuWndWiFiMobileLinkOK_OnClose)
EVENT_ITEM(NVTEVT_WIFI_AUTHORIZED_OK, UIMenuWndWiFiMobileLinkOK_Authorized_OK)
EVENT_ITEM(NVTEVT_WIFI_DHCP_REQ, UIMenuWndWiFiMobileLinkOK_DHCP_REQ)

EVENT_ITEM(NVTEVT_STORAGE_INIT, UIMenuWndWiFiModuleLinkOK_OnStorageInit)
EVENT_ITEM(NVTEVT_STORAGE_CHANGE, UIMenuWndWiFiModuleLinkOK_OnStorageChange)
EVENT_ITEM(NVTEVT_BACKGROUND_DONE, UIMenuWndWiFiMobileLinkOK_OnBackgroundDone)
EVENT_ITEM(NVTEVT_CB_MOVIE_OVERTIME, UIMenuWndWiFiMobileLinkOK_OnMovieFull) // the same handling as storage full (may need to show special message)
EVENT_ITEM(NVTEVT_CB_MOVIE_FULL, UIMenuWndWiFiMobileLinkOK_OnMovieFull)
EVENT_ITEM(NVTEVT_CB_MOVIE_LOOPREC_FULL, UIMenuWndWiFiMobileLinkOK_OnMovieFull)
EVENT_ITEM(NVTEVT_CB_MOVIE_WR_ERROR, UIMenuWndWiFiMobileLinkOK_OnMovieWrError)
EVENT_ITEM(NVTEVT_CB_MOVIE_SLOW, UIMenuWndWiFiMobileLinkOK_OnStorageSlow)
EVENT_ITEM(NVTEVT_CB_MOVIE_REC_ONE_SEC, UIMenuWndWiFiMobileLinkOK_OnMovieOneSec)
EVENT_ITEM(NVTEVT_CB_RAWENC_OK, UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncJpgOKCB)
EVENT_ITEM(NVTEVT_CB_RAWENC_ERR, UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr)
EVENT_ITEM(NVTEVT_CB_RAWENC_WRITE_ERR, UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr)
EVENT_ITEM(NVTEVT_CB_RAWENC_DCF_FULL, UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr)
EVENT_ITEM(NVTEVT_BATTERY_LOW, UIMenuWndWiFiMobileLinkOK_OnBatteryLow)
EVENT_ITEM(NVTEVT_WIFI_DEAUTHENTICATED, UIMenuWndWiFiMobileLinkOK_OnDeAuthenticated)
EVENT_ITEM(NVTEVT_CB_MOVIE_VEDIO_READY, UIMenuWndWiFiMobileLinkOK_OnExeMovieVedioReady)
EVENT_ITEM(NVTEVT_TIMER, UIMenuWndWiFiMobileLinkOK_OnTimer)
EVENT_ITEM(NVTEVT_KEY_CUSTOM1, UIMenuWndWiFiMobileLinkOK_OnCustom1)

//#MT#CJ -20200706-begin

EVENT_ITEM(NVTEVT_USER_SLIDE_LEFT, UIMenuWndWiFiMobileLinkOK_OnTouchSlideLeft)
EVENT_ITEM(NVTEVT_USER_SLIDE_RIGHT,UIMenuWndWiFiMobileLinkOK_OnTouchSlideRight)
//EVENT_ITEM(NVTEVT_USER_SLIDE_UP, UIMenuWndWiFiMobileLinkOK_OnTouchSlideUp)
//EVENT_ITEM(NVTEVT_USER_SLIDE_DOWN, UIMenuWndWiFiMobileLinkOK_OnTouchSlideDown)
EVENT_ITEM(NVTEVT_USER_MOVE , UIMenuWndWiFiMobileLinkOK_OnTouchMove) // NVTEVT_USER_MOVE
EVENT_ITEM(NVTEVT_USER_RELEASE, UIMenuWndWiFiMobileLinkOK_OnTouchRelease)
EVENT_ITEM(NVTEVT_CLICK, UIMenuWndWiFiMobileLinkOK_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_USER_LCA_RESULT, UIMenuWndWiFiMobileLinkOK_OnLCA_Alarm)
//#MT#CJ -20200706 -end

EVENT_END

extern char gLastMacAddr[];
#define wifiMOVIE_KEY_PRESS_MASK        (FLGKEY_SHUTTER2|FLGKEY_RIGHT|FLGKEY_LEFT|FLGKEY_CUSTOM1|FLGKEY_UP|FLGKEY_DOWN)
#define wifiMOVIE_KEY_RELEASE_MASK      (FLGKEY_SHUTTER2|FLGKEY_RIGHT|FLGKEY_LEFT|FLGKEY_CUSTOM1|FLGKEY_UP|FLGKEY_DOWN)
static UINT32  g_uiMaskKeyPress      = wifiMOVIE_KEY_PRESS_MASK;
static UINT32  g_uiMaskKeyRelease    = wifiMOVIE_KEY_RELEASE_MASK;
void Fun_CloseWifiTimer(void);
void Fun_CloseWifiTimer(void)
{
	if (gUIMenuWndWiFiTimerID != NULL_TIMER) {
		GxTimer_StopTimer(&gUIMenuWndWiFiTimerID);
	}
	CHKPNT;
	if (g_UILCAAlarmTimerID != NULL_TIMER) {
		 GxTimer_StopTimer(&g_UILCAAlarmTimerID);
	}
	CHKPNT;
	WiFiCmd_HBStop();
	WiFiCmd_MotionDetectStop();

}

INT32 UIMenuWndWiFiMobileLinkOK_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
CHKPNT;       
	static char Buf1[32] = {0};//, buf2[32] = {0} ;
#if 0
	Ux_FlushEventByRange(NVTEVT_KEY_EVT_START, NVTEVT_KEY_EVT_END);
	Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
	Input_SetKeyMask(KEY_RELEASE, 0);
	Input_SetKeyMask(KEY_CONTINUE, 0);
	#else
	Ux_FlushEventByRange(NVTEVT_KEY_EVT_START, NVTEVT_KEY_EVT_END);
	/* Init window key mask variables & set key and key released mask */
	g_uiMaskKeyPress = wifiMOVIE_KEY_PRESS_MASK;
	g_uiMaskKeyRelease = wifiMOVIE_KEY_RELEASE_MASK;
	Input_SetKeyMask(KEY_PRESS, g_uiMaskKeyPress);
	Input_SetKeyMask(KEY_RELEASE, g_uiMaskKeyPress);
	Input_SetKeyMask(KEY_CONTINUE, g_uiMaskKeyPress);
	#endif
//#NT#2016/05/31#Ben Wang -begin
//#NT#Add UVC multimedia function.
#if(UVC_MULTIMEDIA_FUNC == ENABLE)
	if (System_GetState(SYS_STATE_CURRSUBMODE) == SYS_SUBMODE_UVC) {
		if (ImageUnit_GetParam(&ISF_UsbUVAC, ISF_CTRL, UVAC_PARAM_CDC_ENABLE)) {
			MEM_RANGE WorkBuf;
			WorkBuf.Addr = OS_GetMempoolAddr(POOL_ID_USBCMD);
			WorkBuf.Size = POOL_SIZE_USBCMD;
			UsbCmd_Open(&WorkBuf);
		}
		snprintf(Buf1, sizeof(Buf1), "UVC Connected");
		//just don't show this string
		StringTmpBuf[0] = 0;
	} else
#endif
	{
#if !defined(_NVT_SDIO_WIFI_NONE_) || !defined(_NVT_USB_WIFI_NONE_)
		snprintf(Buf1, sizeof(Buf1), "WiFi Connected");
		snprintf(StringTmpBuf, sizeof(StringTmpBuf), " MAC : %s", UINet_GetConnectedMAC());
#else
		snprintf(Buf1, sizeof(Buf1), "Ethernet Connected");
		snprintf(StringTmpBuf, sizeof(StringTmpBuf), " IP : %s", UINet_GetIP());
#endif
	}
//#MT CJ 20200706 --BEGIN
	if (gUIMenuWndWiFiTimerID == NULL_TIMER) {
		gUIMenuWndWiFiTimerID = GxTimer_StartTimer(1000, NVTEVT_WIFI_UI_TIMER, CONTINUE);
	}
	if (g_UILCAAlarmTimerID == NULL_TIMER) {
		g_UILCAAlarmTimerID = GxTimer_StartTimer(200, NVTEVT_LCA_ALARM_TIMER, CONTINUE);
	}
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_PlaybackModePanelCtrl,FALSE);
  
	Fun_WifiUpdateIcon(FALSE);
	//#MT CJ 20200706 -END
//#NT#2016/05/31#Ben Wang -end
/*
	UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_LinkStsCtrl, STATIC_VALUE, Txt_Pointer(Buf1));
	UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl, STATIC_VALUE, Txt_Pointer(StringTmpBuf));

	snprintf(buf2, sizeof(buf2), "Press Select to Disconnect");
	UxButton_SetItemData(&UIMenuWndWiFiMobileLinkOK_Button_DisconnectCtrl, 0, BTNITM_STRID, Txt_Pointer(buf2));
	//*/

//#NT#2016/05/31#Ben Wang -begin
//#NT#Add UVC multimedia function.
#if(UVC_MULTIMEDIA_FUNC == ENABLE)
	if (System_GetState(SYS_STATE_CURRSUBMODE) != SYS_SUBMODE_UVC)
#endif
	{
		//make sure, connec to RTSP mode
		//if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE) {
		//	Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);
		//}
	}   
//#NT#2016/05/31#Ben Wang -end
//#NT#2016/03/23#Isiah Chang -begin
//#NT#add new Wi-Fi UI flow.
#if(WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0)
	WiFiCmd_HBStart();
#endif
//#NT#2016/03/23#Isiah Chang -end
	WiFiCmd_MotionDetectStart();
    UxState_SetData(&UIMenuWndWiFiMobileLinkOK_Status_RECtrl, STATE_CURITEM, UIMenuWndWiFiMobileLinkOK_Status_RE_ICON_REC_TRANSPAENT);
	UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Status_RECtrl,  TRUE);

	Ux_DefaultEvent(pCtrl, NVTEVT_OPEN_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{  
	if (UI_GetData(FL_MOVIE_SIZE_MENU) != UI_GetData(FL_MOVIE_SIZE)) {
		Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIESIZE, 1, UI_GetData(FL_MOVIE_SIZE_MENU));
	}
//#NT#2016/03/23#Isiah Chang -begin
//#NT#add new Wi-Fi UI flow.
#if (WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0)
	WiFiCmd_HBStop();
#endif
//#NT#2016/03/23#Isiah Chang -end
	WiFiCmd_MotionDetectStop();
  
//#NT#2016/05/31#Ben Wang -begin
//#NT#Add UVC multimedia function.
#if(UVC_MULTIMEDIA_FUNC == ENABLE)
	//if(System_GetState(SYS_STATE_CURRSUBMODE)==SYS_SUBMODE_UVC && System_GetState(SYS_STATE_NEXTSUBMODE)!=SYS_SUBMODE_UVC)
	if (System_GetState(SYS_STATE_CURRSUBMODE) == SYS_SUBMODE_UVC) {
		if (ImageUnit_GetParam(&ISF_UsbUVAC, ISF_CTRL, UVAC_PARAM_CDC_ENABLE)) {
			UsbCmd_Close();
		}
	}
#endif
//#NT#2016/05/31#Ben Wang -end
	//#NT#2019/10/30#Philex Lin - begin
	// stop re-connect timer in station mode
	//if (UI_GetData(FL_NetWorkMode) == NET_STATION_MODE)
//	    UINet_CliReConnect(0);
	//#NT#2019/10/30#Philex Lin - end

//UIFlowWndMovie_SetBriAdjBarShowTime(-1);
		UI_CancelTouchEventMask(NVTEVT_USER_SLIDE_LEFT);
		UI_CancelTouchEventMask(NVTEVT_USER_SLIDE_RIGHT);
		
	Ux_DefaultEvent(pCtrl, NVTEVT_CLOSE_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_Authorized_OK(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 bNewUser = 0 ;
	if (paramNum) {
		bNewUser = paramArray[0];
	}
#if 0  //print MAC when client get IP
	snprintf(StringTmpBuf, sizeof(StringTmpBuf), " MAC : %s", UINet_GetConnectedMAC());
	UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl, STATIC_VALUE, Txt_Pointer(StringTmpBuf));
#endif
	if (bNewUser) {
		//delay 500 ms,disconnect last user and
		//in window,use GxTimer replace Timer Delay,it would occupat UI task
		GxTimer_StartTimer(TIMER_HALF_SEC, NVTEVT_DISCONNECT_LAST_TIMER, ONE_SHOT);
	}

#if 0 // Moved to UINet_DhcpSrvCBCliConn.
	//make sure, connec to RTSP mode
	if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE) {
		Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);
	}
#endif

	return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_DHCP_REQ(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	char *pMAC = 0;
	if (paramNum) {
		pMAC = (char *)paramArray[0];
	}
	//#NT#2016/12/27#YongChang Qui -begin
	//#NT#don't display mac address on UI if mac is 0:0:0:0:0:0:0
	if (pMAC && (pMAC[0] || pMAC[1] || pMAC[2] || pMAC[3] || pMAC[4] || pMAC[5]))
		//#NT#2016/12/27#YongChang Qui -end
	{
		snprintf(StringTmpBuf, sizeof(StringTmpBuf), " MAC : %02x%02x%02x%02x%02x%02x", pMAC[0], pMAC[1], pMAC[2]\
				 , pMAC[3], pMAC[4], pMAC[5]);
	//	UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl, STATIC_VALUE, Txt_Pointer(StringTmpBuf));
	}
	return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiModuleLinkOK_OnStorageInit(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if (SDHOTPLUG_FUNCTION == ENABLE)
	if (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE) {
		UIMenuWndWiFiMobileLinkOKTraceMsg("card err,removed\r\n");
	} else {
		UIMenuWndWiFiMobileLinkOKTraceMsg("card insert\r\n");
		if (System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_PLAYBACK) {
			Ux_SendEvent(0, NVTEVT_SYSTEM_MODE, 1, System_GetState(SYS_STATE_CURRMODE));
		} else {
			ImageUnit_SetParam(&ISF_CamFile, CAMFILE_PARAM_FILEDB_REOPEN, 0);
		}
		WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_CARD_INSERT);
	}
#endif
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiModuleLinkOK_OnStorageChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if (SDHOTPLUG_FUNCTION == ENABLE)
	UIMenuWndWiFiMobileLinkOKTraceMsg("card removed\r\n");
	if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_PLAYBACK) {
		ImageUnit_SetParam(&ISF_CamFile, CAMFILE_PARAM_FILEDB_CLOSE, 0);
	}
	WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_CARD_REMOVE);
#endif
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnBackgroundDone(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	NVTEVT event;
	UINT32 status;

	event = paramArray[ONDONE_PARAM_INDEX_CMD];
	status = paramArray[ONDONE_PARAM_INDEX_RET];
	debug_err(("%s event = 0x%x, status=%d\r\n", __FUNCTION__, event, status));

	switch (event) {
	case NVTEVT_BKW_FORMAT_CARD: {
			WifiCmd_Done(WIFIFLAG_FORMAT_DONE, WIFIAPP_RET_OK);
			//Rsvd
			break;
		}

	case NVTEVT_BKW_FORMAT_NAND: {
			WifiCmd_Done(WIFIFLAG_FORMAT_DONE, WIFIAPP_RET_OK);
			//Rsvd
			break;
		}

	case NVTEVT_BKW_FW_UPDATE: {
			if (status) {
				debug_err(("%s:update FW fail %d\r\n", __FUNCTION__, status));
				WifiCmd_Done(WIFIFLAG_UPDATE_DONE, status + WIFIAPP_RET_FW_OFFSET);
			} else {
				//#NT#2016/03/23#Isiah Chang -begin
				//#NT#add new Wi-Fi UI flow.
				INT32 ret;

				WifiCmd_Done(WIFIFLAG_UPDATE_DONE, WIFIAPP_RET_OK);

				ret = FileSys_DeleteFile(FW_UPDATE_NAME);
				if (ret != FST_STA_OK) {
					debug_err(("%s:delete FW fail %d\r\n", __FUNCTION__, status));
				}
				//#NT#2016/03/23#Isiah Chang -end
				Delay_DelayMs(2000);
				// Should power off immediatelly
				System_PowerOff(SYS_POWEROFF_NORMAL);
			}
			break;
		}
	case NVTEVT_BKW_TRIGGER_THUMB:
	case NVTEVT_BKW_ETHCAM_RAW_ENCODE_RESULT:
		break;

	default:
		debug_err(("%s:Unknown event 0x%x\r\n", __FUNCTION__, event));
		break;
	}
	return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnMovieFull(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//snprintf(StringTmpBuf,sizeof(StringTmpBuf),"Card Full");
	//UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl,STATIC_VALUE,Txt_Pointer(StringTmpBuf));
	return WiFiCmd_OnMovieFull(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieWrError(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//snprintf(StringTmpBuf,sizeof(StringTmpBuf),"Card Error");
	//UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl,STATIC_VALUE,Txt_Pointer(StringTmpBuf));

	return WiFiCmd_OnMovieWrError(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnStorageSlow(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	CHKPNT;
	//snprintf(StringTmpBuf,sizeof(StringTmpBuf),"Slow Card");
	//UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl,STATIC_VALUE,Txt_Pointer(StringTmpBuf));

	return WiFiCmd_OnStorageSlow(pCtrl, paramNum, paramArray);
}
void Fun_UpdateWifiRecIcon(void);
void Fun_UpdateWifiRecIcon(void)
{
	switch (gMovData.State) {
	case MOV_ST_REC:
	case MOV_ST_REC|MOV_ST_ZOOM:

		if (UxState_GetData(&UIMenuWndWiFiMobileLinkOK_Status_RECtrl, STATE_CURITEM) == UIMenuWndWiFiMobileLinkOK_Status_RE_ICON_REC_TRANSPAENT) {
				UxState_SetData(&UIMenuWndWiFiMobileLinkOK_Status_RECtrl, STATE_CURITEM, UIMenuWndWiFiMobileLinkOK_Status_RE_ICON_REC_ELLIPSE);
		} else {
					UxState_SetData(&UIMenuWndWiFiMobileLinkOK_Status_RECtrl, STATE_CURITEM, UIMenuWndWiFiMobileLinkOK_Status_RE_ICON_REC_TRANSPAENT);
		}

		if ( gMovData.State == MOV_ST_REC )
					{
						UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Status_RECtrl,  TRUE);

					}else  {
						UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_Status_RECtrl, FALSE);

					}
					
	}
}

INT32 UIMenuWndWiFiMobileLinkOK_OnMovieOneSec(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	
	return WiFiCmd_OnMovieOneSec(pCtrl, paramNum, paramArray);
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncJpgOKCB(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return WiFiCmd_OnMovieRawEncJpgOKCB(pCtrl, paramNum, paramArray);
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return WiFiCmd_OnMovieRawEncErr(pCtrl, paramNum, paramArray);
}

INT32 UIMenuWndWiFiMobileLinkOK_OnBatteryLow(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UIMenuWndWiFiMobileLinkOKTraceMsg("%s \r\n", __FUNCTION__);

	//snprintf(StringTmpBuf,sizeof(StringTmpBuf),"Battery Low");
	//UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl,STATIC_VALUE,Txt_Pointer(StringTmpBuf));

	WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_BATTERY_LOW);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnDeAuthenticated(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
//#NT#2016/03/23#Isiah Chang -begin
//#NT#add new Wi-Fi UI flow.
#if (WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0)
	Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE), SYS_SUBMODE_NORMAL);
#else
	snprintf(StringTmpBuf, sizeof(StringTmpBuf), "No connect");
	//UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl, STATIC_VALUE, Txt_Pointer(StringTmpBuf));
#if !defined(_NVT_SDIO_WIFI_NONE_) || !defined(_NVT_USB_WIFI_NONE_)
	UINet_CliReConnect(1);
#endif
#endif
//#NT#2016/03/23#Isiah Chang -end
	return NVTEVT_CONSUME;

	//Ux_CloseWindow(pCtrl,0);

	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieVedioReady(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return WiFiCmd_OnExeMovieVedioReady(pCtrl, paramNum, paramArray);
}

#define DisplayWifiExitTime  10
INT32 UIMenuWndWiFiMobileLinkOK_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32  uiEvent;
	uiEvent = paramNum ? paramArray[0] : 0;
	static UINT16 Postcardslowevent_cnt = 0;
	switch (uiEvent) {
		//#MT CJ 2020 0706
		case NVTEVT_IGNORE_SLIDE_TOUCH_TIMER:
			bFocusBackLightAdj = FALSE;
            		GxTimer_StopTimer(&uiIgnoreTimerID);
			break;
		//#MT CJ 2020 0706
	case NVTEVT_DISCONNECT_LAST_TIMER:
		UINet_AddACLTable();
		break;
	//	return NVTEVT_CONSUME;
	case NVTEVT_DELAY_CLOSE_TIMER: {
			//#NT#2016/03/08#Niven Cho -begin
			//#NT#because it is long time closing the linux-wifi, we don't change mode to movie video ahead.
			//#NT#use Ux_SendEvent(0,NVTEVT_EXE_WIFI_STOP, 0),not post event
#if (WIFI_FUNC == ENABLE)
				INT32 curMode = System_GetState(SYS_STATE_CURRMODE);
				if ( curMode!= PRIMARY_MODE_MOVIE) {
			    	Ux_SendEvent(0,NVTEVT_EXE_WIFI_STOP, 0);
					Ux_CloseWindow(&UIFlowWndMovieCtrl,0);
			    	Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, curMode,SYS_SUBMODE_NORMAL);
				} else {
					VControl *pWnd =0 ;
					Ux_GetWindowByIndex(&pWnd, 1);

					Ux_SendEvent(0,NVTEVT_EXE_WIFI_STOP, 0);
					System_ChangeSubMode(SYS_SUBMODE_NORMAL);
					Ux_CloseWindow(pWnd, 0);
				}
#endif
			//#NT#2016/03/08#Niven Cho -end
			break;
			//return NVTEVT_CONSUME;
		}

//#NT#2017/01/03#Isiah Chang -begin
//#NT#Add WiFiCmd Bitrate control.
#if(WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0)
	case NVTEVT_1SEC_TIMER: 
			WiFiCmd_HBOneSec();
			//cj add 0703 begin
			
			//Fun_UpdateWifiRecIcon();
			//cj add 0703 end
			
			//return NVTEVT_CONSUME;
		break;
	case NVTEVT_WIFI_UI_TIMER:
		if(Postcardslowevent_cnt == 20)
		{
			Ux_PostEvent(WIFIAPP_CMD_THUMB, 0);
			Postcardslowevent_cnt = 22;
		}
		else
			Postcardslowevent_cnt++;
	
		Fun_WifiUpdateIcon(TRUE);
		if ( bDisplayWifiExit )
		{
			WifiExitCount ++;
			if ( WifiExitCount == DisplayWifiExitTime)
			{
      			FlowWifiMovie_IconHideExitWifiMsg();
			}
		}else{
			bDisplayWifiExit = FALSE;
			WifiExitCount =0;
		}
		if ( UIFlowWndMovie_GetRecLockStatus())
		{
			FlowWifiMovie_IconDrawEmr();	
		}else{
			FlowWifiMovie_IconHideEmr();
		}
		break;
#endif
//#NT#2017/01/03#Isiah Chang -end
	case NVTEVT_05SEC_TIMER: 
			WiFiCmd_OnMotionDetect();
			//return NVTEVT_CONSUME;
		
	break;
	default:
		break;
		return NVTEVT_CONSUME;
	}
	return NVTEVT_CONSUME;
}
extern void UIFlowWndMovie_SetRecLockStatus(BOOL bSet);
extern BOOL UIFlowWndMovie_GetRecLockStatus(void);
extern ISF_RV ImageApp_MovieMulti_SetCrash(MOVIE_CFG_REC_ID rec_id, UINT32 is_set);
extern MOVIE_RECODE_FILE_OPTION gMovie_Rec_Option;

INT32 UIMenuWndWiFiMobileLinkOK_OnCustom1(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
CHKPNT;
debug_msg("--WiFiMobileLinkOK_OnCustom1%d %d  %d\r\n ",gMovData.State, SysGetFlag(FL_MOVIE_URGENT_PROTECT_AUTO),UIFlowWndMovie_GetRecLockStatus());
	{
		if ((gMovData.State == MOV_ST_REC) || (gMovData.State == MOV_ST_REC_WAIT)) {
			if (SysGetFlag(FL_MOVIE_URGENT_PROTECT_AUTO) == MOVIE_URGENT_PROTECT_AUTO_ON) {
				
				if (UIFlowWndMovie_GetRecLockStatus() == FALSE)
				{
					UINT32 i, mask, movie_rec_mask;
					ISF_RV rt;
					debug_msg("--WiFiMobileLinkOK_OnCustom1%d %d  \r\n ",Movie_GetMovieRecMask(), 
					SENSOR_CAPS_COUNT);

 					movie_rec_mask = Movie_GetMovieRecMask();
					mask = 1;
					for (i = 0; i < SENSOR_CAPS_COUNT; i++) {
						if (movie_rec_mask & mask) {
							CHKPNT;
							ImageApp_MovieMulti_SetCrash(_CFG_REC_ID_1 + i, TRUE);
						}
						mask <<= 1;
					}
					#if (defined(_NVT_ETHREARCAM_RX_))
						for(i = 0;i<ETH_REARCAM_CAPS_COUNT;i++)
						{
							CHKPNT;
							ImageApp_MovieMulti_SetCrash(_CFG_ETHCAM_ID_1 + i,TRUE);
						}	
					#endif
					if (rt < 0)
                    {
                        debug_msg("\r\n  ---------%d SetCrash Error !!!--------- \r\n",rt);
                    }else{
						UIFlowWndMovie_SetRecLockStatus(TRUE);
						#if 1
							UIFlowWndMovie_SetRecLockStatus(TRUE);
							if ( FlowMovie_GetRecCurrTime() > 50)
							{    
								 g_WifiEmergencyRecSetpTotail =gMovie_Rec_Option.seamless_sec ;// (gMovie_Rec_Option.seamless_sec  - FlowMovie_GetRecCurrTime()) + gMovie_Rec_Option.seamless_sec +1;//(60 - FlowMovie_GetRecCurrTime()) + 61;
							}else{
								g_WifiEmergencyRecSetpTotail = gMovie_Rec_Option.seamless_sec ;//61;
							}
							g_WifiEmergencyRecSetp = 0;
		                    g_WifiEmergencyRecTime = 0;	
							FlowWifiMovie_IconDrawEmr();			
						#endif
		            }
				}else{
					debug_msg("has locked \r\n");
				}
			}
		}
	}
	return NVTEVT_CONSUME;
}
//#MT CJ# 20200706 --begin

INT32 UIMenuWndWiFiMobileLinkOK_OnTouchSlideLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
CHKPNT;
debug_msg("bFocusBackLightAdj:%d\r\n",bFocusBackLightAdj);
#if IMG_FULL_DISP

	extern UINT32 g_PipViewStyle;
DBGD(g_PipViewStyle);
#endif
	//extern UINT32 g_PipViewStyle;
	if(!bFocusBackLightAdj)
	{
    //	DBGD(g_PipViewStyle);
    	DBGD(SysGetFlag(FL_DUAL_CAM));
    	if(SysGetFlag(FL_DUAL_CAM) == DUALCAM_BEHIND)
    	{
        SysSetFlag(FL_DUAL_CAM_MENU, DUALCAM_FRONT);
        SysSetFlag(FL_DUAL_CAM, DUALCAM_FRONT);
    	}
    	else
    	{
        SysSetFlag(FL_DUAL_CAM_MENU, DUALCAM_BEHIND);
        SysSetFlag(FL_DUAL_CAM, DUALCAM_BEHIND);
    	}
	}
	return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnTouchSlideRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
CHKPNT;
debug_msg("bFocusBackLightAdj:%d\r\n",bFocusBackLightAdj);
#if IMG_FULL_DISP

	extern UINT32 g_PipViewStyle;
DBGD(g_PipViewStyle);
#endif
//	extern UINT32 g_PipViewStyle;	
	if(!bFocusBackLightAdj)
	{
    //	DBGD(g_PipViewStyle);
    	DBGD(SysGetFlag(FL_DUAL_CAM));
    	if(SysGetFlag(FL_DUAL_CAM) == DUALCAM_BEHIND)
    	{
        SysSetFlag(FL_DUAL_CAM_MENU, DUALCAM_FRONT);
        SysSetFlag(FL_DUAL_CAM, DUALCAM_FRONT);
    	}
    	else
    	{
        SysSetFlag(FL_DUAL_CAM_MENU, DUALCAM_BEHIND);
        SysSetFlag(FL_DUAL_CAM, DUALCAM_BEHIND);
    	}
	}
	return NVTEVT_CONSUME;

}
extern void MovieExe_SetIMECrop(UINT32 rec_id);
INT32 UIMenuWndWiFiMobileLinkOK_OnTouchSlideUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
CHKPNT;
#if IMG_FULL_DISP

	extern UINT32 g_PipViewStyle;
DBGD(g_PipViewStyle);
#endif
	//extern UINT32 g_PipViewStyle;
	UINT32 curDispOffset = 0;
		debug_msg("--OnTouchSlideUp RXcj FL_DUAL_CAM:%d \r\n",UI_GetData(FL_DUAL_CAM));

	if(!bFocusBackLightAdj)
	{
    	if(SysGetFlag(FL_DUAL_CAM) == DUALCAM_FRONT)
    	{
            curDispOffset = SysGetFlag(FL_SENSOR1_DISP_OFFSET);
            if(curDispOffset < (SEN_DISP_OFFSET_SETTING_MAX - 1))
              curDispOffset ++;
            SysSetFlag(FL_SENSOR1_DISP_OFFSET, curDispOffset);
            
            #if IMG_FULL_DISP
            MovieExe_SetIMECrop(_CFG_REC_ID_1);
            #endif  
    	}
    	else
    	{
			curDispOffset = SysGetFlag(FL_SENSOR2_DISP_OFFSET);
			if(curDispOffset < (SEN_DISP_OFFSET_SETTING_MAX - 1))
			  curDispOffset ++;
			SysSetFlag(FL_SENSOR2_DISP_OFFSET, curDispOffset);
            #if IMG_FULL_DISP
  			MovieExe_SetIMECrop(_CFG_REC_ID_2);
            #endif	


    	}
	}
		


	return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnTouchSlideDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if IMG_FULL_DISP

	extern UINT32 g_PipViewStyle;
DBGD(g_PipViewStyle);
#endif
//	extern UINT32 g_PipViewStyle;
	UINT32 curDispOffset = 0;
	if(!bFocusBackLightAdj)
	{
    	if(SysGetFlag(FL_DUAL_CAM) == DUALCAM_FRONT)
    	{
            curDispOffset = SysGetFlag(FL_SENSOR1_DISP_OFFSET);
            if(curDispOffset > 0)
              curDispOffset --;
            SysSetFlag(FL_SENSOR1_DISP_OFFSET, curDispOffset);
            debug_msg("OnTouchSlideDown cj -------sensor 1 offset:%d\r\n",curDispOffset);
            #if IMG_FULL_DISP
            MovieExe_SetIMECrop(_CFG_REC_ID_1);
            #endif  
    	}
    	else
    	{
			curDispOffset = SysGetFlag(FL_SENSOR2_DISP_OFFSET);
            if(curDispOffset > 0)
              curDispOffset --;
			SysSetFlag(FL_SENSOR2_DISP_OFFSET, curDispOffset);
            debug_msg("OnTouchSlideDown-------offset: %d sensor 2 \r\n",curDispOffset);
            #if IMG_FULL_DISP
  			MovieExe_SetIMECrop(_CFG_REC_ID_2);
            #endif

    	}
	}
	return NVTEVT_CONSUME;
}


INT32 UIMenuWndWiFiMobileLinkOK_OnTouchMove(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
//CHKPNT;
    INT32 BL_Adj_Add_Value;
	INT32 iCur_BL_Value_Bar = 0;
//	INT32 iCur_BL_Value_Final = 0;

	if(paramNum == 2 && bFocusBackLightAdj && UxCtrl_IsShow(&UIMenuWndWiFiMobileLinkOK_BackLightLvl_PanelCtrl))
	{
	  //UIFlowWndMovie_SetBriAdjBarShowTime(LCD_BRI_LVL_DISP_TIME);
	   iTouchBLAdjHoldPointCur = paramArray[0];
	   DBGD(paramArray[0]);
	   
	   if(iTouchBLAdjHoldPointPrev == 0)
	   {
	      BL_Adj_Add_Value =  (iTouchBLAdjHoldPointCur - iTouchBLAdjHoldPointInit)/6;
	   }
	   else
	   {
          if(iTouchBLAdjHoldPointCur > iTouchBLAdjHoldPointPrev)
          {
             if((iTouchBLAdjHoldPointCur - iTouchBLAdjHoldPointPrev) < 6 && (iTouchBLAdjHoldPointCur - iTouchBLAdjHoldPointPrev) > 3)
			 	BL_Adj_Add_Value = 1;
			 else
			 	BL_Adj_Add_Value =  (iTouchBLAdjHoldPointCur - iTouchBLAdjHoldPointPrev)/6;
          }
		  else if(iTouchBLAdjHoldPointCur < iTouchBLAdjHoldPointPrev)
		  {
			  if((iTouchBLAdjHoldPointPrev - iTouchBLAdjHoldPointCur) < 6 && (iTouchBLAdjHoldPointPrev - iTouchBLAdjHoldPointCur) > 3)
				 BL_Adj_Add_Value = -1;
			  else
				 BL_Adj_Add_Value =  (iTouchBLAdjHoldPointCur - iTouchBLAdjHoldPointPrev)/6;
		  }
		  else
		  {
		       BL_Adj_Add_Value = 0;
		  }
		  
	   }
	   iTouchBLAdjHoldPointPrev = iTouchBLAdjHoldPointCur;
	   iCur_BL_Value_Bar = (INT32)(UxProgressBar_GetData(&UIMenuWndWiFiMobileLinkOK_BackLightLvl_BarCtrl, PROBAR_CURSTP));
	   #if 1
       iCur_BL_Value_Bar += BL_Adj_Add_Value;
	   if(iCur_BL_Value_Bar < 0)   	 
	   {
	     iCur_BL_Value_Bar = 0;
	   }else if(iCur_BL_Value_Bar > 99)
	   {
	     iCur_BL_Value_Bar = 99;
	   }
#else
	   iCur_BL_Value_Final = iCur_BL_Value_Bar /9 -10;
DBGD(iCur_BL_Value_Bar);
	DBGD(iCur_BL_Value_Final);
	#endif
       UxProgressBar_SetData(&UIMenuWndWiFiMobileLinkOK_BackLightLvl_BarCtrl,PROBAR_CURSTP,iCur_BL_Value_Bar ); //iCur_BL_Value_Bar
	   UxProgressBar_SetData(&UIMenuWndWiFiMobileLinkOK_BackLightLvl_BarCtrl,PROBAR_TOTSTP,99); //99
	
	GxVideo_SetDeviceCtrl(DOUT1, DISPLAY_DEVCTRL_BRIGHTLVL,iCur_BL_Value_Bar);
	   SysSetFlag(FL_LCD_BRIGHTNESS,iCur_BL_Value_Bar);

	}
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnTouchRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	iTouchBLAdjHoldPointInit = 0;
	iTouchBLAdjHoldPointCur = 0;
	iTouchBLAdjHoldPointPrev = 0;
	if(bFocusBackLightAdj == TRUE)
	{
	   if(uiIgnoreTimerID != NULL_TIMER)
	   {
	      GxTimer_StopTimer(&uiIgnoreTimerID);
	   }
	   if(uiIgnoreTimerID == NULL_TIMER)
	      uiIgnoreTimerID = GxTimer_StartTimer(300, NVTEVT_IGNORE_SLIDE_TOUCH_TIMER, ONE_SHOT);
	}
    return NVTEVT_PASS;
}

#include "EthCamAppCmd.h"
 INT32 UIMenuWndWiFiMobileLinkOK_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	 CHKPNT;
	 	if  ( UxCtrl_IsShow(&UIMenuWndWiFiMobileLinkOK_PlaybackModePanelCtrl) )
	 	{
			return NVTEVT_CONSUME;
	 	}

 	debug_msg("%d\r\n",UxCtrl_IsShow(&UIMenuWndWiFiMobileLinkOK_PanelExitWifiCtrl));
  	if (UxCtrl_IsShow(&UIMenuWndWiFiMobileLinkOK_PanelExitWifiCtrl))
  	{
  		FlowWifiMovie_IconHideExitWifiMsg();
		WifiExitCount = 0;
		bDisplayWifiExit = FALSE;
  	}else{
		FlowWifiMovie_IconDrawExitWifiMsg();
		bDisplayWifiExit = TRUE;
		WifiExitCount = 0;
   
  	}
	return NVTEVT_CONSUME;
} 
INT32 UIMenuWndWiFiMobileLinkOK_OnLCA_Alarm(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(paramNum == 2)
    {  
        uiLCA_Alarm_level_Left = paramArray[0];
        uiLCA_Alarm_level_Right = paramArray[1];
        //debug_msg("%d,%d\r\n", uiLCA_Alarm_level_Left, uiLCA_Alarm_level_Right);
        switch(paramArray[0])
        {
            case USER_AVLCA_WRN_NONE:
                bLCA_Alarm_L = FALSE;
                break;
            case USER_AVLCA_WRN_LEVEL_L:
                bLCA_Alarm_L = TRUE;
                //UxState_SetData(&UIFlowWndMovie_Status_Alarm_LCtrl, STATE_CURITEM, UIFlowWndMovie_Status_Alarm_L_ICON_ALARM_LEFT_Y);
                break;
            case USER_AVLCA_WRN_LEVEL_H:
                bLCA_Alarm_L = TRUE;
                //UxState_SetData(&UIFlowWndMovie_Status_Alarm_LCtrl, STATE_CURITEM, UIFlowWndMovie_Status_Alarm_L_ICON_ALARM_LEFT_R);
                break;
            default:
                bLCA_Alarm_L = FALSE;
            break;
        }

        switch(paramArray[1])
        {
            case USER_AVLCA_WRN_NONE:
                bLCA_Alarm_R = FALSE;
                break;
            case USER_AVLCA_WRN_LEVEL_L:
                bLCA_Alarm_R = TRUE;
                //UxState_SetData(&UIFlowWndMovie_Status_Alarm_RCtrl, STATE_CURITEM, UIFlowWndMovie_Status_Alarm_R_ICON_ALARM_RIGHT_Y);
                break;
            case USER_AVLCA_WRN_LEVEL_H:
                bLCA_Alarm_R = TRUE;
                //UxState_SetData(&UIFlowWndMovie_Status_Alarm_RCtrl, STATE_CURITEM, UIFlowWndMovie_Status_Alarm_R_ICON_ALARM_RIGHT_R);
                break;
            default:
                bLCA_Alarm_R = FALSE;
            break;
        }
        //debug_msg("%d,%d\r\n", bLCA_Alarm_L, bLCA_Alarm_R);
    }

    return NVTEVT_PASS;
}

  
//---------------------UIMenuWndWiFiMobileLinkOK_BackLightLvl_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiMobileLinkOK_BackLightLvl_Panel)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_BackLightLvl_Bar)
CTRL_LIST_END

//----------------------UIMenuWndWiFiMobileLinkOK_BackLightLvl_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_BackLightLvl_Panel)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_BackLightLvl_BarCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_BackLightLvl_Bar)
EVENT_END

//#MT CJ# 20200706 --end
//----------------------UIMenuWndWiFiMobileLinkOK_StaticTXT_LinkStsCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_StaticTXT_LinkSts)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Button_DisconnectCtrl Event---------------------------
INT32 UIMenuWndWiFiMobileLinkOK_Button_Disconnect_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Button_Disconnect)
EVENT_ITEM(NVTEVT_CLICK , UIMenuWndWiFiMobileLinkOK_Button_Disconnect_OnKeyEnter)//NVTEVT_KEY_SELECT
EVENT_END

INT32 UIMenuWndWiFiMobileLinkOK_Button_Disconnect_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
//#NT#2016/05/31#Ben Wang -begin
//#NT#Add UVC multimedia function.
#if(UVC_MULTIMEDIA_FUNC == ENABLE)
	if (System_GetState(SYS_STATE_CURRSUBMODE) == SYS_SUBMODE_UVC) {
		Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE), SYS_SUBMODE_NORMAL);
		return NVTEVT_CONSUME;
	}
#endif
//#NT#2016/05/31#Ben Wang -end
#if  (WIFI_FUNC == ENABLE)
#if 0// !defined(_NVT_SDIO_WIFI_NONE_) || !defined(_NVT_USB_WIFI_NONE_)
	//notify current connected socket,new connect not get IP and socket not create
	//cannot disconnet immediate,suggest after 500 ms
	WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_DISCONNECT);
	//delay 500 ms,and then close window
	//in window,use GxTimer replace Timer Delay,it would occupat UI task
	GxTimer_StartTimer(TIMER_HALF_SEC, NVTEVT_DELAY_CLOSE_TIMER, ONE_SHOT);
#else

	Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE), SYS_SUBMODE_NORMAL);
	//should close network application,then stop wifi
	//Ux_PostEvent(NVTEVT_EXE_WIFI_STOP, 0); // cj 20200513 disable close wifi 
	WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_DISCONNECT);


#endif
#endif
	return NVTEVT_CONSUME;
}
//----------------------UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_StaticTXT_MAC)
EVENT_END

//---------------------UIMenuWndWiFiMobileLinkOK_PanelExitWifiCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiMobileLinkOK_PanelExitWifi)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_StatusTxT_Title)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Tab_YES_NO)
CTRL_LIST_END

//----------------------UIMenuWndWiFiMobileLinkOK_PanelExitWifiCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_PanelExitWifi)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_StatusTxT_TitleCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_StatusTxT_Title)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Tab_YES_NOCtrl Event---------------------------
INT32 UIMenuWndWiFiMobileLinkOK_Tab_YES_NO_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_Tab_YES_NO_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_Tab_YES_NO_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Tab_YES_NO)
EVENT_ITEM(NVTEVT_CLICK,UIMenuWndWiFiMobileLinkOK_Tab_YES_NO_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_PRESS,UIMenuWndWiFiMobileLinkOK_Tab_YES_NO_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_RELEASE,UIMenuWndWiFiMobileLinkOK_Tab_YES_NO_OnTouchPanelRelease)
EVENT_END

INT32 UIMenuWndWiFiMobileLinkOK_Tab_YES_NO_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_Tab_YES_NO_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_Tab_YES_NO_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndWiFiMobileLinkOK_ButtonNoCtrl Event---------------------------
INT32 UIMenuWndWiFiMobileLinkOK_ButtonNo_OnTouchPanelClick(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_ButtonNo)
EVENT_ITEM(NVTEVT_CLICK,UIMenuWndWiFiMobileLinkOK_ButtonNo_OnTouchPanelClick)

EVENT_END
INT32 UIMenuWndWiFiMobileLinkOK_ButtonNo_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	WifiExitCount = 0;
	bDisplayWifiExit =FALSE;
	FlowWifiMovie_IconHideExitWifiMsg();
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndWiFiMobileLinkOK_ButtonYesCtrl Event---------------------------
INT32 UIMenuWndWiFiMobileLinkOK_ButtonYes_OnTouchPanelClick(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_ButtonYes)
EVENT_ITEM(NVTEVT_CLICK,UIMenuWndWiFiMobileLinkOK_ButtonYes_OnTouchPanelClick)

EVENT_END
extern void FlowWiFiMovie_StopRec(void);
extern void FlowWiFiMovie_StartRec(void);
INT32 UIMenuWndWiFiMobileLinkOK_ButtonYes_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{  
	if (UIFlowWndMovie_GetRecLockStatus() )
	{
        CHKPNT;
		UIFlowWndMovie_SetRecLockStatus(FALSE);
		if (UxCtrl_IsShow(&UIMenuWndWiFiMobileLinkOK_PanelExitWifiCtrl))
  		{
	  		FlowWifiMovie_IconHideExitWifiMsg();
			WifiExitCount = 0;
			bDisplayWifiExit = FALSE;
  		}
		
        if (FlowMovie_GetDataState() == MOV_ST_REC)
            {
            	FlowWiFiMovie_StopRec();
            	FlowMovie_SetRecCurrTime(0);
				FlowWiFiMovie_StartRec();
            }
	}else{
		WifiExitCount = 0;
		bDisplayWifiExit =FALSE;
		#if 0
		if (gUIMenuWndWiFiTimerID != NULL_TIMER) {
			GxTimer_StopTimer(&gUIMenuWndWiFiTimerID);
		}
		CHKPNT;
		if (g_UILCAAlarmTimerID != NULL_TIMER) {
			 GxTimer_StopTimer(&g_UILCAAlarmTimerID);
		}
		CHKPNT;
		WiFiCmd_HBStop();
		WiFiCmd_MotionDetectStop();
		FlowWifiMovie_IconHideExitWifiMsg();		

		Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE), SYS_SUBMODE_NORMAL);
		WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_DISCONNECT);
		#endif
					
		Ux_PostEvent(NVTEVT_WIFI_EXE_APP_SESSION_CLOSE, 0);
		//should close network application,then stop wifi
		//zjf reopen wifi
		Ux_PostEvent(NVTEVT_EXE_WIFI_STOP, 0);
		Delay_DelayMs(100);
		Ux_PostEvent(NVTEVT_EXE_WIFI_START, 0);
		
		Ux_CloseWindow(&UIMenuWndWiFiMobileLinkOKCtrl,0);
	}
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndWiFiMobileLinkOK_Panel_EMRBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiMobileLinkOK_Panel_EMRBar)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_ProgressBar)
CTRL_LIST_END

//----------------------UIMenuWndWiFiMobileLinkOK_Panel_EMRBarCtrl Event---------------------------
INT32 UIMenuWndWiFiMobileLinkOK_Panel_EMRBar_OnTouchPanelClick(VControl *, UINT32 , UINT32 *);
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Panel_EMRBar)
EVENT_ITEM(NVTEVT_CLICK,UIMenuWndWiFiMobileLinkOK_Panel_EMRBar_OnTouchPanelClick)
EVENT_END
INT32 UIMenuWndWiFiMobileLinkOK_Panel_EMRBar_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)

{
		if (UIFlowWndMovie_GetRecLockStatus() ){
			FlowWifiMovie_IconDrawExitWifiMsg();
				WifiExitCount = 0;
				bDisplayWifiExit =TRUE;
			}
		 return NVTEVT_CONSUME;
}
//----------------------UIMenuWndWiFiMobileLinkOK_ProgressBarCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_ProgressBar)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Static_ENRTimeCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_ENRTime)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_EmrStatusTxT_TitleCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_EmrStatusTxT_Title)
EVENT_END

//---------------------UIMenuWndWiFiMobileLinkOK_PlaybackModePanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiMobileLinkOK_PlaybackModePanel)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_PlaybackMode_StaticText)
CTRL_LIST_END

//----------------------UIMenuWndWiFiMobileLinkOK_PlaybackModePanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_PlaybackModePanel)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_PlaybackMode_StaticTextCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_PlaybackMode_StaticText)
EVENT_END

//---------------------UIMenuWndWiFiMobileLinkOK_Panel_RecUrgCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiMobileLinkOK_Panel_RecUrg)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_RecUrgTxt)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_RecUrgIcon)
CTRL_LIST_END

//----------------------UIMenuWndWiFiMobileLinkOK_Panel_RecUrgCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Panel_RecUrg)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Static_RecUrgTxtCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_RecUrgTxt)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Static_RecUrgIconCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_RecUrgIcon)
EVENT_END

