//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDPLAY_H
#define UIFLOWWNDPLAY_H

#include "UIFramework.h"

typedef enum {
	UIFLOW_PLAY_DISP_ID_1 = 0,
	UIFLOW_PLAY_DISP_ID_2,
	UIFLOW_PLAY_DISP_ID_MAX,
	ENUM_DUMMY4WORD(UIFLOW_PLAY_DISP_ID)
} UIFLOW_PLAY_DISP_ID;

extern VControl UIFlowWndPlayCtrl;//Panel type 

extern VControl UIFlowWndPlay_Static_TitleCtrl;//Panel type 

extern VControl UIFlowWndPlay_StaticTXT_TitleCtrl;//Static type 

extern VControl UIFlowWndPlay_StaticTXT_FileNumCtrl;//Static type 

extern VControl UIFlowWndPlay_StaticTXT_YMDCtrl;//Static type 

extern VControl UIFlowWndPlay_StaticTXT_HMSCtrl;//Static type 

extern VControl UIFlowWndPlay_Panel_OperateCtrl;//Panel type 

extern VControl UIFlowWndPlay_BTN_ReturnCtrl;//Button type 

extern VControl UIFlowWndPlay_BTN_DelCtrl;//Button type 

extern VControl UIFlowWndPlay_BTN_PlayCtrl;//Button type 

extern VControl UIFlowWndPlay_BTN_ExitCtrl;//Button type 

extern VControl UIFlowWndPlay_Panel_OperateCCtrl;//Panel type 

extern VControl UIFlowWndPlay_BTN_ReturnCCtrl;//Button type 

extern VControl UIFlowWndPlay_BTN_DelCCtrl;//Button type 

extern VControl UIFlowWndPlay_BTN_ExitCCtrl;//Button type 

//---------------------UIFlowWndPlayCtrl User Export---------------------------
#endif
