//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndPlayRes.c"
#include "UIFlowWndPlay.h"
#include "UIFlowWndPlayMagnify.h"
#include "AppCommon.h"
#include "Audio.h"
#include "UICommon.h"
#include "UIFlow.h"
//#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
#include "SMediaPlayAPI.h"
#include "DCF.h"
#include "UIAppMoviePlay.h"
//#NT#2012/08/31#Calvin Chang -end
#include "UIAppPlay.h"
#include "UIPlayComm.h"
// Photo mode key mask
#include "FileDB.h"
//#NT#2016/11/10#Niven Cho -begin
//#NT#AUTO_TEST
#include "MsdcNvtCb_Exam.h"
//#NT#2016/11/10#Niven Cho -end
#include "ImageApp_MoviePlay.h"
#include "ImageApp_Play.h"
#include "GxVideoFile.h"
//#NT#2016/03/03#Ben Wang -begin
#include "PrjCfg.h"
#include "AppDisp_MoviePlayView.h"
//#NT#Add debug message for script test.
#define THIS_DBGLVL         2 // 0=FATAL, 1=ERR, 2=WRN, 3=UNIT, 4=FUNC, 5=IND, 6=MSG, 7=VALUE, 8=USER
///////////////////////////////////////////////////////////////////////////////
#define __MODULE__          UIFlowWndPlay
#define __DBGLVL__          ((THIS_DBGLVL>=PRJ_DBG_LVL)?THIS_DBGLVL:PRJ_DBG_LVL)
#define __DBGFLT__          "*" //*=All, [mark]=CustomClass
#include "DebugModule.h"

//#include "UIMenuWndPlayDel.h"
///////////////////////////////////////////////////////////////////////////////
//#NT#2016/03/03#Ben Wang -end
#define PLAY_KEY_PRESS_MASK        (FLGKEY_KEY_MASK_DEFAULT)
#define PLAY_KEY_RELEASE_MASK      FLGKEY_KEY_MASK_NULL//(FLGKEY_UP | FLGKEY_DOWN | FLGKEY_LEFT | FLGKEY_RIGHT)
#define PLAY_KEY_CONTINUE_MASK     FLGKEY_KEY_CONT_MASK_DEFAULT

#define FULL_FILE_PATH_LEN      64

#define BROWSER_VIEW			ENABLE
	static UINT32  g_uiOperateTimerID = NULL_TIMER;
BOOL PlayFocusOperate = FALSE;
BOOL           g_bUIFlowWndPlayNoImgWndOpened   = FALSE;
UINT32         g_uiUIFlowWndPlayCurrentVolume   = AUDIO_VOL_5;
//#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
UINT32         g_uiUIFlowWndPlayCurrenSpeed     = SMEDIAPLAY_SPEED_NORMAL;
UINT32         g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
MOVIEPLAY_FILEPLAY_INFO gMovie_Play_Info        = {0};
FST_FILE       gphUIFlowMovPlay_Filehdl         = NULL;
//#NT#2012/08/31#Calvin Chang -end

MOVIEPLAY_DISP_INFO  gUIFlowWndPlayDispConfig[4] = {
    //enable  disp_id       w     h      ratio     rotate dir
	{TRUE, MOVIEPLAY_DISP_ID_1, 960,  240  ,  4 ,  3  ,  0},
	{TRUE, MOVIEPLAY_DISP_ID_2, 960,  240  ,  4 ,  3  ,  0},
	{TRUE, MOVIEPLAY_DISP_ID_3, 960,  240  ,  4 ,  3  ,  0},
	{TRUE, MOVIEPLAY_DISP_ID_4, 960,  240  ,  4 ,  3  ,  0},
};
//static char g_StringTitleBuf[64] = {0};

//extern BOOL AutoREC;
//---------------------UIFlowWndPlayCtrl Function ---------------------------
void UIFlowMoviePlay_SetSpeed(INT16 uiChangeSpeedLevel);
void UIFlowWndPlay_ConfigDispInfo(void);

//---------------------UIFlowWndPlayCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlay)
CTRL_LIST_ITEM(UIFlowWndPlay_Static_Title)
CTRL_LIST_ITEM(UIFlowWndPlay_Panel_Operate)
CTRL_LIST_ITEM(UIFlowWndPlay_Panel_OperateC)
CTRL_LIST_END

//----------------------UIFlowWndPlayCtrl Event---------------------------
INT32 UIFlowWndPlay_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyNext(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeySelect(VControl *, UINT32, UINT32 *);
#if defined(_KEY_METHOD_4KEY_)
INT32 UIFlowWndPlay_OnKeyPrev(VControl *, UINT32, UINT32 *);
#endif
INT32 UIFlowWndPlay_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyDisplay(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnBattery(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnBatteryLow(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyPlayback(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnMovieFinish(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnMovieOneSec(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnStorageInit(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnStorageChange(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnTimer(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnTouchPanelClick(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIFlowWndPlay)
EVENT_ITEM(NVTEVT_OPEN_WINDOW, UIFlowWndPlay_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW, UIFlowWndPlay_OnClose)
EVENT_ITEM(NVTEVT_KEY_NEXT, UIFlowWndPlay_OnKeyNext)
EVENT_ITEM(NVTEVT_KEY_SELECT, UIFlowWndPlay_OnKeySelect)
#if defined(_KEY_METHOD_4KEY_)
EVENT_ITEM(NVTEVT_KEY_PREV, UIFlowWndPlay_OnKeyPrev)
#endif
EVENT_ITEM(NVTEVT_KEY_UP, UIFlowWndPlay_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN, UIFlowWndPlay_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT, UIFlowWndPlay_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT, UIFlowWndPlay_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN, UIFlowWndPlay_OnKeyNext)
EVENT_ITEM(NVTEVT_KEY_ZOOMOUT, UIFlowWndPlay_OnKeySelect)
EVENT_ITEM(NVTEVT_KEY_MENU, UIFlowWndPlay_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_DISPLAY, UIFlowWndPlay_OnKeyDisplay)
EVENT_ITEM(NVTEVT_KEY_MODE, UIFlowWndPlay_OnKeyMode)
EVENT_ITEM(NVTEVT_CHILD_CLOSE, UIFlowWndPlay_OnChildClose)
EVENT_ITEM(NVTEVT_BATTERY, UIFlowWndPlay_OnBattery)
EVENT_ITEM(NVTEVT_BATTERY_LOW, UIFlowWndPlay_OnBatteryLow)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2, UIFlowWndPlay_OnKeyShutter2)
EVENT_ITEM(NVTEVT_KEY_ENTER, UIFlowWndPlay_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_PLAYBACK, UIFlowWndPlay_OnKeyPlayback)
EVENT_ITEM(NVTEVT_CB_MOVIE_FINISH, UIFlowWndPlay_OnMovieFinish)
EVENT_ITEM(NVTEVT_CB_MOVIE_ONE_SEC, UIFlowWndPlay_OnMovieOneSec)
EVENT_ITEM(NVTEVT_STORAGE_INIT, UIFlowWndPlay_OnStorageInit)
EVENT_ITEM(NVTEVT_STORAGE_CHANGE, UIFlowWndPlay_OnStorageChange)
EVENT_ITEM(NVTEVT_TIMER, UIFlowWndPlay_OnTimer)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlay_OnTouchPanelClick)
EVENT_END

INT8 FileRecoverystatus=0;
void UIFlowWndPlay_CheckStatus(void);
extern  INT32 DetJumpDirect;
 void UIFlowWndPlay_CheckStatus(void)
{
	UINT32 uiStatus, uiCurrMode;
	uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);
	PB_GetParam(PBPRMID_PLAYBACK_MODE, &uiCurrMode);

	//#NT#2017/10/18#Adam Su -begin
	//#NT#AUTO_TEST
	exam_msg("PB_WaitCommandFinish\r\n");
	//#NT#2017/10/18#Adam Su -end
	FileRecoverystatus =0;
	// Decode Error & Read Error
	if (uiStatus & (PB_STA_ERR_FILE | PB_STA_ERR_DECODE)) {
		if (uiCurrMode == PLAYMODE_AVI || uiCurrMode == PLAYMODE_MOVMJPG) {
			UINT32  uiBuffAddr, uiBuffSize;
			CHAR    chaFullName[64] = { 0 };

			PB_GetParam(PBPRMID_DATABUF_ADDR, &uiBuffAddr);
			PB_GetParam(PBPRMID_DATABUF_SIZE, &uiBuffSize);
			PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)&chaFullName);
			FileRecoverystatus=SMediaPlay_FileRecovery(chaFullName, uiBuffAddr, uiBuffSize);
			DBGD(FileRecoverystatus);
			FileDB_Refresh(0);//2016/04/11
			debug_msg("^RSMediaPlay_FileRecovery is skipped.\r\n");
			//if (DetJumpDirect <0)
			{
			if(FileRecoverystatus == 0)
			{
				uiStatus = UIPlay_PlaySingle(PB_SINGLE_CURR);
			}
			}//else if (DetJumpDirect == 1)
			{
			//	uiStatus = UIPlay_PlaySingle(PB_SINGLE_PREV);

			}//else if (DetJumpDirect == 2)
			{
			//	uiStatus = UIPlay_PlaySingle(PB_SINGLE_NEXT);
			}
			//DetJumpDirect = -1;
			if (uiStatus == PB_STA_DONE) {
				return;
			}
		}
		Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_PICTURE_ERR, FLOWWRNMSG_TIMER_2SEC);
	}
}

#if 0
static INT32 UIFlowWndPlay_OnExeUpKeyAct(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiCurrMode;
	PB_GetParam(PBPRMID_PLAYBACK_MODE, &uiCurrMode);
	switch (g_PlbData.State) {
	case PLB_ST_FULL:
		if (uiCurrMode == PLAYMODE_PRIMARY && PB_WaitCommandFinish(PB_WAIT_INFINITE) == PB_STA_DONE) {
			Ux_OpenWindow((VControl *)(&UIFlowWndPlayMagnifyCtrl), 0);
		}
		break;
	case PLB_ST_PLAY_MOV:
		if (g_uiUIFlowWndPlayCurrentVolume < AUDIO_VOL_7) {
			// Start to Play
			g_uiUIFlowWndPlayCurrentVolume++;
			Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 1, g_uiUIFlowWndPlayCurrentVolume);
			//Ux_SendEvent(&CustomMoviePlayObjCtrl,
			//             NVTEVT_EXE_STARTPLAY,
			//             2,
			//             g_uiUIFlowWndPlayCurrenSpeed,
			//             g_uiUIFlowWndPlayCurrenDirection);
			FlowPB_IconDrawMovPlayVolumn(g_uiUIFlowWndPlayCurrentVolume);
		}
		break;

	}
	return NVTEVT_CONSUME;
}

static INT32 UIFlowWndPlay_OnExeDownKeyAct(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiActKey;

	if (paramNum >= 1) {
		uiActKey = paramArray[0];
	} else {
		debug_msg("error parameter!!\r\n");
		return NVTEVT_CONSUME;
	}

	switch (uiActKey) {
	case NVTEVT_KEY_PRESS:
		switch (g_PlbData.State) {
		case PLB_ST_FULL:
			Ux_OpenWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 0);
			break;
		case PLB_ST_PLAY_MOV:
			if (g_uiUIFlowWndPlayCurrentVolume > AUDIO_VOL_MUTE) {
				// Start to Play
				g_uiUIFlowWndPlayCurrentVolume--;
				Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 1, g_uiUIFlowWndPlayCurrentVolume);
				//Ux_SendEvent(&CustomMoviePlayObjCtrl,
				//             NVTEVT_EXE_STARTPLAY,
				//             2,
				//             g_uiUIFlowWndPlayCurrenSpeed,
				//             g_uiUIFlowWndPlayCurrenDirection);
				FlowPB_IconDrawMovPlayVolumn(g_uiUIFlowWndPlayCurrentVolume);
			}
			break;
		}
		break;
	}
	return NVTEVT_CONSUME;
}
#endif
extern UIPLAY_ROOTDIR_TYPE g_uiRootDirType ;  
extern void CheckFileRecovery(void);
INT32 UIFlowWndPlay_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
CHKPNT;
#if 1
//FileDB_Release(0 );
//FileDB_SortBy(0,FILEDB_SORT_BY_SN,TRUE);
//	FileDB_Release(0);
	
	UINT32  uiStatus;
	UINT32 uiFileNum = 0;
#if 1//(SDHOTPLUG_FUNCTION == ENABLE)
	if (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE) {
		Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, UIFlowWndWrnMsg_StatusTXT_Msg_STRID_PLEASE_INSERT_SD, FLOWWRNMSG_TIMER_2SEC);
		return NVTEVT_CONSUME;
	}
#endif
	g_bUIFlowWndPlayNoImgWndOpened = FALSE;
    CHKPNT;
	PB_WaitCommandFinish(PB_WAIT_INFINITE);
	//After playback ready, point to the last file
	PB_GetParam(PBPRMID_TOTAL_FILE_COUNT, &uiFileNum);
//    PB_OpenSpecFileBySeq(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT), TRUE);

	PB_OpenSpecFileBySeq(1, TRUE);
    debug_msg("cj uiFileNum:%d \r\n",uiFileNum);
//PB_OpenSpecFileBySeq(1, TRUE);
        PB_WaitCommandFinish(PB_WAIT_INFINITE);

	//UIPlay_PlaySingle(PB_SINGLE_CURR);  
	uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);
  	CHKPNT;
	//disable video2 and enable video 1
	Display_ShowPreview();
	CHKPNT;

	UpdateVdoWinForPB();
	DBGD(uiStatus);
	if (uiStatus & PB_STA_NOIMAGE)
		//if(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT)==0)
	{
		Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_NO_IMAGE, FLOWWRNMSG_TIMER_2SEC);
		g_bUIFlowWndPlayNoImgWndOpened = TRUE;
		Ux_DefaultEvent(pCtrl, NVTEVT_OPEN_WINDOW, paramNum, paramArray);

		return NVTEVT_CONSUME;
	} else {
		g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
		g_PlbData.State = PLB_ST_FULL;
		//UxTab_SetData(&UIFlowWndPlay_TabNaviCtrl, TAB_FOCUS, UIFlowWndPlay_TabNavi_ButtonPlay);
		UIFlowWndPlay_CheckStatus();
		FlowPB_UpdateIcons(1);
	}
//	UxCtrl_SetShow(&UIFlowWndPlay_Panel_TopCtrl, FALSE);
//	UxCtrl_SetShow(&UIFlowWndPlayMenu_ListCtrl, FALSE);
	
	// Set mask key
	Ux_FlushEventByRange(NVTEVT_KEY_EVT_START, NVTEVT_KEY_EVT_END);
	Input_SetKeyMask(KEY_PRESS, PLAY_KEY_PRESS_MASK);
	Input_SetKeyMask(KEY_RELEASE, PLAY_KEY_RELEASE_MASK);
	Input_SetKeyMask(KEY_CONTINUE, PLAY_KEY_CONTINUE_MASK);

	DBGD(UIPlay_GetRootDirType());
	//CheckFileRecovery();
	#endif 
	if ( UIPlay_GetRootDirType() == ROOTDIR_TYPE_MOVIE_EMR)
	{
		CHKPNT;
		Ux_OpenWindow(&UIFlowWndPlayThumbCtrl,1,ROOTDIR_TYPE_MOVIE_EMR);
   //     return NVTEVT_CONSUME;

	}else if ( UIPlay_GetRootDirType() == ROOTDIR_TYPE_MOVIE)
	{
		CHKPNT;
		Ux_OpenWindow(&UIFlowWndPlayThumbCtrl,1,ROOTDIR_TYPE_MOVIE);
 //       return NVTEVT_CONSUME;
	}else if ( UIPlay_GetRootDirType() == ROOTDIR_TYPE_PHOTO)
 	{
 		CHKPNT;
		Ux_OpenWindow(&UIFlowWndPlayThumbCtrl,1,ROOTDIR_TYPE_PHOTO);

 	}


#if 0
	
	memset(g_StringTitleBuf, 0, 64);
	
	if (paramNum == 1)
	{
		switch (paramArray[0])
		{
			case CYCREC:
				 snprintf(g_StringTitleBuf, sizeof(g_StringTitleBuf), "Loop video");
				break;
				
			case EMERREC:
				snprintf(g_StringTitleBuf, sizeof(g_StringTitleBuf), "Emergency video");
				break;
		}
	 	UxState_SetItemData(& UIFlowWndPlay_StaticTXT_TitleCtrl, 0, STATE_ITEM_STRID,  Txt_Pointer(g_StringTitleBuf));

	}
#else
	char g_StringTitleBuf[64] = "Photo";//{0}; Txt_Pointer(g_StringTitleBuf)
	memset(g_StringTitleBuf, 0, 64);
	snprintf(g_StringTitleBuf, sizeof(g_StringTitleBuf), "Photo");
	//UxStatic_SetData(& UIFlowWndPlay_Panel_TopCtrl, STATIC_VALUE, STRID_PHOTOALBUM);
	// UxList_SetItemData(&UIFlowWndPlayMenu_ListCtrl, 0, LSTITM_ICONID, ICON_PBMENU_LOOP_F);
	//UxList_SetItemData(&UIFlowWndPlayMenu_ListCtrl, 0, LSTITM_ICONID, ICON_PBMENU_LOOP_F);

	//UxCtrl_SetShow(& UIFlowWndPlay_Panel_TopCtrl, FALSE);
	//UxCtrl_SetShow(&UIFlowWndPlayMenu_ListCtrl, FALSE);

	
	
	#endif

	if((System_GetState(SYS_STATE_CARD)  == CARD_INSERTED))
	{
		//if(bRecoveryOneTime == TRUE)
		{
			//bRecoveryOneTime = FALSE;
			//CheckFileRecovery();
		}
	}
	
	Ux_DefaultEvent(pCtrl, NVTEVT_OPEN_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	switch (g_PlbData.State) {
	case PLB_ST_FULL:
	
		break;

	case PLB_ST_PLAY_MOV:
	case PLB_ST_PAUSE_MOV:
	case PLB_ST_FWD_MOV:
	case PLB_ST_BWD_MOV:
		g_PlbData.State        = PLB_ST_FULL;
		g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
		UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
		g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

		ImageApp_MoviePlay_Close();
        if (gMovie_Play_Info.event_cb) {
			#if (NMEDIAPLAY_FUNC == DISABLE)
			gMovie_Play_Info.event_cb(SMEDIAPLAY_EVENT_STOP); // release ISF_Data by AppDisp_ScaleView
			#else //((NMEDIAPLAY_FUNC == ENABLE))
			gMovie_Play_Info.event_cb(MOVIEPLAY_EVENT_STOP);
			#endif
		}

		if (gphUIFlowMovPlay_Filehdl) {
			FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
			gphUIFlowMovPlay_Filehdl = NULL;
		}
		break;
	}

	//#NT#2012/10/23#Philex Lin - begin
	// enable auto power off/USB detect timer
	// enable sound key tone
	KeyScan_EnableMisc(TRUE);
	//#NT#2012/10/23#Philex Lin - end
	//g_PlbData.VideoPBSpeed=PLB_FWD_MOV_1x;
//	Ux_OpenWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 0 ); // UIFlowWndPlayThumbCtrl
CHKPNT;
	Ux_DefaultEvent(pCtrl, NVTEVT_CLOSE_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyNext(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	if (NVTEVT_KEY_RELEASE == paramArray[0]) {
		return NVTEVT_CONSUME;
	}
	switch (g_PlbData.State) {
	case PLB_ST_FULL:
		//Ux_SendEvent(&UIFlowWndPlay_TabNaviCtrl, NVTEVT_NEXT_ITEM, 0);
		break;
	case PLB_ST_PLAY_MOV:
    case PLB_ST_FWD_MOV:
    case PLB_ST_BWD_MOV:
        if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_8x)
        {
            g_PlbData.VideoPBSpeed ++;

            Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
            Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);

            if(g_PlbData.VideoPBSpeed > PLB_FWD_MOV_1x)
            {
                g_PlbData.State = PLB_ST_FWD_MOV;
                g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
            }
            else if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_1x)
            {
                g_PlbData.State = PLB_ST_BWD_MOV;
                g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_BACKWARD;
            }
            else   //uiCurrSpeedIndex == PLAYMOV_SPEED_FWD_1X
            {
                g_PlbData.State = PLB_ST_PLAY_MOV;
                g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
            }

			// Set speed and direction
			UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
			#if (NMEDIAPLAY_FUNC == DISABLE)
			ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURSPD, g_uiUIFlowWndPlayCurrenSpeed);
			ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURDIR, g_uiUIFlowWndPlayCurrenDirection);
			ImageApp_MoviePlay_UpdateAll();
			#else //(NMEDIAPLAY_FUNC == ENABLE)
			UINT32 vdo_idx = AppDisp_MoviePlayView_GetDispIdx(); // get current display video index
			ImageApp_MoviePlay_FilePlay_UpdateSpeedDirect(g_uiUIFlowWndPlayCurrenSpeed, g_uiUIFlowWndPlayCurrenDirection, vdo_idx);
			#endif

            //FlowPB_IconDrawMovSpeed();
            Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
        }
        break;
	case PLB_ST_PAUSE_MOV:
        Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
		#if (NMEDIAPLAY_FUNC == DISABLE)
        ImageApp_MoviePlay_FilePlay_StepByStep(SMEDIAPLAY_DIR_FORWARD, 0);
		#else //(NMEDIAPLAY_FUNC == ENABLE)
		UINT32 vdo_idx = AppDisp_MoviePlayView_GetDispIdx(); // get current display video index
		ImageApp_MoviePlay_FilePlay_StepByStep(SMEDIAPLAY_DIR_FORWARD, vdo_idx);
		#endif
        Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
        break;
	default:
		break;
	}
	return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlay_OnKeyPrev(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	if (NVTEVT_KEY_RELEASE == paramArray[0]) {
		return NVTEVT_CONSUME;
	}
	switch (g_PlbData.State) {
	case PLB_ST_FULL:
        //lyb---2020319
		//Ux_SendEvent(&UIFlowWndPlay_TabNaviCtrl, NVTEVT_PREVIOUS_ITEM, 0);
		break;
	case PLB_ST_PLAY_MOV:
    case PLB_ST_FWD_MOV:
    case PLB_ST_BWD_MOV:
        if(g_PlbData.VideoPBSpeed > PLB_BWD_MOV_8x)
        {
			if (g_PlbData.VideoPBSpeed == PLB_FWD_MOV_1x) {
				g_PlbData.VideoPBSpeed -= 2;
			} else {
				g_PlbData.VideoPBSpeed--;
			}

            Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
            Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);

            if(g_PlbData.VideoPBSpeed > PLB_FWD_MOV_1x)
            {
                g_PlbData.State = PLB_ST_FWD_MOV;
				g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
            }
            else if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_1x)
            {
                g_PlbData.State = PLB_ST_BWD_MOV;
				g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_BACKWARD;
            }
            else   //uiCurrSpeedIndex == PLAYMOV_SPEED_FWD_1X
            {
                g_PlbData.State = PLB_ST_PLAY_MOV;
                g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
            }

			// Set speed and direction
			UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
			#if (NMEDIAPLAY_FUNC == DISABLE)
			ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURSPD, g_uiUIFlowWndPlayCurrenSpeed);
			ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURDIR, g_uiUIFlowWndPlayCurrenDirection);
			ImageApp_MoviePlay_UpdateAll();
			#else //(NMEDIAPLAY_FUNC == ENABLE)
			UINT32 vdo_idx = AppDisp_MoviePlayView_GetDispIdx(); // get current display video index
			ImageApp_MoviePlay_FilePlay_UpdateSpeedDirect(g_uiUIFlowWndPlayCurrenSpeed, g_uiUIFlowWndPlayCurrenDirection, vdo_idx);
			#endif

            //FlowPB_IconDrawMovSpeed();
            Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
        }
        break;
	case PLB_ST_PAUSE_MOV:
        Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
		#if (NMEDIAPLAY_FUNC == DISABLE)
        ImageApp_MoviePlay_FilePlay_StepByStep(SMEDIAPLAY_DIR_BACKWARD, 0);
		#else //(NMEDIAPLAY_FUNC == ENABLE)
		UINT32 vdo_idx = AppDisp_MoviePlayView_GetDispIdx(); // get current display video index
		ImageApp_MoviePlay_FilePlay_StepByStep(SMEDIAPLAY_DIR_BACKWARD, vdo_idx);
		#endif
        Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
        break;
	default:
		break;
	}
	return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlay_OnKeySelect(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	if (NVTEVT_KEY_RELEASE == paramArray[0]) {
		return NVTEVT_CONSUME;
	}
	switch (g_PlbData.State) {
		UINT32 Tabfocus;
	case PLB_ST_FULL:
        //lyb---2020319
		//Tabfocus = UxTab_GetData(&UIFlowWndPlay_TabNaviCtrl, TAB_FOCUS);
		switch (Tabfocus) {
//#MT#lyb -20200319 -begin
#if 0
			char   pFilePath[FULL_FILE_PATH_LEN];
			UINT32 uiPBFileFmt;
			UINT32 uiPBFileSize = 0;
		case UIFlowWndPlay_TabNavi_ButtonPlay:
			PB_GetParam(PBPRMID_CURR_FILEFMT, &uiPBFileFmt);
			if (uiPBFileFmt & (PBFMT_MOVMJPG | PBFMT_AVI | PBFMT_MP4 | PBFMT_TS)) {
                GXVIDEO_INFO VidInfo = {0};
                SMEDIAPLAY_MAX_MEM_INFO SMPMaxMemInfo = {0};

				// Open Video File
				if (gphUIFlowMovPlay_Filehdl) {
					FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
					gphUIFlowMovPlay_Filehdl = NULL;
				}
				if (uiPBFileFmt & PBFMT_TS) {
					PB_GetParam(PBPRMID_CURR_FILESIZE, &uiPBFileSize);
					if (uiPBFileSize <= 0x10000) {
						debug_msg("Wrong video file format!! \r\n");
						break;
					}
				}
				// Get Current index
				PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)pFilePath);

				//#NT#2017/11/13#Adam Su -begin
				//#NT#AUTO_TEST
				exam_msg("Play File Path = %s\r\n", pFilePath);
				//#NT#2017/11/13#Adam Su -end

				// Open Test Media File
				gphUIFlowMovPlay_Filehdl = FileSys_OpenFile(pFilePath, FST_OPEN_READ);

				if (!gphUIFlowMovPlay_Filehdl) {
					debug_msg("UIFlowWndPlay_OnKeySelect: Can't open Video file!\r\n");
					break;
				}
				//#NT#2012/10/23#Philex Lin - begin
				// disable auto power off/USB detect timer
				// disable key tone flag
				KeyScan_EnableMisc(FALSE);
				//#NT#2012/10/23#Philex Lin - end

				UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
				g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

				ImageApp_Play_Close();

				#if (VDO_USE_COPY_BUFFER == ENABLE)
				VdoOut_SetSkipAllocTemp(TRUE);
				#endif

                MoviePlayExe_CapInitFileNaming();
				#if PLAY_CAP_CRYPTO_FUNC
				ImageApp_MoviePlay_Config(MOVIEPLAY_CONFIG_CAP_ENABLE, TRUE);
				#endif

				// Config file play info
				gMovie_Play_Info.fileplay_id = _CFG_FILEPLAY_ID_1;
				gMovie_Play_Info.file_handle = gphUIFlowMovPlay_Filehdl;
				gMovie_Play_Info.curr_speed  = g_uiUIFlowWndPlayCurrenSpeed;
				gMovie_Play_Info.curr_direct = g_uiUIFlowWndPlayCurrenDirection;
				#if (NMEDIAPLAY_FUNC == DISABLE)
				gMovie_Play_Info.event_cb    = Play_MovieCB;
				#else //(NMEDIAPLAY_FUNC == ENABLE)
				gMovie_Play_Info.event_cb    = UIAppPlay_MoviePlayCB;
				#endif

                // Config max mem info
                PB_GetParam(PBPRMID_INFO_VDO, (UINT32*) &VidInfo);
                if (uiPBFileFmt & PBFMT_TS) {
                    SMPMaxMemInfo.FileFormat = MEDIA_FILEFORMAT_TS;
                } else if (uiPBFileFmt & PBFMT_MP4) {
                    SMPMaxMemInfo.FileFormat = MEDIA_FILEFORMAT_MOV;
                }
                SMPMaxMemInfo.VidFR = VidInfo.uiVidRate;
                SMPMaxMemInfo.AudFR = VidInfo.AudInfo.uiSR / 1024;
                SMPMaxMemInfo.TotalSecs = VidInfo.uiToltalSecs;
                SMPMaxMemInfo.CodecType = VidInfo.uiVidType;
                SMPMaxMemInfo.ImageWidth = VidInfo.uiVidWidth;
                SMPMaxMemInfo.ImageHeight = VidInfo.uiVidHeight;
                gMovie_Play_Info.pmax_mem_info = &SMPMaxMemInfo;

				ImageApp_MoviePlay_Config(MOVIEPLAY_CONFIG_FILEPLAY_INFO, (UINT32) &gMovie_Play_Info);

#if (NMEDIAPLAY_FUNC == ENABLE)
#if (_BOARD_DRAM_SIZE_ == 0x04000000)
				if (uiPBFileFmt & PBFMT_TS) {
				//max movie file is 1920x1080p30
					ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_TSDMX_BUFBLK, 4);//NMP_TSDEMUX_BUFBLK
					ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_BLK_TTNUM, 4); //NMP_FILEIN_BUFBLK
				}else{
					ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_TSDMX_BUFBLK, 7);//NMP_TSDEMUX_BUFBLK
					ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_BLK_TTNUM, 7); //NMP_FILEIN_BUFBLK
				}
#else
				ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_TSDMX_BUFBLK, 7);//NMP_TSDEMUX_BUFBLK
				ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_BLK_TTNUM, 7); //NMP_FILEIN_BUFBLK
#endif
#endif

#if (_BOARD_DRAM_SIZE_ <= 0x08000000)
				// 64MB/128MB DRAM cannot support step by step function, since buffer is not enough
				ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_RAW_BLK_NUM, 4);
#else
				// For step play func. Should be GOP num. of video file. default is 15.
				ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_RAW_BLK_NUM, 15);
#endif
				ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_COMM_WORK_BUF, 0);

				// Config rotation info
				UIFlowWndPlay_ConfigDispInfo();

				//flush event first
				Ux_FlushEventByRange(NVTEVT_KEY_EVT_START, NVTEVT_KEY_EVT_END);

				//stop scan
				//SxTimer_SetFuncActive(SX_TIMER_DET_STRG_ID, FALSE);
				SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, FALSE);

				ImageApp_MoviePlay_Open();
				#if (NMEDIAPLAY_FUNC == ENABLE)
				ImageApp_MoviePlay_Start();
				#endif

				//set movie volumn
				Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 2, UI_GetData(FL_MovieAudioPlayIndex), 1);
				FlowPB_UpdateIcons(0);
				g_PlbData.State = PLB_ST_PLAY_MOV;
				FlowPB_IconDrawLeftBtn(TRUE);
				FlowPB_IconDrawRightBtn(TRUE);
				FlowPB_IconDrawMovPlayTime(TRUE);
			} else {
				g_PlbData.State = PLB_ST_MAGNIFY;
				FlowPB_UpdateIcons(0);
				FlowPB_IconDrawLeftBtn(TRUE);

				//#NT#2017/11/17#Adam Su -begin
				//#NT#AUTO_TEST
				PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)pFilePath);
				exam_msg("Play File Path = %s\r\n", pFilePath);
				//#NT#2017/11/17#Adam Su -end
			}
			break;
		case UIFlowWndPlay_TabNavi_ButtonLeft:
			Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
			UIPlay_PlaySingle(PB_SINGLE_PREV);
			UIFlowWndPlay_CheckStatus();
			FlowPB_UpdateIcons(1);
			Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
			break;
		case UIFlowWndPlay_TabNavi_ButtonRight:
			Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
			UIPlay_PlaySingle(PB_SINGLE_NEXT);
			UIFlowWndPlay_CheckStatus();
			FlowPB_UpdateIcons(1);
			Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
			break;
		case UIFlowWndPlay_TabNavi_ButtonUp:
			//Ux_OpenWindow(&UIMenuWndPlayDelCtrl, 0);
			//Ux_OpenWindow((VControl *)(&UIMenuWndPlayConfirmDelCtrl), 1, UIMenuWndPlayConfirmDel_StatusText_STRID_ERASE_THIS);
			Ux_OpenWindow(&MenuCommonConfirmCtrl, 1, IDM_DELETE_THIS);
			break;
		case UIFlowWndPlay_TabNavi_ButtonDown:
			g_PlbData.State = PLB_ST_MENU;
			// Reset specific menu items
			SysSetFlag(FL_PROTECT, PROTECT_ONE);
			// Set Tab menu to Playback menu
			// Open common item menu
			Ux_OpenWindow(&MenuCommonItemCtrl, 0);
			Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_DEFAULT);
			break;

#endif
//#MT#lyb -20200319 -end

        default:
			break;
		}
		break;
	case PLB_ST_MAGNIFY:
		g_PlbData.State = PLB_ST_FULL;
		FlowPB_UpdateIcons(1);
		break;
	case PLB_ST_PLAY_MOV:
	case PLB_ST_PAUSE_MOV:
		g_PlbData.State        = PLB_ST_FULL;
		g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
		UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
		g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

		ImageApp_MoviePlay_Close();
		if (gMovie_Play_Info.event_cb) {
			#if (NMEDIAPLAY_FUNC == DISABLE)
			gMovie_Play_Info.event_cb(SMEDIAPLAY_EVENT_STOP); // release ISF_Data by AppDisp_ScaleView
			#else //((NMEDIAPLAY_FUNC == ENABLE))
			gMovie_Play_Info.event_cb(MOVIEPLAY_EVENT_STOP);
			#endif
		}

		if (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE) {
			return NVTEVT_CONSUME;
		}

		ImageApp_Play_Open();

		//#NT#2012/10/23#Philex Lin - begin
		// enable auto power off/USB detect timer
		// enable key tone flag
		KeyScan_EnableMisc(TRUE);
		//#NT#2012/10/23#Philex Lin - end

		// stop scan
		//if (SxTimer_GetFuncActive(SX_TIMER_DET_STRG_ID)==0)
		//        SxTimer_SetFuncActive(SX_TIMER_DET_STRG_ID, TRUE);

		if (SxTimer_GetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID) == 0) {
			SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, TRUE);
		}


		if (gphUIFlowMovPlay_Filehdl) {
			FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
			gphUIFlowMovPlay_Filehdl = NULL;
		}

		// Play 1st video frame image
		UIPlay_PlaySingle(PB_SINGLE_CURR);
		//#NT#2012/08/31#Calvin Chang -end

		FlowPB_UpdateIcons(1);

		break;
	case PLB_ST_FWD_MOV:
	case PLB_ST_BWD_MOV:
		//#NT#2012/10/23#Philex Lin - begin
        // disable auto power off/USB detect timer
        // disable key tone flag
        KeyScan_EnableMisc(FALSE);
        //#NT#2012/10/23#Philex Lin - end

		// Set to Normal Play
		g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
		UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
		g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

        // Start Play
        #if (NMEDIAPLAY_FUNC == DISABLE)
        ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURSPD, g_uiUIFlowWndPlayCurrenSpeed);
		ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURDIR, g_uiUIFlowWndPlayCurrenDirection);
		ImageApp_MoviePlay_UpdateAll();
		#else //(NMEDIAPLAY_FUNC == ENABLE)
		UINT32 vdo_idx = AppDisp_MoviePlayView_GetDispIdx(); // get current display video index
		ImageApp_MoviePlay_FilePlay_UpdateSpeedDirect(g_uiUIFlowWndPlayCurrenSpeed, g_uiUIFlowWndPlayCurrenDirection, vdo_idx);
		#endif

        /*if (KeyScan_GetPlugDev()!=PLUG_HDMI)
        {
            FlowPB_IconDrawMovPlayVolumn(g_uiUIFlowWndPlayCurrentVolume);
        }*/

        g_PlbData.State = PLB_ST_PLAY_MOV;

        //Update UI
        /*FlowPB_IconDrawMovPlay(TRUE);
        FlowPB_IconDrawMovFwd(TRUE);
        FlowPB_IconDrawMovBwd(TRUE);
        FlowPB_IconDrawMovSpeed();*/
	}

	return NVTEVT_CONSUME;
}
extern     CHAR  ClickFilePath[64];
INT32 UIFlowWndPlay_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    char   pFilePath[FULL_FILE_PATH_LEN];
	
    UINT32 uiPBFileFmt;
    UINT32 uiPBFileSize = 0;

	//指定打开播放的文件路径
		//memcpy(pFilePath, ClickFilePath, sizeof(ClickFilePath));
	//  	PB_SetParam(PBPRMID_CURR_FILEPATH, ClickFilePath);
	//	Delay_DelayMs(100);
		
    PB_GetParam(PBPRMID_CURR_FILEFMT, &uiPBFileFmt);
    if (uiPBFileFmt & (PBFMT_MOVMJPG | PBFMT_AVI | PBFMT_MP4 | PBFMT_TS)) {
        GXVIDEO_INFO VidInfo = {0};
        SMEDIAPLAY_MAX_MEM_INFO SMPMaxMemInfo = {0};

        // Open Video File
        if (gphUIFlowMovPlay_Filehdl) {
            FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
            gphUIFlowMovPlay_Filehdl = NULL;
        }
        if (uiPBFileFmt & PBFMT_TS) {
            PB_GetParam(PBPRMID_CURR_FILESIZE, &uiPBFileSize);
            if (uiPBFileSize <= 0x10000) {
                debug_msg("Wrong video file format!! \r\n");
                return NVTEVT_CONSUME;
            }
        }
		
        // Get Current index
     //   memcpy(pFilePath,ClickFilePath,sizeof(ClickFilePath));
        PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)pFilePath);


        //#NT#2017/11/13#Adam Su -begin
        //#NT#AUTO_TEST
        exam_msg("Play File Path = %s\r\n", pFilePath);
        //#NT#2017/11/13#Adam Su -end

        // Open Test Media File
        gphUIFlowMovPlay_Filehdl = FileSys_OpenFile(pFilePath, FST_OPEN_READ);

        if (!gphUIFlowMovPlay_Filehdl) {
            debug_msg("UIFlowWndPlay_OnKeySelect: Can't open Video file!\r\n");
            return NVTEVT_CONSUME;
        }
        //#NT#2012/10/23#Philex Lin - begin
        // disable auto power off/USB detect timer
        // disable key tone flag
        KeyScan_EnableMisc(FALSE);
        //#NT#2012/10/23#Philex Lin - end

        UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
        g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

        ImageApp_Play_Close();

	#if (VDO_USE_COPY_BUFFER == ENABLE)
        VdoOut_SetSkipAllocTemp(TRUE);
	#endif

        MoviePlayExe_CapInitFileNaming();
	#if PLAY_CAP_CRYPTO_FUNC
        ImageApp_MoviePlay_Config(MOVIEPLAY_CONFIG_CAP_ENABLE, TRUE);
	#endif

        // Config file play info
        gMovie_Play_Info.fileplay_id = _CFG_FILEPLAY_ID_1;
        gMovie_Play_Info.file_handle = gphUIFlowMovPlay_Filehdl;
        gMovie_Play_Info.curr_speed  = g_uiUIFlowWndPlayCurrenSpeed;
        gMovie_Play_Info.curr_direct = g_uiUIFlowWndPlayCurrenDirection;
	#if (NMEDIAPLAY_FUNC == DISABLE)
        gMovie_Play_Info.event_cb    = Play_MovieCB;
	#else //(NMEDIAPLAY_FUNC == ENABLE)
        gMovie_Play_Info.event_cb    = UIAppPlay_MoviePlayCB;
	#endif

        // Config max mem info
        PB_GetParam(PBPRMID_INFO_VDO, (UINT32*) &VidInfo);
        if (uiPBFileFmt & PBFMT_TS) {
            SMPMaxMemInfo.FileFormat = MEDIA_FILEFORMAT_TS;
        } else if (uiPBFileFmt & PBFMT_MP4) {
            SMPMaxMemInfo.FileFormat = MEDIA_FILEFORMAT_MOV;
        }
        SMPMaxMemInfo.VidFR = VidInfo.uiVidRate;
        SMPMaxMemInfo.AudFR = VidInfo.AudInfo.uiSR / 1024;
        SMPMaxMemInfo.TotalSecs = VidInfo.uiToltalSecs;
        SMPMaxMemInfo.CodecType = VidInfo.uiVidType;
        SMPMaxMemInfo.ImageWidth = VidInfo.uiVidWidth;
        SMPMaxMemInfo.ImageHeight = VidInfo.uiVidHeight;
        gMovie_Play_Info.pmax_mem_info = &SMPMaxMemInfo;

        ImageApp_MoviePlay_Config(MOVIEPLAY_CONFIG_FILEPLAY_INFO, (UINT32) &gMovie_Play_Info);

#if (NMEDIAPLAY_FUNC == ENABLE)
#if (_BOARD_DRAM_SIZE_ == 0x04000000)
        if (uiPBFileFmt & PBFMT_TS) {
        //max movie file is 1920x1080p30
            ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_TSDMX_BUFBLK, 4);//NMP_TSDEMUX_BUFBLK
            ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_BLK_TTNUM, 4); //NMP_FILEIN_BUFBLK
        }else{
            ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_TSDMX_BUFBLK, 7);//NMP_TSDEMUX_BUFBLK
            ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_BLK_TTNUM, 7); //NMP_FILEIN_BUFBLK
        }
#else
        ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_TSDMX_BUFBLK, 7);//NMP_TSDEMUX_BUFBLK
        ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_BLK_TTNUM, 7); //NMP_FILEIN_BUFBLK
#endif
#endif

#if (_BOARD_DRAM_SIZE_ <= 0x08000000)
        // 64MB/128MB DRAM cannot support step by step function, since buffer is not enough
        ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_RAW_BLK_NUM, 4);
#else
        // For step play func. Should be GOP num. of video file. default is 15.
        ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_RAW_BLK_NUM, 15);
#endif
        ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_COMM_WORK_BUF, 0);

        // Config rotation info
        UIFlowWndPlay_ConfigDispInfo();

        //flush event first
        Ux_FlushEventByRange(NVTEVT_KEY_EVT_START, NVTEVT_KEY_EVT_END);

        //stop scan
        //SxTimer_SetFuncActive(SX_TIMER_DET_STRG_ID, FALSE);
        SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, FALSE);
        CHKPNT;
        ImageApp_MoviePlay_Open();
	#if (NMEDIAPLAY_FUNC == ENABLE)
        ImageApp_MoviePlay_Start();
	#endif

        //set movie volumn
        Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 2, UI_GetData(FL_MovieAudioPlayIndex), 1);
        FlowPB_UpdateIcons(0);
        g_PlbData.State = PLB_ST_PLAY_MOV;
        FlowPB_IconDrawLeftBtn(TRUE);
        FlowPB_IconDrawRightBtn(TRUE);
        FlowPB_IconDrawMovPlayTime(TRUE);
    } else {
        g_PlbData.State = PLB_ST_MAGNIFY;
        FlowPB_UpdateIcons(0);
        FlowPB_IconDrawLeftBtn(TRUE);
	UxButton_SetItemData(&UIFlowWndPlay_BTN_PlayCtrl, 0, BTNITM_ICONID, ICON_OPERATE_PLAY_F );
        //#NT#2017/11/17#Adam Su -begin
        //#NT#AUTO_TEST
        PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)pFilePath);
        exam_msg("Play File Path = %s\r\n", pFilePath);
        //#NT#2017/11/17#Adam Su -end
    }

	//open auto close operate item
	if (g_uiOperateTimerID == NULL_TIMER) {
		g_uiOperateTimerID = GxTimer_StartTimer(TIMER_ONE_SEC, NVTEVT_1SEC_TIMER, CONTINUE);
	}
	PlayFocusOperate = TRUE;
return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
            UINT32  uiKeyAct;
            char   pFilePath[FULL_FILE_PATH_LEN];
            UINT32 uiPBFileFmt;
            UINT32 uiPBFileSize = 0;
            uiKeyAct = paramArray[0];

            switch (uiKeyAct)
            {
                case NVTEVT_KEY_PRESS:
                    if (0) //(UxCtrl_IsShow(&UIFlowWndPlay_Panel_InvalidCtrl))
                    {
                        //DBG_ERR(" The file decode error !!!  \r\n");
                        return NVTEVT_CONSUME;
                    }
                    if ( UIPlay_GetRootDirType() == ROOTDIR_TYPE_PHOTO  )

                    {
                        Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
                        UIPlay_PlaySingle(PB_SINGLE_NEXT);
                        //Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYSINGLE, 2, PB_SINGLE_NEXT, 1);
                        FlowPB_UpdateIcons(1);
                        UIFlowWndPlay_CheckStatus();
                        Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
                    }
                    else
                    {
                    	debug_msg("g_PlbData.State: %d \r\n",g_PlbData.State);
                        switch (g_PlbData.State)
                        {
                            case PLB_ST_FULL:
					#if  0
                                PB_GetParam(PBPRMID_CURR_FILEFMT, &uiPBFileFmt);
                                if (uiPBFileFmt & (PBFMT_MOVMJPG | PBFMT_AVI | PBFMT_MP4 | PBFMT_TS))
                                {
                                    GXVIDEO_INFO VidInfo = {0};
                                    SMEDIAPLAY_MAX_MEM_INFO SMPMaxMemInfo = {0};

                                    // Open Video File
                                    if (gphUIFlowMovPlay_Filehdl)
                                    {
                                        FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
                                        gphUIFlowMovPlay_Filehdl = NULL;
                                    }
                                    if (uiPBFileFmt & PBFMT_TS)
                                    {
                                        PB_GetParam(PBPRMID_CURR_FILESIZE, &uiPBFileSize);
                                        if (uiPBFileSize <= 0x10000)
                                        {
                                            debug_msg("Wrong video file format!! \r\n");
                                            break;
                                        }
                                    }
                                    // Get Current index
                                    PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)pFilePath);

                                    //#NT#2017/11/13#Adam Su -begin
                                    //#NT#AUTO_TEST
                                    debug_msg("Play File Path = %s\r\n", pFilePath);
                                    //#NT#2017/11/13#Adam Su -end

                                    // Open Test Media File
                                    gphUIFlowMovPlay_Filehdl = FileSys_OpenFile(pFilePath, FST_OPEN_READ);

                                    if (!gphUIFlowMovPlay_Filehdl)
                                    {
                                        debug_msg("UIFlowWndPlay_OnKeySelect: Can't open Video file!\r\n");
                                        break;
                                    }
                                    //#NT#2012/10/23#Philex Lin - begin
                                    // disable auto power off/USB detect timer
                                    // disable key tone flag
                                    KeyScan_EnableMisc(FALSE);
                                    //#NT#2012/10/23#Philex Lin - end

                                    UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                                    g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

                                    ImageApp_Play_Close();

					#if (VDO_USE_COPY_BUFFER == ENABLE)
					CHKPNT;
						VdoOut_SetSkipAllocTemp(TRUE);
					#endif

                                    // Config file play info
                                    gMovie_Play_Info.fileplay_id = _CFG_FILEPLAY_ID_1;
                                    gMovie_Play_Info.file_handle = gphUIFlowMovPlay_Filehdl;
                                    gMovie_Play_Info.curr_speed  = g_uiUIFlowWndPlayCurrenSpeed;
                                    gMovie_Play_Info.curr_direct = g_uiUIFlowWndPlayCurrenDirection;
					#if (NMEDIAPLAY_FUNC == DISABLE)
					gMovie_Play_Info.event_cb    = Play_MovieCB;
					#else //(NMEDIAPLAY_FUNC == ENABLE)
					gMovie_Play_Info.event_cb    = UIAppPlay_MoviePlayCB;
					#endif

                                    // Config max mem info
                                    PB_GetParam(PBPRMID_INFO_VDO, (UINT32 *) &VidInfo);
                                    if (uiPBFileFmt & PBFMT_TS)
                                    {
                                        SMPMaxMemInfo.FileFormat = MEDIA_FILEFORMAT_TS;
                                    }
                                    else if (uiPBFileFmt & PBFMT_MP4)
                                    {
                                        SMPMaxMemInfo.FileFormat = MEDIA_FILEFORMAT_MOV;
                                    }
                                    SMPMaxMemInfo.VidFR = VidInfo.uiVidRate;
                                    SMPMaxMemInfo.AudFR = VidInfo.AudInfo.uiSR / 1024;
                                    SMPMaxMemInfo.TotalSecs = VidInfo.uiToltalSecs;
                                    SMPMaxMemInfo.CodecType = VidInfo.uiVidType;
                                    SMPMaxMemInfo.ImageWidth = VidInfo.uiVidWidth;
                                    SMPMaxMemInfo.ImageHeight = VidInfo.uiVidHeight;
                                    gMovie_Play_Info.pmax_mem_info = &SMPMaxMemInfo;

                                    ImageApp_MoviePlay_Config(MOVIEPLAY_CONFIG_FILEPLAY_INFO, (UINT32) &gMovie_Play_Info);

                                    // For step play func. Should be GOP num. of video file. default is 15.
                                    //ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_RAW_BLK_NUM, 15);
#if (_BOARD_DRAM_SIZE_ <= 0x08000000)
// 64MB/128MB DRAM cannot support step by step function, since buffer is not enough
ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_RAW_BLK_NUM, 4);
#else
// For step play func. Should be GOP num. of video file. default is 15.
ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_RAW_BLK_NUM, 15);
#endif
// Config rotation info
UIFlowWndPlay_ConfigDispInfo();

                                    //flush event first
                                    Ux_FlushEventByRange(NVTEVT_KEY_EVT_START, NVTEVT_KEY_EVT_END);

                                    //stop scan
                                    //SxTimer_SetFuncActive(SX_TIMER_DET_STRG_ID, FALSE);
                                    SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, FALSE);

                                    ImageApp_MoviePlay_Open();
#if (NMEDIAPLAY_FUNC == ENABLE)
ImageApp_MoviePlay_Start();
#endif

                                    //set movie volumn
                                    Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 2, UI_GetData(FL_VOLUME), 1);
                                    //Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 2, UI_GetData(FL_MovieAudioPlayIndex), 1);
                                    FlowPB_UpdateIcons(1);
                                    g_PlbData.State = PLB_ST_PLAY_MOV;
                                    FlowPB_IconDrawMovPlayTime(TRUE);
                                  //  FlowPB_IconDrawMovPlay(TRUE);
					#else
					PB_GetParam(PBPRMID_CURR_FILEFMT, &uiPBFileFmt);
			if (uiPBFileFmt & (PBFMT_MOVMJPG | PBFMT_AVI | PBFMT_MP4 | PBFMT_TS)) {
                		GXVIDEO_INFO VidInfo = {0};
                		SMEDIAPLAY_MAX_MEM_INFO SMPMaxMemInfo = {0};

				// Open Video File
				if (gphUIFlowMovPlay_Filehdl) {
					FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
					gphUIFlowMovPlay_Filehdl = NULL;
				}
				if (uiPBFileFmt & PBFMT_TS) {
					PB_GetParam(PBPRMID_CURR_FILESIZE, &uiPBFileSize);
					if (uiPBFileSize <= 0x10000) {
						debug_msg("Wrong video file format!! \r\n");
						break;
					}
				}
				// Get Current index
				PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)pFilePath);

				//#NT#2017/11/13#Adam Su -begin
				//#NT#AUTO_TEST
				exam_msg("Play File Path = %s\r\n", pFilePath);
				//#NT#2017/11/13#Adam Su -end

				// Open Test Media File
				gphUIFlowMovPlay_Filehdl = FileSys_OpenFile(pFilePath, FST_OPEN_READ);

				if (!gphUIFlowMovPlay_Filehdl) {
					debug_msg("UIFlowWndPlay_OnKeySelect: Can't open Video file!\r\n");
					break;
				}
				//#NT#2012/10/23#Philex Lin - begin
				// disable auto power off/USB detect timer
				// disable key tone flag
				KeyScan_EnableMisc(FALSE);
				//#NT#2012/10/23#Philex Lin - end

				UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
				g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

				ImageApp_Play_Close();

				#if (VDO_USE_COPY_BUFFER == ENABLE)
				VdoOut_SetSkipAllocTemp(TRUE);
				#endif

				// Config file play info
				gMovie_Play_Info.fileplay_id = _CFG_FILEPLAY_ID_1;
				gMovie_Play_Info.file_handle = gphUIFlowMovPlay_Filehdl;
				gMovie_Play_Info.curr_speed  = g_uiUIFlowWndPlayCurrenSpeed;
				gMovie_Play_Info.curr_direct = g_uiUIFlowWndPlayCurrenDirection;
				#if (NMEDIAPLAY_FUNC == DISABLE)
				gMovie_Play_Info.event_cb    = Play_MovieCB;
				#else //(NMEDIAPLAY_FUNC == ENABLE)
				gMovie_Play_Info.event_cb    = UIAppPlay_MoviePlayCB;
				#endif

                // Config max mem info
                PB_GetParam(PBPRMID_INFO_VDO, (UINT32*) &VidInfo);
                if (uiPBFileFmt & PBFMT_TS) {
                    SMPMaxMemInfo.FileFormat = MEDIA_FILEFORMAT_TS;
                } else if (uiPBFileFmt & PBFMT_MP4) {
                    SMPMaxMemInfo.FileFormat = MEDIA_FILEFORMAT_MOV;
                }
                SMPMaxMemInfo.VidFR = VidInfo.uiVidRate;
                SMPMaxMemInfo.AudFR = VidInfo.AudInfo.uiSR / 1024;
                SMPMaxMemInfo.TotalSecs = VidInfo.uiToltalSecs;
                SMPMaxMemInfo.CodecType = VidInfo.uiVidType;
                SMPMaxMemInfo.ImageWidth = VidInfo.uiVidWidth;
                SMPMaxMemInfo.ImageHeight = VidInfo.uiVidHeight;
                gMovie_Play_Info.pmax_mem_info = &SMPMaxMemInfo;

				ImageApp_MoviePlay_Config(MOVIEPLAY_CONFIG_FILEPLAY_INFO, (UINT32) &gMovie_Play_Info);

#if (NMEDIAPLAY_FUNC == ENABLE)
#if (_BOARD_DRAM_SIZE_ == 0x04000000)
				if (uiPBFileFmt & PBFMT_TS) {
				//max movie file is 1920x1080p30
					ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_TSDMX_BUFBLK, 4);//NMP_TSDEMUX_BUFBLK
					ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_BLK_TTNUM, 4); //NMP_FILEIN_BUFBLK
				}else{
					ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_TSDMX_BUFBLK, 7);//NMP_TSDEMUX_BUFBLK
					ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_BLK_TTNUM, 7); //NMP_FILEIN_BUFBLK
				}
#else
				ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_TSDMX_BUFBLK, 7);//NMP_TSDEMUX_BUFBLK
				ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_BLK_TTNUM, 7); //NMP_FILEIN_BUFBLK
#endif
#endif

#if (_BOARD_DRAM_SIZE_ <= 0x08000000)
				// 64MB/128MB DRAM cannot support step by step function, since buffer is not enough
				ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_RAW_BLK_NUM, 4);
#else
				// For step play func. Should be GOP num. of video file. default is 15.
				ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_RAW_BLK_NUM, 15);
#endif
				// Config rotation info
				UIFlowWndPlay_ConfigDispInfo();

				//flush event first
				Ux_FlushEventByRange(NVTEVT_KEY_EVT_START, NVTEVT_KEY_EVT_END);

				//stop scan
				//SxTimer_SetFuncActive(SX_TIMER_DET_STRG_ID, FALSE);
				SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, FALSE);

				ImageApp_MoviePlay_Open();
				#if (NMEDIAPLAY_FUNC == ENABLE)
				ImageApp_MoviePlay_Start();
				#endif

				//set movie volumn
				Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 2, UI_GetData(FL_MovieAudioPlayIndex), 1);
				FlowPB_UpdateIcons(0);
				g_PlbData.State = PLB_ST_PLAY_MOV;
				FlowPB_IconDrawLeftBtn(TRUE);
				FlowPB_IconDrawRightBtn(TRUE);
				FlowPB_IconDrawMovPlayTime(TRUE);
			}
			//}
					#endif
                                
                                else
                                {
                                    g_PlbData.State = PLB_ST_MAGNIFY;
                                    FlowPB_UpdateIcons(0);
                                    //#NT#2017/11/17#Adam Su -begin
                                    //#NT#AUTO_TEST
                                    PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)pFilePath);
                                    debug_msg("Play File Path = %s\r\n", pFilePath);
                                    //#NT#2017/11/17#Adam Su -end
                                }
                                break;
                            case PLB_ST_MAGNIFY:
                                g_PlbData.State = PLB_ST_FULL;
                                FlowPB_UpdateIcons(1);
                                break;
                            case PLB_ST_PLAY_MOV:
                                //Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_PAUSEPLAY, 0);
                                ImageApp_MoviePlay_FilePlay_Pause();
                                g_PlbData.State = PLB_ST_PAUSE_MOV;
                                //FlowPB_IconDrawRightBtn(TRUE);
                                //#NT#2012/10/23#Philex Lin - begin
                                // enable auto power off/USB detect timer
                                // enable sound key tone flag
                                KeyScan_EnableMisc(TRUE);
                                //#NT#2012/10/23#Philex Lin - end
                                FlowPB_UpdateIcons(1);
                               // FlowPB_IconDrawMovPlay(TRUE);
                                break;

                            case PLB_ST_PAUSE_MOV:
                                //#NT#2012/10/23#Philex Lin - begin
                                // disable auto power off/USB detect timer
                                // disable key tone flag
                                KeyScan_EnableMisc(FALSE);
                                //#NT#2012/10/23#Philex Lin - end
                                // Start to Play
                                //set movie volumn again to avoid volumn changed by beep sound
                                Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 2, UI_GetData(FL_VOLUME), 1);
                                //Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 2, UI_GetData(FL_MovieAudioPlayIndex), 1);
                                ImageApp_MoviePlay_FilePlay_Resume();
                                g_PlbData.State = PLB_ST_PLAY_MOV;
                               // FlowPB_IconDrawMovPlay(TRUE);
                                break;

                            case PLB_ST_FWD_MOV:
                            case PLB_ST_BWD_MOV:
                                //#NT#2012/10/23#Philex Lin - begin
                                // disable auto power off/USB detect timer
                                // disable key tone flag
                                KeyScan_EnableMisc(FALSE);
                                //#NT#2012/10/23#Philex Lin - end

                                // Set to Normal Play
                                g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
                                UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                                g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

                                // Start Play
                                ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURSPD, g_uiUIFlowWndPlayCurrenSpeed);
                                ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURDIR, g_uiUIFlowWndPlayCurrenDirection);
                                ImageApp_MoviePlay_UpdateAll();

                                /*if (KeyScan_GetPlugDev()!=PLUG_HDMI)
                                {
                                    FlowPB_IconDrawMovPlayVolumn(g_uiUIFlowWndPlayCurrentVolume);
                                }*/

                                g_PlbData.State = PLB_ST_PLAY_MOV;

                                //Update UI
                                /*FlowPB_IconDrawMovPlay(TRUE);
                                FlowPB_IconDrawMovFwd(TRUE);
                                FlowPB_IconDrawMovBwd(TRUE);
                                FlowPB_IconDrawMovSpeed();*/
                        }
                    }
                    break;
            }
            return NVTEVT_CONSUME;
        }
INT32 UIFlowWndPlay_OnKeyDisplay(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
CHKPNT;
	UINT32 uiStatus;

	//#NT#2012/12/27#Hideo Lin -begin
	//#NT#Fix close child window hang up as card removed
	if (Ux_IsForceCloseWindow()) {
		return NVTEVT_CONSUME;
	}
	//#NT#2012/12/27#Hideo Lin -end
//    UIAppPlay_MoviePlayCB
//    char   pFilePath[FULL_FILE_PATH_LEN];

	if (paramNum > 0) {
		//Return from thumbnail, magnify or delete mode and play current image again.
		switch (paramArray[0]) {
		case NVTRET_THUMBNAIL:
		case NVTRET_MAGNIFY:
			//CHKPNT;
        
			UIPlay_PlaySingle(PB_SINGLE_CURR);
			UIFlowWndPlay_CheckStatus();
			FlowPB_UpdateIcons(1);
			if ( UIPlay_GetRootDirType() != ROOTDIR_TYPE_PHOTO  )
			{
			//CHKPNT;
				FlowPlay_HidePhotoOperate();
				FlowPlay_DrawVideoOperate();
			//	FlowPB_IconDrawPhotoOperateC(FALSE);
			      Ux_PostEvent(NVTEVT_KEY_UP, 1, NVTEVT_KEY_PRESS);	//enter to play!
			}else if ( UIPlay_GetRootDirType() == ROOTDIR_TYPE_PHOTO  ){
				//FlowPB_IconDrawPhotoOperateC(TRUE);
				FlowPlay_DrawPhotoOperate();
				FlowPlay_HideVideoOperate();
			}
			break;
		case NVTRET_DELETE:
		case NVTRET_DELETEALL:
			uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);
			
			if (uiStatus & PB_STA_NOIMAGE)
				//if(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT)==0)
			{
				if (!g_bUIFlowWndPlayNoImgWndOpened) {
					Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_NO_IMAGE, FLOWWRNMSG_TIMER_2SEC);
					g_bUIFlowWndPlayNoImgWndOpened = TRUE;
				}
			} else {
				UIPlay_PlaySingle(PB_SINGLE_CURR);
				UIFlowWndPlay_CheckStatus();
				FlowPB_UpdateIcons(1);
			}
			UxButton_SetItemData(&UIFlowWndPlay_BTN_PlayCtrl, 0, BTNITM_ICONID, ICON_OPERATE_PLAY);

			break;
		case NVTRET_ENTER_MENU:
			// Reset specific menu items
			SysSetFlag(FL_PROTECT, PROTECT_ONE);
			// Open common item menu
			Ux_OpenWindow(&MenuCommonItemCtrl, 0);
			g_bUIFlowWndPlayNoImgWndOpened = FALSE;
			break;
		case NVTRET_WARNING:
			Ux_PostEvent(paramArray[1], 0);
			break;
		}
	} else {
	CHKPNT;//here 
		UIPlay_PlaySingle(PB_SINGLE_CURR);
		uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);
		if (uiStatus & PB_STA_NOIMAGE)
			//if(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT)==0)
		{CHKPNT;
			if (!g_bUIFlowWndPlayNoImgWndOpened) {
				Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_NO_IMAGE, FLOWWRNMSG_TIMER_2SEC);
				g_bUIFlowWndPlayNoImgWndOpened = TRUE;
			} else {
				#if 1
				Ux_OpenWindow(&MenuCommonPlayMenuCtrl, 0);
			CHKPNT;
			#else 
				g_PlbData.State = PLB_ST_MENU;
				Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_NULL);
				// Reset specific menu items
				SysSetFlag(FL_PROTECT, PROTECT_ONE);
				// Open common item menu
				Ux_OpenWindow(&MenuCommonItemCtrl, 0);
				Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_DEFAULT);
				#endif 
			}
		} else { //file error
		CHKPNT;
			//UIPlay_PlaySingle(PB_SINGLE_CURR);
			//FlowPB_UpdateIcons(1);
			//UIFlowWndPlay_CheckStatus();
		}
	}
	g_PlbData.State = PLB_ST_FULL;

	//#NT#2012/10/23#Philex Lin - begin
	// enable auto power off/USB detect timer
	// enable sound key tone flag
	KeyScan_EnableMisc(TRUE);
	//#NT#2012/10/23#Philex Lin - end

	// set mask key
	//Ux_FlushEvent();
	Input_SetKeyMask(KEY_PRESS, PLAY_KEY_PRESS_MASK);
	Input_SetKeyMask(KEY_RELEASE, PLAY_KEY_RELEASE_MASK);
	Input_SetKeyMask(KEY_CONTINUE, PLAY_KEY_CONTINUE_MASK);
	Ux_DefaultEvent(pCtrl, NVTEVT_CHILD_CLOSE, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnBattery(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if 0
	static volatile BOOL bBatteryOn = FALSE;

	UxState_SetData(&UIFlowWndPlay_StatusICN_BatteryCtrl, STATE_CURITEM, GetBatteryLevel());
	if (KeyScan_IsACIn()) {
		bBatteryOn = !bBatteryOn;
		UxCtrl_SetShow(&UIFlowWndPlay_StatusICN_BatteryCtrl, bBatteryOn);
	} else {
		UxCtrl_SetShow(&UIFlowWndPlay_StatusICN_BatteryCtrl, TRUE);
	}
#endif
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnBatteryLow(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, UIFlowWndWrnMsg_StatusTXT_Msg_STRID_BATTERY_LOW, FLOWWRNMSG_TIMER_2SEC);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	if (NVTEVT_KEY_RELEASE == paramArray[0]) {
		return NVTEVT_CONSUME;
	}

	switch (g_PlbData.State) {
	case PLB_ST_PLAY_MOV:
		//Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_PAUSEPLAY, 0);
		ImageApp_MoviePlay_FilePlay_Pause();
		g_PlbData.State = PLB_ST_PAUSE_MOV;
		FlowPB_IconDrawRightBtn(TRUE);
		//#NT#2012/10/23#Philex Lin - begin
		// enable auto power off/USB detect timer
		// enable sound key tone flag
		KeyScan_EnableMisc(TRUE);
		//#NT#2012/10/23#Philex Lin - end
		break;
	case PLB_ST_PAUSE_MOV:
		//#NT#2012/10/23#Philex Lin - begin
		// disable auto power off/USB detect timer
		// disable key tone flag
		KeyScan_EnableMisc(FALSE);
		//#NT#2012/10/23#Philex Lin - end
		// Start to Play
		//set movie volumn again to avoid volumn changed by beep sound
		Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 2, UI_GetData(FL_MovieAudioPlayIndex), 1);
		ImageApp_MoviePlay_FilePlay_Resume();
		g_PlbData.State = PLB_ST_PLAY_MOV;
		FlowPB_IconDrawRightBtn(TRUE);
		break;
	#if (BROWSER_VIEW == ENABLE)
	case PLB_ST_FULL:
		Ux_OpenWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 0);
		break;
	#endif
	default:
		break;
	}

	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyPlayback(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;   
}
INT32 UIFlowWndPlay_OnMovieFinish(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
	g_PlbData.State        = PLB_ST_FULL;
	g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
	UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
	g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

	ImageApp_MoviePlay_Close();
	if (gMovie_Play_Info.event_cb) {
		#if (NMEDIAPLAY_FUNC == DISABLE)
		gMovie_Play_Info.event_cb(SMEDIAPLAY_EVENT_STOP); // release ISF_Data by AppDisp_ScaleView
		#else //((NMEDIAPLAY_FUNC == ENABLE))
		gMovie_Play_Info.event_cb(MOVIEPLAY_EVENT_STOP);
		#endif
	}

	if (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE) {
		return NVTEVT_CONSUME;
	}

	ImageApp_Play_Open();

	//#NT#2012/10/23#Philex Lin - begin
	// enable auto power off/USB detect timer
	// enable key tone flag
	KeyScan_EnableMisc(TRUE);
	//#NT#2012/10/23#Philex Lin - end

	// stop scan
	//if (SxTimer_GetFuncActive(SX_TIMER_DET_STRG_ID)==0)
//        SxTimer_SetFuncActive(SX_TIMER_DET_STRG_ID, TRUE);

	if (SxTimer_GetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID) == 0) {
		SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, TRUE);
	}


	if (gphUIFlowMovPlay_Filehdl) {
		FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
		gphUIFlowMovPlay_Filehdl = NULL;
	}

	// Play 1st video frame image
	UIPlay_PlaySingle(PB_SINGLE_CURR);
	//#NT#2012/08/31#Calvin Chang -end

	FlowPB_UpdateIcons(1);
	//#NT#2016/03/03#Ben Wang -begin
	//#NT#Add debug message for script test.
	DBG_TEST("OnMovieFinish\r\n");
	//#NT#2016/11/10#Niven Cho -begin
	//#NT#AUTO_TEST
	exam_msg("OnMovieFinish\r\n");
	//#NT#2016/11/10#Niven Cho -end
	//#NT#2016/03/03#Ben Wang -end
	UxButton_SetItemData(&UIFlowWndPlay_BTN_PlayCtrl, 0, BTNITM_ICONID, ICON_OPERATE_PLAY );
	
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnMovieOneSec(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{  
	FlowPB_IconDrawMovPlayTime(TRUE);
	//FlowPB_UpdateIcons(TRUE);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnStorageInit(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnStorageChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if (SDHOTPLUG_FUNCTION == ENABLE)
	Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, System_GetState(SYS_STATE_CURRMODE));
#endif
	return NVTEVT_CONSUME;
}

static UINT32 FocusOperateCount = 0;
INT32 UIFlowWndPlay_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32  uiEvent;
	uiEvent = paramNum ? paramArray[0] : 0;
	switch (uiEvent) {
		case NVTEVT_1SEC_TIMER:
			
			if ( 	UxCtrl_IsShow(&UIFlowWndPlay_Panel_OperateCtrl) || 
				UxCtrl_IsShow(&UIFlowWndPlay_Panel_OperateCCtrl))
			{
				
				if ( FocusOperateCount == 5 )
				{
					FocusOperateCount = 0;
					UxCtrl_SetShow(&UIFlowWndPlay_Panel_OperateCtrl,FALSE);
					UxCtrl_SetShow(&UIFlowWndPlay_Panel_OperateCCtrl,FALSE);

					PlayFocusOperate = FALSE;
				}else{
					FocusOperateCount++;
				}
			}else{
				FocusOperateCount = 0;
			}
			break;
		default:
			break;
	}
	return NVTEVT_CONSUME;
}

void FlowPlay_DrawVideoOperate(void)
{
	UxCtrl_SetShow(&UIFlowWndPlay_Panel_OperateCtrl,TRUE);
		UxCtrl_SetShow(&UIFlowWndPlay_BTN_ReturnCtrl,TRUE);//Button type 

		UxCtrl_SetShow(&UIFlowWndPlay_BTN_DelCtrl,TRUE);//Button type 

		UxCtrl_SetShow(&UIFlowWndPlay_BTN_PlayCtrl,TRUE);//Button type 

		UxCtrl_SetShow(&UIFlowWndPlay_BTN_ExitCtrl,TRUE);
		
		UxCtrl_SetShow(&UIFlowWndPlay_Static_TitleCtrl,TRUE);
		UxCtrl_SetShow(&UIFlowWndPlay_StaticTXT_FileNumCtrl,TRUE);//Button type 
		UxCtrl_SetShow(&UIFlowWndPlay_StaticTXT_YMDCtrl,TRUE);//Button type 
		UxCtrl_SetShow(&UIFlowWndPlay_StaticTXT_HMSCtrl,TRUE);//Button type 
		
		PlayFocusOperate = TRUE;
		FocusOperateCount =0;
}
void FlowPlay_HideVideoOperate(void)
{
	UxCtrl_SetShow(&UIFlowWndPlay_Panel_OperateCtrl,FALSE);
	UxCtrl_SetShow(&UIFlowWndPlay_Static_TitleCtrl,FALSE);
	PlayFocusOperate = FALSE;
	FocusOperateCount = 0;
}

void FlowPlay_DrawPhotoOperate(void)
{
	UxCtrl_SetShow(&UIFlowWndPlay_Panel_OperateCCtrl,TRUE);
		UxCtrl_SetShow(&UIFlowWndPlay_BTN_ReturnCCtrl,TRUE);//Button type 

		UxCtrl_SetShow(&UIFlowWndPlay_BTN_DelCCtrl,TRUE);//Button type 
		UxCtrl_SetShow(&UIFlowWndPlay_BTN_ExitCCtrl,TRUE);
		PlayFocusOperate = TRUE;
		FocusOperateCount =0;
}
void FlowPlay_HidePhotoOperate(void)
{
	UxCtrl_SetShow(&UIFlowWndPlay_Panel_OperateCCtrl,FALSE);
	PlayFocusOperate = FALSE;
	FocusOperateCount = 0;
}
INT32 UIFlowWndPlay_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{

	if (UxCtrl_IsShow(&UIFlowWndPlay_Panel_OperateCtrl) )
	{
		CHKPNT;
		FlowPlay_HideVideoOperate();
		return NVTEVT_CONSUME;
		
	}else if (UxCtrl_IsShow(&UIFlowWndPlay_Panel_OperateCtrl) )
	{
		CHKPNT;
		FlowPlay_HidePhotoOperate();
		return NVTEVT_CONSUME;
	}
	if ( 	UIPlay_GetRootDirType() == ROOTDIR_TYPE_MOVIE_EMR ||
		UIPlay_GetRootDirType() == ROOTDIR_TYPE_MOVIE )
	{
		CHKPNT;
		FlowPlay_DrawVideoOperate();
       		return NVTEVT_CONSUME;

	}else if ( UIPlay_GetRootDirType() == ROOTDIR_TYPE_PHOTO)
 	{
 		CHKPNT;
		FlowPlay_DrawPhotoOperate();
		return NVTEVT_CONSUME;

 	}
	

	
}

void UIFlowMoviePlay_SetSpeed(INT16 uiChangeSpeedLevel)
{
	switch (uiChangeSpeedLevel) {
	default:
	case PLB_FWD_MOV_1x:
	case PLB_BWD_MOV_1x:
		g_uiUIFlowWndPlayCurrenSpeed = SMEDIAPLAY_SPEED_NORMAL;
		break;

	case PLB_FWD_MOV_2x:
	case PLB_BWD_MOV_2x:
		g_uiUIFlowWndPlayCurrenSpeed = SMEDIAPLAY_SPEED_2X;
		break;

	case PLB_FWD_MOV_4x:
	case PLB_BWD_MOV_4x:
		g_uiUIFlowWndPlayCurrenSpeed = SMEDIAPLAY_SPEED_4X;
		break;

	case PLB_FWD_MOV_8x:
	case PLB_BWD_MOV_8x:
		g_uiUIFlowWndPlayCurrenSpeed = SMEDIAPLAY_SPEED_8X;
		break;

	}
}

static void UIFlowWndPlay_SetDispParam(MOVIEPLAY_DISP_INFO *p_disp_info, BOOL en)
{
	USIZE device_ratio, src_size;

	if (en == TRUE) { // use dev_id when enable
		device_ratio = GxVideo_GetDeviceAspect(p_disp_info->dev_id);
	} else {
		device_ratio = GxVideo_GetDeviceAspect(DOUT1);
	}
	PB_GetParam(PBPRMID_SRC_SIZE, (UINT32 *) &src_size); // get source image size from playback

	p_disp_info->enable			= en;
	p_disp_info->width			= src_size.w;
	p_disp_info->height			= src_size.h;
	p_disp_info->width_ratio	= device_ratio.w;
	p_disp_info->height_ratio	= device_ratio.h;
	p_disp_info->rotate_dir		= SysVideo_GetDirbyID(p_disp_info->dev_id);

	ImageApp_MoviePlay_Config(MOVIEPLAY_CONFIG_DISP_INFO, (UINT32)p_disp_info);
}

void UIFlowWndPlay_ConfigDispInfo(void)
{
	//MOVIEPLAY_DISP_INFO	*p_disp_info = NULL;

#if (DISPLAY2_FUNC == ENABLE)
	if (g_DualVideo == DISPLAY_1) {
		UIFlowWndPlay_SetDispParam(&gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_1], TRUE);
		UIFlowWndPlay_SetDispParam(&gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_2], FALSE);
	} else if (g_DualVideo == DISPLAY_2) {
		UIFlowWndPlay_SetDispParam(&gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_1], FALSE);
		UIFlowWndPlay_SetDispParam(&gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_2], TRUE);
	} else if (g_DualVideo == (DISPLAY_1|DISPLAY_2)) {
		UIFlowWndPlay_SetDispParam(&gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_1], TRUE);
		UIFlowWndPlay_SetDispParam(&gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_2], TRUE);
	}
#else
	UIFlowWndPlay_SetDispParam(&gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_1], TRUE);
#endif

}
//----------------------UIFlowWndPlayMenu_ListCtrl Event---------------------------
INT32 UIFlowWndPlayMenu_List_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayMenu_List_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayMenu_List_OnTouchPanelPress(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIFlowWndPlayMenu_List)
//EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlayMenu_List_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_USER_RELEASE,UIFlowWndPlayMenu_List_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_PRESS,UIFlowWndPlayMenu_List_OnTouchPanelPress)

EVENT_END
extern void UIPlay_SetRootDirType(UIPLAY_ROOTDIR_TYPE uiType);

INT32 UIFlowWndPlayMenu_List_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	#if 0
		UINT32 CurItem,CutStrID ;  
	CurItem = UxList_GetData(&UIFlowWndPlayMenu_ListCtrl,LST_CURITM);
	    CutStrID = UxList_GetItemData(&MenuCommonItem_ListCtrl, CurItem, LSTITM_STRID);

	debug_msg("curitem:%d  %d\r\n",CurItem,CutStrID);
	switch (CurItem)
	{
		case UIFlowWndPlayMenu_List_ICON_PBMENU_LOOP: //cyc video
			UIPlay_SetRootDirType(ROOTDIR_TYPE_MOVIE);
			Ux_OpenWindow(&UIFlowWndPlayThumbCtrl,1,ROOTDIR_TYPE_MOVIE);
			CHKPNT;
		//	UxList_SetItemData(&UIFlowWndPlayMenu_ListCtrl, 0, LSTITM_ICONID, ICON_PBMENU_LOOP_F);

			break;
			
		case UIFlowWndPlayMenu_List_ICON_PBMENU_URG:// emer video
	//		UxList_SetItemData(&UIFlowWndPlayMenu_ListCtrl, 1, LSTITM_ICONID, ICON_PBMENU_URG_F);

			UIPlay_SetRootDirType(ROOTDIR_TYPE_MOVIE_EMR);
			Ux_OpenWindow(&UIFlowWndPlayThumbCtrl,1,ROOTDIR_TYPE_MOVIE_EMR);
			CHKPNT;
			break;
			

	}
	#endif 
    	return NVTEVT_CONSUME;

}

INT32 UIFlowWndPlayMenu_List_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
CHKPNT;
#if 0
	UINT32 CurItem ;  
	CurItem = UxList_GetData(&UIFlowWndPlayMenu_ListCtrl,LST_CURITM);
	debug_msg("curitem:%d \r\n",CurItem);
	switch (CurItem)
	{  
		case UIFlowWndPlayMenu_List_ICON_PBMENU_LOOP: //cyc video
			UxList_SetItemData(&UIFlowWndPlayMenu_ListCtrl, 0, LSTITM_ICONID, ICON_PBMENU_LOOP);

			break;
			
		case UIFlowWndPlayMenu_List_ICON_PBMENU_URG:// emer video

			UxList_SetItemData(&UIFlowWndPlayMenu_ListCtrl, 1, LSTITM_ICONID, ICON_PBMENU_URG);

			break;
			

	}
#endif
	return NVTEVT_CONSUME;
}


INT32 UIFlowWndPlayMenu_List_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
CHKPNT;
#if 0
	UINT32 CurItem,CutStrID ;  
	CurItem = UxList_GetData(&UIFlowWndPlayMenu_ListCtrl,LST_CURITM);
	    CutStrID = UxList_GetItemData(&MenuCommonItem_ListCtrl, CurItem, LSTITM_STRID);

	debug_msg("curitem:%d  %d\r\n",CurItem,CutStrID);
	switch (CurItem)
	{  
		case UIFlowWndPlayMenu_List_ICON_PBMENU_LOOP: //cyc video
			UxList_SetItemData(&UIFlowWndPlayMenu_ListCtrl, 0, LSTITM_ICONID, ICON_PBMENU_LOOP_F);

			break;
			
		case UIFlowWndPlayMenu_List_ICON_PBMENU_URG:// emer video

			UxList_SetItemData(&UIFlowWndPlayMenu_ListCtrl, 1, LSTITM_ICONID, ICON_PBMENU_URG_F);

			break;
			

	}
	#endif
	return NVTEVT_CONSUME;
}


//---------------------UIFlowWndPlay_Panel_OperateCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlay_Panel_Operate)
CTRL_LIST_ITEM(UIFlowWndPlay_BTN_Return)
CTRL_LIST_ITEM(UIFlowWndPlay_BTN_Del)
CTRL_LIST_ITEM(UIFlowWndPlay_BTN_Play)
CTRL_LIST_ITEM(UIFlowWndPlay_BTN_Exit)
CTRL_LIST_END

//----------------------UIFlowWndPlay_Panel_OperateCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Panel_Operate)
EVENT_END

//----------------------UIFlowWndPlay_BTN_ReturnCtrl Event---------------------------
INT32 UIFlowWndPlay_BTN_Return_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_BTN_Return_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_BTN_Return_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIFlowWndPlay_BTN_Return)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlay_BTN_Return_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_PRESS,UIFlowWndPlay_BTN_Return_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_USER_RELEASE,UIFlowWndPlay_BTN_Return_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_USER_PRESS,UIFlowWndPlay_BTN_Return_OnTouchPanelRelease)

EVENT_END

INT32 UIFlowWndPlay_BTN_Return_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
CHKPNT;
	FocusOperateCount = 0;
	PlayFocusOperate =FALSE;
	if (g_uiOperateTimerID != NULL_TIMER) {
		GxTimer_StopTimer(&g_uiOperateTimerID);
	}
	debug_msg("g_PlbData.State 00000000000000: %d \r\n",g_PlbData.State);
       if ( g_PlbData.State == PLB_ST_PLAY_MOV ) 
       	{
		 ImageApp_MoviePlay_FilePlay_Pause();
                      g_PlbData.State = PLB_ST_PAUSE_MOV;
                       KeyScan_EnableMisc(TRUE);
                       FlowPB_UpdateIcons(1);
			 UxButton_SetItemData(&UIFlowWndPlay_BTN_PlayCtrl, 0, BTNITM_ICONID, ICON_OPERATE_PLAY );
		Delay_DelayMs(200);  
	   }
	   
	{
		
			g_PlbData.State        = PLB_ST_FULL;
			g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
			UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
			g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

			ImageApp_MoviePlay_Close();
        		if (gMovie_Play_Info.event_cb) {
				#if (NMEDIAPLAY_FUNC == DISABLE)
				gMovie_Play_Info.event_cb(SMEDIAPLAY_EVENT_STOP); // release ISF_Data by AppDisp_ScaleView
				#else //((NMEDIAPLAY_FUNC == ENABLE))
				gMovie_Play_Info.event_cb(MOVIEPLAY_EVENT_STOP);
				#endif
			}
			ImageApp_Play_Open();

			KeyScan_EnableMisc(TRUE);

			if (SxTimer_GetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID) == 0) {
				SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, TRUE);
			}
			if (gphUIFlowMovPlay_Filehdl) {
				FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
				gphUIFlowMovPlay_Filehdl = NULL;
			}
		
	}
		debug_msg("RETURN g_PlbData.State: %d \r\n",g_PlbData.State);

	if (System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_PLAYBACK)
	{
		CHKPNT;
		if ( UIPlay_GetRootDirType() == ROOTDIR_TYPE_MOVIE_EMR)
		{
			CHKPNT;   
			Ux_OpenWindow(&UIFlowWndPlayThumbCtrl,1,ROOTDIR_TYPE_MOVIE_EMR);
	        return NVTEVT_CONSUME;

		}else if ( UIPlay_GetRootDirType() == ROOTDIR_TYPE_MOVIE)
		{
			CHKPNT;
			Ux_OpenWindow(&UIFlowWndPlayThumbCtrl,1,ROOTDIR_TYPE_MOVIE);
	        return NVTEVT_CONSUME;
		}else if ( UIPlay_GetRootDirType() == ROOTDIR_TYPE_PHOTO)
		{
			CHKPNT;
			Ux_OpenWindow(&UIFlowWndPlayThumbCtrl,1,ROOTDIR_TYPE_PHOTO);
			return NVTEVT_CONSUME;
		}else{
			
			Ux_OpenWindow(&UIFlowWndPlayThumbCtrl,1,ROOTDIR_TYPE_MOVIE);

		}

	}
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlay_BTN_Return_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	    UxButton_SetItemData(&UIFlowWndPlay_BTN_ReturnCtrl, 0, BTNITM_ICONID, ICON_OPERATE_RETURN_F );

    return NVTEVT_CONSUME;
}


INT32 UIFlowWndPlay_BTN_Return_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxButton_SetItemData(&UIFlowWndPlay_BTN_ReturnCtrl, 0, BTNITM_ICONID, ICON_OPERATE_RETURN );

    return NVTEVT_CONSUME;
}

//----------------------UIFlowWndPlay_BTN_DelCtrl Event---------------------------
INT32 UIFlowWndPlay_BTN_Del_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_BTN_Del_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_BTN_Del_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIFlowWndPlay_BTN_Del)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlay_BTN_Del_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_PRESS,UIFlowWndPlay_BTN_Del_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_USER_RELEASE,UIFlowWndPlay_BTN_Del_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_USER_PRESS,UIFlowWndPlay_BTN_Del_OnTouchPanelRelease)

EVENT_END

INT32 UIFlowWndPlay_BTN_Del_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
CHKPNT;
	FocusOperateCount = 0;
	debug_msg("g_PlbData.State: %d \r\n",g_PlbData.State);
	  if ( g_PlbData.State == PLB_ST_PLAY_MOV ) 
       	{
		 	ImageApp_MoviePlay_FilePlay_Pause();
            g_PlbData.State = PLB_ST_PAUSE_MOV;
            KeyScan_EnableMisc(TRUE);
            FlowPB_UpdateIcons(1);
			UxButton_SetItemData(&UIFlowWndPlay_BTN_PlayCtrl, 0, BTNITM_ICONID, ICON_OPERATE_PLAY );
			Delay_DelayMs(200);  
	   }
	   
	{
		
			g_PlbData.State        = PLB_ST_FULL;
			g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
			UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
			g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

			ImageApp_MoviePlay_Close();
        		if (gMovie_Play_Info.event_cb) {
				#if (NMEDIAPLAY_FUNC == DISABLE)
				gMovie_Play_Info.event_cb(SMEDIAPLAY_EVENT_STOP); // release ISF_Data by AppDisp_ScaleView
				#else //((NMEDIAPLAY_FUNC == ENABLE))
				gMovie_Play_Info.event_cb(MOVIEPLAY_EVENT_STOP);
				#endif
			}
			ImageApp_Play_Open();

			KeyScan_EnableMisc(TRUE);

			if (SxTimer_GetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID) == 0) {
				SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, TRUE);
			}
			if (gphUIFlowMovPlay_Filehdl) {
				FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
				gphUIFlowMovPlay_Filehdl = NULL;
			}
		
	}

	Ux_OpenWindow(&UIMenuWndPlayDelCtrl, 0);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_BTN_Del_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	    UxButton_SetItemData(&UIFlowWndPlay_BTN_DelCtrl, 0, BTNITM_ICONID, ICON_OPERATE_DEL_F );

    return NVTEVT_CONSUME;
}


INT32 UIFlowWndPlay_BTN_Del_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxButton_SetItemData(&UIFlowWndPlay_BTN_DelCtrl, 0, BTNITM_ICONID, ICON_OPERATE_DEL);

    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndPlay_BTN_PlayCtrl Event---------------------------
INT32 UIFlowWndPlay_BTN_Play_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_BTN_Play_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_BTN_Play_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIFlowWndPlay_BTN_Play)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlay_BTN_Play_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_PRESS,UIFlowWndPlay_BTN_Play_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_USER_RELEASE,UIFlowWndPlay_BTN_Play_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_USER_PRESS,UIFlowWndPlay_BTN_Play_OnTouchPanelRelease)

EVENT_END

INT32 UIFlowWndPlay_BTN_Play_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
CHKPNT;
if(FileRecoverystatus != 0)
{
	Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_PICTURE_ERR, FLOWWRNMSG_TIMER_2SEC);

    return NVTEVT_CONSUME;
}
	FocusOperateCount = 0;
	debug_msg("g_PlbData.State: %d \r\n",g_PlbData.State);
        switch (g_PlbData.State) 
	{
		case PLB_ST_PLAY_MOV:
			UxButton_SetItemData(&UIFlowWndPlay_BTN_PlayCtrl, 0, BTNITM_ICONID, ICON_OPERATE_PLAY );
            //Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_PAUSEPLAY, 0);
            ImageApp_MoviePlay_FilePlay_Pause();
            g_PlbData.State = PLB_ST_PAUSE_MOV;
            //FlowPB_IconDrawRightBtn(TRUE);
            //#NT#2012/10/23#Philex Lin - begin
            // enable auto power off/USB detect timer
            // enable sound key tone flag
            KeyScan_EnableMisc(TRUE);
            //#NT#2012/10/23#Philex Lin - end
            FlowPB_UpdateIcons(1);

           // FlowPB_IconDrawMovPlay(TRUE);
            break;

        case PLB_ST_PAUSE_MOV:
			UxButton_SetItemData(&UIFlowWndPlay_BTN_PlayCtrl, 0, BTNITM_ICONID,ICON_OPERATE_PLAY_F);
            //#NT#2012/10/23#Philex Lin - begin
            // disable auto power off/USB detect timer
            // disable key tone flag
            KeyScan_EnableMisc(FALSE);
            //#NT#2012/10/23#Philex Lin - end
            // Start to Play
            //set movie volumn again to avoid volumn changed by beep sound
            Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 2, UI_GetData(FL_VOLUME), 1);
            //Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 2, UI_GetData(FL_MovieAudioPlayIndex), 1);
            ImageApp_MoviePlay_FilePlay_Resume();
            g_PlbData.State = PLB_ST_PLAY_MOV;
           // FlowPB_IconDrawMovPlay(TRUE);
            break;    
		case PLB_ST_FULL:  
			Ux_PostEvent(NVTEVT_KEY_UP, 1, NVTEVT_KEY_PRESS);
			CHKPNT;
			break;
        case PLB_ST_FWD_MOV:
        case PLB_ST_BWD_MOV:
            //#NT#2012/10/23#Philex Lin - begin
            // disable auto power off/USB detect timer
            // disable key tone flag
            KeyScan_EnableMisc(FALSE);
            //#NT#2012/10/23#Philex Lin - end

            // Set to Normal Play
            g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
            UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
            g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

            // Start Play
            ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURSPD, g_uiUIFlowWndPlayCurrenSpeed);
            ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURDIR, g_uiUIFlowWndPlayCurrenDirection);
            ImageApp_MoviePlay_UpdateAll();

            /*if (KeyScan_GetPlugDev()!=PLUG_HDMI)
            {
                FlowPB_IconDrawMovPlayVolumn(g_uiUIFlowWndPlayCurrentVolume);
            }*/

            g_PlbData.State = PLB_ST_PLAY_MOV;
			break;
	}
	
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_BTN_Play_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
		//    UxButton_SetItemData(&UIFlowWndPlay_BTN_PlayCtrl, 0, BTNITM_ICONID, ICON_OPERATE_PLAY_F );

    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_BTN_Play_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
		//    UxButton_SetItemData(&UIFlowWndPlay_BTN_PlayCtrl, 0, BTNITM_ICONID, ICON_OPERATE_PLAY );

    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndPlay_BTN_ExitCtrl Event---------------------------
INT32 UIFlowWndPlay_BTN_Exit_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_BTN_Exit_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_BTN_Exit_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIFlowWndPlay_BTN_Exit)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlay_BTN_Exit_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_PRESS,UIFlowWndPlay_BTN_Exit_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_USER_RELEASE,UIFlowWndPlay_BTN_Exit_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_USER_PRESS,UIFlowWndPlay_BTN_Exit_OnTouchPanelRelease)

EVENT_END

INT32 UIFlowWndPlay_BTN_Exit_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	FocusOperateCount = 0;
	PlayFocusOperate =FALSE;
	
	if (g_uiOperateTimerID != NULL_TIMER) {
		GxTimer_StopTimer(&g_uiOperateTimerID);
	}


	//Ux_RedrawAllWind();
	FlowPB_ClearAllThumbIcon();
	Ux_CloseWindow(&UIFlowWndPlayCtrl, 0);
	
//	Display_SetEnable(LAYER_VDO1, FALSE);

				Ux_PostEvent( NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);

	//	Ux_SendEvent(0, NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);
  
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_BTN_Exit_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
		    UxButton_SetItemData(&UIFlowWndPlay_BTN_ExitCtrl, 0, BTNITM_ICONID, ICON_OPERATE_EXIT_F );

    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_BTN_Exit_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
		    UxButton_SetItemData(&UIFlowWndPlay_BTN_ExitCtrl, 0, BTNITM_ICONID, ICON_OPERATE_EXIT );

    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndPlay_Panel_TopCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Panel_Top)
EVENT_END

//---------------------UIFlowWndPlayPanel_ListCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayPanel_List)
//CTRL_LIST_ITEM(Status_loop)
//CTRL_LIST_ITEM(Status_EMR)
CTRL_LIST_END

//----------------------UIFlowWndPlayPanel_ListCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayPanel_List)
EVENT_END

//----------------------Status_loopCtrl Event---------------------------

INT32 Status_loop_OnTouchPanelClick(VControl *, UINT32 , UINT32 *);
INT32 Status_loop_OnTouchPanelRelease(VControl *, UINT32 , UINT32 *);
INT32 Status_loop_OnTouchPanelPress(VControl *, UINT32 , UINT32 *);

EVENT_BEGIN(Status_loop)
//EVENT_ITEM(NVTEVT_CLICK,Status_loop_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_PRESS,Status_loop_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_USER_RELEASE,Status_loop_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_USER_PRESS,Status_loop_OnTouchPanelRelease)

EVENT_END
INT32 Status_loop_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiCurrMode;

	uiCurrMode= UI_GetData(FL_NextMode);
	if (System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_PLAYBACK)
	{
		CHKPNT;
		debug_msg("%d %d ",System_GetState(SYS_STATE_CURRMODE), UI_GetData(FL_PreMode));
		Ux_OpenWindow((VControl *)(&UIFlowWndPlayCtrl), 1,ROOTDIR_TYPE_MOVIE ); // UIFlowWndPlayThumbCtrl

	}else if (System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_MOVIE)
	{
		
		debug_msg("%d %d ",System_GetState(SYS_STATE_CURRMODE), UI_GetData(FL_PreMode));
		UI_SetData(FL_PreMode, uiCurrMode);
		UI_SetData(FL_NextMode, PRIMARY_MODE_PLAYBACK);
		debug_msg("%d %d ",uiCurrMode, UI_GetData(FL_PreMode));
		Ux_SendEvent(0, NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_PLAYBACK);
   
	}
		UIPlay_SetRootDirType(ROOTDIR_TYPE_MOVIE );//CYCREC

	return NVTEVT_CONSUME;
}

INT32 Status_loop_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
   //    UxState_SetData(&Status_loopCtrl, STATE_CURITEM, Status_loop_ICON_PBMENU_LOOP_F );
	return NVTEVT_CONSUME;
}

INT32 Status_loop_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//       UxState_SetData(&Status_loopCtrl, STATE_CURITEM, Status_loop_ICON_PBMENU_LOOP);
		return NVTEVT_CONSUME;
}


//----------------------Status_EMRCtrl Event---------------------------
INT32 Status_EMR_OnTouchPanelClick(VControl *, UINT32 , UINT32 *);
INT32 Status_EMR_OnTouchPanelPress(VControl *, UINT32 , UINT32 *);
INT32 Status_EMR_OnTouchPanelRelease(VControl *, UINT32 , UINT32 *);

EVENT_BEGIN(Status_EMR)
//EVENT_ITEM(NVTEVT_CLICK,Status_EMR_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_PRESS,Status_EMR_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_USER_RELEASE,Status_EMR_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_USER_PRESS,Status_EMR_OnTouchPanelRelease)

EVENT_END

INT32 Status_EMR_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
					//Ux_OpenWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 1, ROOTDIR_TYPE_MOVIE);

	UINT32 uiCurrMode;

	uiCurrMode= UI_GetData(FL_NextMode);
	if (System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_PLAYBACK)
	{
		CHKPNT;
		debug_msg("%d %d ",System_GetState(SYS_STATE_CURRMODE), UI_GetData(FL_PreMode));
		Ux_OpenWindow((VControl *)(&UIFlowWndPlayCtrl), 1,ROOTDIR_TYPE_MOVIE_EMR ); // UIFlowWndPlayThumbCtrl

	}else if (System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_MOVIE)
	{
		
		debug_msg("%d %d ",System_GetState(SYS_STATE_CURRMODE), UI_GetData(FL_PreMode));
		UI_SetData(FL_PreMode, uiCurrMode);
		UI_SetData(FL_NextMode, PRIMARY_MODE_PLAYBACK);
		debug_msg("%d %d ",uiCurrMode, UI_GetData(FL_PreMode));
		Ux_SendEvent(0, NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_PLAYBACK);
   
	}
		UIPlay_SetRootDirType(ROOTDIR_TYPE_MOVIE_EMR );//CYCREC

			return NVTEVT_CONSUME;
}

INT32 Status_EMR_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //   UxState_SetData(&Status_EMRCtrl, STATE_CURITEM, Status_EMR_ICON_PBMENU_URG_F );
	return NVTEVT_CONSUME;
}

INT32 Status_EMR_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//       UxState_SetData(&Status_EMRCtrl, STATE_CURITEM, Status_EMR_ICON_PBMENU_URG);
		return NVTEVT_CONSUME;
}

//---------------------UIFlowWndPlay_Static_TitleCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlay_Static_Title)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Title)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_FileNum)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_YMD)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_HMS)
CTRL_LIST_END

//----------------------UIFlowWndPlay_Static_TitleCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Static_Title)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_TitleCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Title)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_FileNumCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_FileNum)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_YMDCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_YMD)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_HMSCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_HMS)
EVENT_END

//----------------------Status93Ctrl Event---------------------------
EVENT_BEGIN(Status93)
EVENT_END

//---------------------UIFlowWndPlay_Panel_OperateCCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlay_Panel_OperateC)
CTRL_LIST_ITEM(UIFlowWndPlay_BTN_ReturnC)
CTRL_LIST_ITEM(UIFlowWndPlay_BTN_DelC)
CTRL_LIST_ITEM(UIFlowWndPlay_BTN_ExitC)
CTRL_LIST_END

//----------------------UIFlowWndPlay_Panel_OperateCCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_Panel_OperateC)
EVENT_END

//----------------------UIFlowWndPlay_BTN_ReturnCCtrl Event---------------------------
INT32 UIFlowWndPlay_BTN_ReturnC_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlay_BTN_ReturnC)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlay_BTN_ReturnC_OnTouchPanelClick)
EVENT_END

INT32 UIFlowWndPlay_BTN_ReturnC_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	FocusOperateCount = 0;
	PlayFocusOperate =FALSE;
	Ux_OpenWindow(&UIFlowWndPlayThumbCtrl,1,ROOTDIR_TYPE_PHOTO);
	
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndPlay_BTN_DelCCtrl Event---------------------------
INT32 UIFlowWndPlay_BTN_DelC_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlay_BTN_DelC)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlay_BTN_DelC_OnTouchPanelClick)
EVENT_END

INT32 UIFlowWndPlay_BTN_DelC_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	FocusOperateCount = 0;
	Ux_OpenWindow(&UIMenuWndPlayDelCtrl, 0);
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndPlay_BTN_ExitCCtrl Event---------------------------
INT32 UIFlowWndPlay_BTN_ExitC_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlay_BTN_ExitC)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlay_BTN_ExitC_OnTouchPanelClick)
EVENT_END

INT32 UIFlowWndPlay_BTN_ExitC_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	FocusOperateCount = 0;
	PlayFocusOperate =FALSE;
	
	if (g_uiOperateTimerID != NULL_TIMER) {
		GxTimer_StopTimer(&g_uiOperateTimerID);
	}


	FlowPB_ClearAllThumbIcon();
	Ux_CloseWindow(&UIFlowWndPlayCtrl, 0);
	
//	Display_SetEnable(LAYER_VDO1, FALSE);

				Ux_PostEvent( NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);
    return NVTEVT_CONSUME;
}

