//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDPLAYTHUMB_H
#define UIFLOWWNDPLAYTHUMB_H

#include "UIFramework.h"

extern VControl UIFlowWndPlayThumbCtrl;//Panel type 

extern VControl UIFlowWndPlayThumb_Panel_TopCtrl;//Panel type 

extern VControl UIFlowWndPlayThumb_Static_TitleCtrl;//Static type 

extern VControl UIFlowWndPlayThumb_ThumbIDCtrl;//Static type 

extern VControl UIFlowWndPlayThumb_Static_YMDCtrl;//Static type 

extern VControl UIFlowWndPlayThumb_Static_HMSCtrl;//Static type 

extern VControl UIFlowWndPlayThumb_Panel0Ctrl;//Panel type 

extern VControl UIFlowWndPlayThumb_Panel1Ctrl;//Panel type 

extern VControl UIFlowWndPlayThumb_Panel2Ctrl;//Panel type 

extern VControl UIFlowWndPlayThumb_Panel3Ctrl;//Panel type 

extern VControl UIFlowWndPlayThumb_Panel4Ctrl;//Panel type 

extern VControl UIFlowWndPlayThumb_Panel5Ctrl;//Panel type 

extern VControl UIFlowWndPlayThumb_Panel6Ctrl;//Panel type 

extern VControl UIFlowWndPlayThumb_Panel7Ctrl;//Panel type 

extern VControl UIFlowWndPlayThumb_Panel8Ctrl;//Panel type 

extern VControl UIFlowWndPlayThumb_Panel9Ctrl;//Panel type 

extern VControl UIFlowWndPlayThumb_Panel10Ctrl;//Panel type 

extern VControl UIFlowWndPlayThumb_Panel11Ctrl;//Panel type 

extern VControl UIFlowWndPlayThumb_Panel12Ctrl;//Panel type 

extern VControl UIFlowWndPlayThumb_Panel13Ctrl;//Panel type 

extern VControl UIFlowWndPlayThumb_Panel_OperateCtrl;//Panel type 

extern VControl UIFlowWndPlayThumb_BTN_ReturnCtrl;//Button type 

extern VControl UIFlowWndPlayThumb_BTN_LeftCtrl;//Button type 

extern VControl UIFlowWndPlayThumb_BTN_DelCtrl;//Button type 

extern VControl UIFlowWndPlayThumb_BTN_RightCtrl;//Button type 

extern VControl UIFlowWndPlayThumb_BTN_SelectCtrl;//Button type 

extern VControl UIFlowWndPlayThumb_BTN_ExitCtrl;//Button type 

//---------------------UIFlowWndPlayThumbCtrl User Export---------------------------
#endif
