//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "NVTToolCommand.h"
#include "UIFlowWndPlayThumbRes.c"
#include "UIFlow.h"
#include "UIPlayComm.h"
#include "ImageUnit_VdoOut.h"
#include "GxVideoFile.h"
#include "SMediaPlayAPI.h"
#include "ImageApp_MoviePlay.h"
#include "FileDB.h"
#define PBX_SLIDE_EFFECT_NONE                     0
#define FULL_FILE_PATH_LEN      64

//---------------------UIFlowWndPlayThumbCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel_Top)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel0)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel1)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel2)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel3)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel4)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel5)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel6)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel7)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel8)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel9)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel10)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel11)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel12)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel13)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Panel_Operate)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumbCtrl Event---------------------------
INT32 UIFlowWndPlayThumb_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnChildClose(VControl *, UINT32, UINT32 *);

INT32 UIFlowWndPlayThumb_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnKeyPrev(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnKeyNext(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_OnTouchClick(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIFlowWndPlayThumb)
EVENT_ITEM(NVTEVT_OPEN_WINDOW, UIFlowWndPlayThumb_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW, UIFlowWndPlayThumb_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE, UIFlowWndPlayThumb_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_UP, UIFlowWndPlayThumb_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN, UIFlowWndPlayThumb_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT, UIFlowWndPlayThumb_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT, UIFlowWndPlayThumb_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER, UIFlowWndPlayThumb_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MENU, UIFlowWndPlayThumb_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIFlowWndPlayThumb_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN, UIFlowWndPlayThumb_OnKeyZoomin)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2, UIFlowWndPlayThumb_OnKeyShutter2)
EVENT_ITEM(NVTEVT_KEY_PREV, UIFlowWndPlayThumb_OnKeyPrev)
EVENT_ITEM(NVTEVT_KEY_NEXT, UIFlowWndPlayThumb_OnKeyNext)
//EVENT_ITEM(NVTEVT_CLICK, UIFlowWndPlayThumb_OnTouchClick)


EVENT_END
static char g_StringTitleBuf[64] = {0};
extern BOOL           g_bUIFlowWndPlayNoImgWndOpened ;
extern  void UIFlowWndPlay_CheckStatus(void);

extern PURECT FlowPB_ThumbDisplay(void);

extern FST_FILE       gphUIFlowMovPlay_Filehdl         ;
extern UINT32         g_uiUIFlowWndPlayCurrenDirection ;
extern UINT32         g_uiUIFlowWndPlayCurrenSpeed     ;
extern MOVIEPLAY_FILEPLAY_INFO gMovie_Play_Info        ;
static void UIFlowWndPlayThumb_NaviKey(UINT32 key)
{
	BROWSE_NAVI_INFO BrowseNavi;
	FlowPB_ClearAllThumbIcon();
	SxTimer_SetFuncActive(SX_TIMER_DET_KEY_ID, FALSE);
	BrowseNavi.NaviKey = key;
	BrowseNavi.HorNums = FLOWPB_THUMB_H_NUM2;
	BrowseNavi.VerNums = FLOWPB_THUMB_V_NUM2;

	BrowseThumbNaviKey(&BrowseNavi);

	FlowPB_ShowAllThumbIcon();
	
	FlowPlayThumb_DrawDateTime();
	SxTimer_SetFuncActive(SX_TIMER_DET_KEY_ID, TRUE);
}
static char ModDateTimeStr[34]={0};
static char ModYMDStr[34]={0};
char *Prj_GetModYMDStr(void)
{
	return ModYMDStr;
}
char *Prj_GetModDateTimeStr(void)
{
	return ModDateTimeStr;
}
void FlowPlayThumb_DrawDateTime(void)
{
	UINT32  CurrFileIndex;	//index in thumb
	//BOOL    bLock;
	UINT16 PBAttrib;
	UINT32 uiFileNum = 0;
	PFILEDB_FILE_ATTR  pFileAttr = NULL;;
	UINT32  *pThumbSeqID;
	UINT32 CurrFileSeqID;
	UINT16  *pCurrFileFormat;   // Hideo@0503: variable type should be UINT16
	UINT32 uiParamVal;
	UINT16 TempLastWriteTime;                        ///< The latest time of write file.
	UINT16 TempLastWriteDate;                        ///< The latest date of write file.
	UINT32  /*creDateTime[6],*/modDateTime[6];
	static char item1_Buf[34];
	static char item2_Buf[34];
        UINT32 thousand,hundred;
	PB_GetParam(PBPRMID_TOTAL_FILE_COUNT, &uiFileNum);
       // MY_MSG("=====>uiFileNum %d \r\n",uiFileNum);
	if (uiFileNum)
	{
	     PB_GetParam(PBPRMID_THUMB_FMT_ARRAY, &uiParamVal);
	     pCurrFileFormat = (UINT16 *)uiParamVal;

	     PB_GetParam(PBPRMID_THUMB_CURR_IDX, &CurrFileIndex);
		 
	     PBAttrib = *(pCurrFileFormat+CurrFileIndex-1);
		 
	     FileSys_WaitFinish();
	     PB_GetParam(PBPRMID_THUMB_SEQ_ARRAY, &uiParamVal);
	     pThumbSeqID = (UINT32 *)uiParamVal;	
		 
	     pThumbSeqID += (CurrFileIndex-1);
	     CurrFileSeqID = *pThumbSeqID;


		pFileAttr = FileDB_SearhFile2(0,(CurrFileSeqID-1));

	//
	///< File created time. bit0~4: seconds/2, bit5~10: minutes, bit11~15: hours.
	///< File created date. bit0~4: day(1-31), bit5~8: month(1-12), bit9~15: year(0-127) add 1980 to convert
		TempLastWriteDate = pFileAttr->creDate;
		TempLastWriteTime =pFileAttr->creTime;

		//debug_err(("bobo FlowThumb_DateTime  0x%x  , 0x%x \r\n",TempLastWriteDate,TempLastWriteTime));

		modDateTime[0]=((TempLastWriteDate>>9)&0x007F)+1980;	
		modDateTime[1]=(TempLastWriteDate>>5)&0x000F;
		modDateTime[2]=TempLastWriteDate&0x001f;
		//
		modDateTime[3]=(TempLastWriteTime>>11)&0x001F;	
		modDateTime[4]=(TempLastWriteTime>>5)&0x003F; 
	//date
#if 1// miotone_2018829 zejia change
                //MY_MSG("=====>modDateTime0 %d \r\n",modDateTime[0]);
                //modDateTime[0] = 2151;//test
                thousand = modDateTime[0] / 1000;
                hundred = (modDateTime[0] % 1000) / 100;
                modDateTime[0] = modDateTime[0] -(1000 * thousand) - (100 * hundred);
                //MY_MSG("=====>thousand %d hundred %d modDateTime0 %d \r\n",thousand,hundred,modDateTime[0]);
	        if (modDateTime[0] > 50)  modDateTime[0] = 50;
#else
	    //modDateTime[0] %= 100;
	    modDateTime[0] %= 10000;

	    //if (modDateTime[0] > 50)  modDateTime[0] = 50;
	    if ((modDateTime[0]%100) > 50)  modDateTime[0] = 50;
#endif        
	    if (modDateTime[1] > 12)  modDateTime[0] = 12;
	    if (modDateTime[2] > 31)  modDateTime[0] = 31;
	    snprintf(item1_Buf,20,"%02lu/%02lu/%02lu",modDateTime[0],modDateTime[1],modDateTime[2]);

	//time
	    if (modDateTime[3]>23)   modDateTime[3]=0;
	    if (modDateTime[4]>59)   modDateTime[4]=0;
	    snprintf(item2_Buf,20,"%02lu:%02lu",modDateTime[3],modDateTime[4]);

	    snprintf(ModYMDStr,20,"%s",item1_Buf);
           snprintf(ModDateTimeStr,20,"%s",item2_Buf);
		   
	    UxStatic_SetData(&UIFlowWndPlayThumb_Static_YMDCtrl,STATIC_VALUE,Txt_Pointer(item1_Buf));
	    UxStatic_SetData(&UIFlowWndPlayThumb_Static_HMSCtrl,STATIC_VALUE,Txt_Pointer(item2_Buf));
	    UxCtrl_SetShow(&UIFlowWndPlayThumb_Static_YMDCtrl,TRUE);
	    UxCtrl_SetShow(&UIFlowWndPlayThumb_Static_HMSCtrl,TRUE);
	}
}
INT32 UIFlowWndPlayThumb_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	PURECT          pThumbRect;
	PLAY_BROWSER_OBJ     FlowPBBrowserObj = {0};
	UINT32 FileNumsInDir = 0, NumsPerPage;
	UINT8   HorNums, VerNums;
	UINT32 uiStatus;
    CHKPNT;
	FlowPB_ClearAllThumbIcon();
	pThumbRect = FlowPB_ThumbDisplay();
	HorNums = FLOWPB_THUMB_H_NUM2;
	VerNums = FLOWPB_THUMB_V_NUM2;
	PB_SetParam(PBPRMID_THUMB_LAYOUT_ARRAY, (UINT32)pThumbRect);
//#NT#2012/11/27#Scottie -begin
//#NT#Support Dual Display for PB
	if (System_GetEnableDispCount() == 2) {
		PB_SetParam(PBPRMID_THUMB_LAYOUT_ARRAY2, (UINT32)pThumbRect);
	}
//#NT#2012/11/27#Scottie -end
	NumsPerPage = VerNums * HorNums;
	debug_msg("-------UIFlowWndPlayThumb_OnOpen------NumsPerPage:%d  VerNums:%d  ", NumsPerPage, VerNums);
	PB_GetParam(PBPRMID_TOTAL_FILE_COUNT, &FileNumsInDir);
	FlowPBBrowserObj.BrowserCommand = PB_BROWSER_CURR;
	FlowPBBrowserObj.HorNums        = HorNums;
	FlowPBBrowserObj.VerNums        = VerNums;
	FlowPBBrowserObj.slideEffectFunc = PBX_SLIDE_EFFECT_NONE;
	debug_msg("FileNumsInDir:%d NumsPerPage: %d \r\n",FileNumsInDir, NumsPerPage );
	if (FileNumsInDir <= NumsPerPage) { // means only one page
		FlowPBBrowserObj.bReDecodeImages = FALSE;
	} else {
		FlowPBBrowserObj.bReDecodeImages = TRUE;
	}
	PB_PlayBrowserMode(&FlowPBBrowserObj);
	uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);
	if (uiStatus & PB_STA_NOIMAGE) // 没有文件
	{
		Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_NO_IMAGE, FLOWWRNMSG_TIMER_2SEC);
		g_bUIFlowWndPlayNoImgWndOpened = TRUE;
		Ux_CloseWindow(&UIFlowWndPlayThumbCtrl,0);
		return NVTEVT_CONSUME;

	}
	if ( UIPlay_GetRootDirType() == ROOTDIR_TYPE_PHOTO)
	{
		UxStatic_SetData(&UIFlowWndPlayThumb_Static_TitleCtrl,STATIC_VALUE,STRID_PHOTOALBUM);

	}else if ( UIPlay_GetRootDirType() == ROOTDIR_TYPE_MOVIE_EMR)
	{
		UxStatic_SetData(&UIFlowWndPlayThumb_Static_TitleCtrl,STATIC_VALUE,STRID_PLAYBACK_URG);

	}else if ( UIPlay_GetRootDirType() == ROOTDIR_TYPE_MOVIE)
	{
		UxStatic_SetData(&UIFlowWndPlayThumb_Static_TitleCtrl,STATIC_VALUE,STRID_PLAYBACK_LOOP);

	}
	FlowPB_ShowAllThumbIcon(); // 显示图标
	//	FlowPB_IconDrawThumbSeq(TRUE);
	FlowPlayThumb_DrawDateTime();

	Ux_DefaultEvent(pCtrl, NVTEVT_OPEN_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//FlowPB_ClearAllThumbIcon();
    	Ux_Redraw();
			FlowPB_ShowAllThumbIcon(); // 显示图标

	Ux_DefaultEvent(pCtrl, NVTEVT_CLOSE_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	FlowPB_ClearAllThumbIcon();
    	//Ux_Redraw();
	//		FlowPB_ShowAllThumbIcon(); // 显示图标

	Ux_DefaultEvent(pCtrl, NVTEVT_CLOSE_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnTouchClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
//CHKPNT;
//			Ux_CloseWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 0, NVTRET_THUMBNAIL);

	//Ux_DefaultEvent(pCtrl, NVTEVT_CLOSE_WINDOW, paramNum, paramArray);
	return NVTEVT_PASS;
}

INT32 UIFlowWndPlayThumb_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	CHKPNT;
	INT32 uiActKey;

	uiActKey = paramArray[0];
	switch (uiActKey) {

	case NVTEVT_KEY_PRESS:
		CHKPNT;
		UIFlowWndPlayThumb_NaviKey(NVTEVT_KEY_UP);
		break;
	case NVTEVT_KEY_RELEASE:
		break;

	}

	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	CHKPNT;
	INT32 uiActKey;

	uiActKey = paramArray[0];
	switch (uiActKey) {

	case NVTEVT_KEY_PRESS:
		CHKPNT;
		UIFlowWndPlayThumb_NaviKey(NVTEVT_KEY_DOWN);
		break;
	case NVTEVT_KEY_RELEASE:
		break;
	}

	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	INT32 uiActKey;

	uiActKey = paramArray[0];
	switch (uiActKey) {

	case NVTEVT_KEY_PRESS:
		UIFlowWndPlayThumb_NaviKey(NVTEVT_KEY_LEFT);
		break;

	}

	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	INT32 uiActKey;

	uiActKey = paramArray[0];
	switch (uiActKey) {

	case NVTEVT_KEY_PRESS:
		UIFlowWndPlayThumb_NaviKey(NVTEVT_KEY_RIGHT);
		break;

	}

	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	FlowPB_ClearAllThumbIcon();
	Ux_Redraw();
	if ( UIPlay_GetRootDirType() == ROOTDIR_TYPE_PHOTO)
	{
			Ux_CloseWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 1, NVTRET_MAGNIFY);

	}else{
			Ux_CloseWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 1, NVTRET_THUMBNAIL);

	}
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//Ux_SendEvent(&UISetupObjCtrl,NVTEVT_EXE_CHANGEDSCMODE,1,DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	FlowPB_ClearAllThumbIcon();
	Ux_Redraw();
	Ux_CloseWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 1, NVTRET_THUMBNAIL);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	FlowPB_ClearAllThumbIcon();
	Ux_Redraw();
	Ux_CloseWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 1, NVTRET_THUMBNAIL);
	//Ux_SendEvent(&UISetupObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_OnKeyPrev(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	INT32 uiActKey;

	uiActKey = paramArray[0];
	switch (uiActKey) {

	case NVTEVT_KEY_PRESS:
		UIFlowWndPlayThumb_NaviKey(NVTEVT_KEY_LEFT);
		break;

	}

	return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlayThumb_OnKeyNext(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	INT32 uiActKey;

	uiActKey = paramArray[0];
	switch (uiActKey) {

	case NVTEVT_KEY_PRESS:
		UIFlowWndPlayThumb_NaviKey(NVTEVT_KEY_RIGHT);
		break;

	}

	return NVTEVT_CONSUME;
}


//---------------------UIFlowWndPlayThumb_Panel_TopCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel_Top)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Static_Title)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_ThumbID)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Static_YMD)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_Static_HMS)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_Panel_TopCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel_Top)
EVENT_END

//----------------------UIFlowWndPlayThumb_Static_TitleCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Static_Title)
EVENT_END

//----------------------UIFlowWndPlayThumb_ThumbIDCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_ThumbID)
EVENT_END

//----------------------UIFlowWndPlayThumb_Static_YMDCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Static_YMD)
EVENT_END

//----------------------UIFlowWndPlayThumb_Static_HMSCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Static_HMS)
EVENT_END

//---------------------UIFlowWndPlayThumb_Panel0Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel0)
CTRL_LIST_END

INT32 UIFlowWndPlayThumb_Panel0_OnTouchPanelClick(VControl *, UINT32 , UINT32 *);

//----------------------UIFlowWndPlayThumb_Panel0Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel0)
//EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlayThumb_Panel0_OnTouchPanelClick)
EVENT_END

UINT32 PrevThumbNialCnt = 0;
UINT32 CurThumbNialCnt = 0;
    CHAR  ClickFilePath[64] = {0};

extern void   VdoOut_SetSkipAllocTemp(UINT32 is_alloc);
#include "SysCommon.h"
  UINT32    indexfileplaythumb =0;
BOOL bDetClick = 0;
INT32  DetJumpDirect =-1;
INT32 UIFlowWndPlayThumb_Panel0_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	CHKPNT;
	debug_msg("g_PlbData.State: %d \r\n",g_PlbData.State);
	UIPlay_PlaySingle(PB_SINGLE_CURR);
		UIFlowWndPlay_CheckStatus();			

	Ux_CloseWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 1, NVTRET_THUMBNAIL);
	
	return  NVTEVT_CONSUME;
	
	PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)ClickFilePath);
//debug_msg("Click File Path 1= %s\r\n", ClickFilePath);

FILEDB_FILE_ATTR *pFileAttr;
CHAR path[50]="A:\\";
     
 

   //indexfileplaythumb = FileDB_GetIndexByPath(0,path);
     
  // if (index!=FILEDB_SEARCH_ERR)
     
   {
     
       pFileAttr = FileDB_SearhFile(0, indexfileplaythumb);
     
   }
		debug_msg("pFileAttr = %s\r\n", pFileAttr->filePath);
strncpy(ClickFilePath, pFileAttr->filePath, sizeof(pFileAttr->filePath));
debug_msg("Click File Path 2  = %s %d \r\n", ClickFilePath,indexfileplaythumb);
indexfileplaythumb ++;
	Ux_CloseWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 1, NVTRET_THUMBNAIL);
	
	return  NVTEVT_CONSUME;

}
//----------------
//---------------------UIFlowWndPlayThumb_Panel1Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel1)
CTRL_LIST_END


//----------------------UIFlowWndPlayThumb_Panel1Ctrl Event---------------------------
INT32  UIFlowWndPlayThumb_Panel1_OnTouchPanelClick(VControl *, UINT32 , UINT32 *);

EVENT_BEGIN(UIFlowWndPlayThumb_Panel1)
//EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlayThumb_Panel1_OnTouchPanelClick)

EVENT_END
INT32 UIFlowWndPlayThumb_Panel1_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
//Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);			
	UIPlay_PlaySingle(PB_SINGLE_PREV);			
	UIFlowWndPlay_CheckStatus();			
	//FlowPB_UpdateIcons(1);			
//Input_SetKeyMask(KEY_PRESS,FLGKEY_KEY_MASK_DEFAULT);

Ux_CloseWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 1, NVTRET_THUMBNAIL);
	
	return  NVTEVT_CONSUME;
	PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)ClickFilePath);
debug_msg("Click File Path 1= %s\r\n", ClickFilePath);

FILEDB_FILE_ATTR *pFileAttr;
CHAR path[50]="A:\\";
     
   UINT32    index;

    
 
   index = FileDB_GetIndexByPath(0,path);
     
//   if (index!=FILEDB_SEARCH_ERR)
     
   {
     
       pFileAttr = FileDB_SearhFile(0, 1);
     
   }
		debug_msg("pFileAttr = %s\r\n", pFileAttr->filePath);
strncpy(ClickFilePath, pFileAttr->filePath, sizeof(pFileAttr->filePath));
debug_msg("Click File Path 2  = %s\r\n", ClickFilePath);

	CHKPNT;
	Ux_CloseWindowClear((VControl *)(&UIFlowWndPlayThumbCtrl), 1, NVTRET_THUMBNAIL);
	//PrevThumbNialCnt = CurThumbNialCnt;
    	
return NVTEVT_CONSUME;

}
//---------------------UIFlowWndPlayThumb_Panel2Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel2)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_Panel2Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel2)
//EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlayThumb_Panel0_OnTouchPanelClick)

EVENT_END

//---------------------UIFlowWndPlayThumb_Panel3Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel3)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_Panel3Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel3)
//EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlayThumb_Panel0_OnTouchPanelClick)

EVENT_END

//---------------------UIFlowWndPlayThumb_Panel4Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel4)
CTRL_LIST_END


//----------------------UIFlowWndPlayThumb_Panel4Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel4)
//EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlayThumb_Panel0_OnTouchPanelClick)

EVENT_END

//---------------------UIFlowWndPlayThumb_Panel5Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel5)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_Panel5Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel5)
//EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlayThumb_Panel0_OnTouchPanelClick)

EVENT_END

//---------------------UIFlowWndPlayThumb_Panel6Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel6)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_Panel6Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel6)
//EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlayThumb_Panel0_OnTouchPanelClick)

EVENT_END

//---------------------UIFlowWndPlayThumb_Panel7Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel7)

CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_Panel7Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel7)
//EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlayThumb_Panel0_OnTouchPanelClick)

EVENT_END

//---------------------UIFlowWndPlayThumb_Panel8Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel8)

CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_Panel8Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel8)
//EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlayThumb_Panel0_OnTouchPanelClick)

EVENT_END

//---------------------UIFlowWndPlayThumb_Panel9Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel9)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_Panel9Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel9)
//EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlayThumb_Panel0_OnTouchPanelClick)

EVENT_END

//---------------------UIFlowWndPlayThumb_Panel10Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel10)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_Panel10Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel10)
//EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlayThumb_Panel0_OnTouchPanelClick)

EVENT_END

//---------------------UIFlowWndPlayThumb_Panel11Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel11)
CTRL_LIST_END

//---
//----------------------UIFlowWndPlayThumb_Panel11Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel11)
//EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlayThumb_Panel0_OnTouchPanelClick)

EVENT_END

//---------------------UIFlowWndPlayThumb_Panel12Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel12)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_Panel12Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel12)
//EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlayThumb_Panel0_OnTouchPanelClick)

EVENT_END

//---------------------UIFlowWndPlayThumb_Panel13Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel13)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_Panel13Ctrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel13)
//EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlayThumb_Panel0_OnTouchPanelClick)
EVENT_END

//---------------------UIFlowWndPlayThumb_Panel_OperateCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayThumb_Panel_Operate)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_BTN_Return)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_BTN_Left)
//CTRL_LIST_ITEM(UIFlowWndPlayThumb_BTN_Del)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_BTN_Right)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_BTN_Select)
CTRL_LIST_ITEM(UIFlowWndPlayThumb_BTN_Exit)
CTRL_LIST_END

//----------------------UIFlowWndPlayThumb_Panel_OperateCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayThumb_Panel_Operate)
EVENT_END

//----------------------UIFlowWndPlayThumb_BTN_ReturnCtrl Event---------------------------
INT32 UIFlowWndPlayThumb_BTN_Return_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_BTN_Return_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_BTN_Return_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlayThumb_BTN_Return)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlayThumb_BTN_Return_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_PRESS,UIFlowWndPlayThumb_BTN_Return_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_USER_RELEASE,UIFlowWndPlayThumb_BTN_Return_OnTouchPanelRelease)

EVENT_END

INT32 UIFlowWndPlayThumb_BTN_Return_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	CHKPNT;

	Ux_SendEvent(0, NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_PLAYMENU);
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlayThumb_BTN_Return_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	   UxButton_SetItemData(&UIFlowWndPlayThumb_BTN_ReturnCtrl, 0, BTNITM_ICONID, ICON_OPERATE_RETURN_F );

    return NVTEVT_CONSUME;
}


INT32 UIFlowWndPlayThumb_BTN_Return_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxButton_SetItemData(&UIFlowWndPlayThumb_BTN_ReturnCtrl, 0, BTNITM_ICONID, ICON_OPERATE_RETURN );

    return NVTEVT_CONSUME;
}

//----------------------UIFlowWndPlayThumb_BTN_LeftCtrl Event---------------------------
INT32 UIFlowWndPlayThumb_BTN_Left_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_BTN_Left_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_BTN_Left_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);


EVENT_BEGIN(UIFlowWndPlayThumb_BTN_Left)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlayThumb_BTN_Left_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_PRESS,UIFlowWndPlayThumb_BTN_Left_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_USER_RELEASE,UIFlowWndPlayThumb_BTN_Left_OnTouchPanelRelease)

EVENT_END

INT32 UIFlowWndPlayThumb_BTN_Left_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
CHKPNT;
	UIFlowWndPlayThumb_NaviKey(NVTEVT_KEY_LEFT);
		//Ux_PostEvent(NVTEVT_KEY_UP, 1, NVTEVT_KEY_PRESS);
		    return NVTEVT_CONSUME;

	CHKPNT;
	bDetClick = 1;
	DetJumpDirect = 1;
		//	UIPlay_PlaySingle(PB_SINGLE_PREV);
		//				FlowPB_UpdateIcons(1);
		//	UIFlowWndPlay_CheckStatus();
		//
			
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlayThumb_BTN_Left_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	   UxButton_SetItemData(&UIFlowWndPlayThumb_BTN_LeftCtrl, 0, BTNITM_ICONID, ICON_OPERATE_LEFT_F );

    return NVTEVT_CONSUME;
}


INT32 UIFlowWndPlayThumb_BTN_Left_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxButton_SetItemData(&UIFlowWndPlayThumb_BTN_LeftCtrl, 0, BTNITM_ICONID, ICON_OPERATE_LEFT );

    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndPlayThumb_BTN_DelCtrl Event---------------------------
INT32 UIFlowWndPlayThumb_BTN_Del_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_BTN_Del_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_BTN_Del_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIFlowWndPlayThumb_BTN_Del)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlayThumb_BTN_Del_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_PRESS,UIFlowWndPlayThumb_BTN_Del_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_USER_RELEASE,UIFlowWndPlayThumb_BTN_Del_OnTouchPanelRelease)

EVENT_END

INT32 UIFlowWndPlayThumb_BTN_Del_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	CHKPNT;
	Ux_CloseWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 1,NVTRET_DELETE);
	//Ux_OpenWindow(&UIMenuWndPlayDelCtrl, 0);

	
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_BTN_Del_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	   UxButton_SetItemData(&UIFlowWndPlayThumb_BTN_DelCtrl, 0, BTNITM_ICONID, ICON_OPERATE_DEL_F );

    return NVTEVT_CONSUME;
}


INT32 UIFlowWndPlayThumb_BTN_Del_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxButton_SetItemData(&UIFlowWndPlayThumb_BTN_DelCtrl, 0, BTNITM_ICONID, ICON_OPERATE_DEL );

    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndPlayThumb_BTN_RightCtrl Event---------------------------
INT32 UIFlowWndPlayThumb_BTN_Right_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_BTN_Right_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_BTN_Right_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIFlowWndPlayThumb_BTN_Right)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlayThumb_BTN_Right_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_PRESS,UIFlowWndPlayThumb_BTN_Right_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_USER_RELEASE,UIFlowWndPlayThumb_BTN_Right_OnTouchPanelRelease)

EVENT_END

INT32 UIFlowWndPlayThumb_BTN_Right_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
CHKPNT;
	UIFlowWndPlayThumb_NaviKey(NVTEVT_KEY_RIGHT);

	//Ux_PostEvent(NVTEVT_KEY_DOWN, 1, NVTEVT_KEY_PRESS);
		    return NVTEVT_CONSUME;
	bDetClick = 1;
	DetJumpDirect = 2; 
			//UIPlay_PlaySingle(PB_SINGLE_NEXT);
			//FlowPB_UpdateIcons(1);
			//UIFlowWndPlay_CheckStatus();
			//UIFlowWndPlayThumb_NaviKey(NVTEVT_KEY_DOWN);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_BTN_Right_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	   UxButton_SetItemData(&UIFlowWndPlayThumb_BTN_RightCtrl, 0, BTNITM_ICONID, ICON_OPERATE_RIGHT_F );

    return NVTEVT_CONSUME;
}


INT32 UIFlowWndPlayThumb_BTN_Right_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxButton_SetItemData(&UIFlowWndPlayThumb_BTN_RightCtrl, 0, BTNITM_ICONID, ICON_OPERATE_RIGHT );

    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndPlayThumb_BTN_SelectCtrl Event---------------------------
INT32 UIFlowWndPlayThumb_BTN_Select_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_BTN_Select_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_BTN_Select_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);



EVENT_BEGIN(UIFlowWndPlayThumb_BTN_Select)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlayThumb_BTN_Select_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_PRESS,UIFlowWndPlayThumb_BTN_Select_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_USER_RELEASE,UIFlowWndPlayThumb_BTN_Select_OnTouchPanelRelease)
EVENT_END

INT32 UIFlowWndPlayThumb_BTN_Select_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_PostEvent(NVTEVT_KEY_ENTER, 1, NVTEVT_KEY_PRESS);
		    return NVTEVT_CONSUME;
			if ( bDetClick == 0)
	{
		UIPlay_PlaySingle(PB_SINGLE_CURR);
		UIFlowWndPlay_CheckStatus();
	}else{
		bDetClick = 0;
	}
	Ux_CloseWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 1, NVTRET_THUMBNAIL);


    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_BTN_Select_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	   UxButton_SetItemData(&UIFlowWndPlayThumb_BTN_SelectCtrl, 0, BTNITM_ICONID, ICON_OPERATE_SELECT_F );

    return NVTEVT_CONSUME;
}


INT32 UIFlowWndPlayThumb_BTN_Select_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxButton_SetItemData(&UIFlowWndPlayThumb_BTN_SelectCtrl, 0, BTNITM_ICONID, ICON_OPERATE_SELECT);

    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndPlayThumb_BTN_ExitCtrl Event---------------------------
INT32 UIFlowWndPlayThumb_BTN_Exit_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_BTN_Exit_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayThumb_BTN_Exit_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIFlowWndPlayThumb_BTN_Exit)
EVENT_ITEM(NVTEVT_CLICK,UIFlowWndPlayThumb_BTN_Exit_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_PRESS,UIFlowWndPlayThumb_BTN_Exit_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_USER_RELEASE,UIFlowWndPlayThumb_BTN_Exit_OnTouchPanelRelease)

EVENT_END

INT32 UIFlowWndPlayThumb_BTN_Exit_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
CHKPNT;
//Ux_Redraw();
//Ux_RedrawAllWind();
FlowPB_ClearAllThumbIcon();
	Ux_CloseWindow(&UIFlowWndPlayThumbCtrl, 0);
Ux_CloseWindow(&UIFlowWndPlayCtrl, 0);
//	Display_SetEnable(LAYER_VDO1, FALSE);
Ux_SendEvent(0, NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);

    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayThumb_BTN_Exit_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	   UxButton_SetItemData(&UIFlowWndPlayThumb_BTN_ExitCtrl, 0, BTNITM_ICONID, ICON_OPERATE_EXIT_F );

    return NVTEVT_CONSUME;
}


INT32 UIFlowWndPlayThumb_BTN_Exit_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxButton_SetItemData(&UIFlowWndPlayThumb_BTN_ExitCtrl, 0, BTNITM_ICONID, ICON_OPERATE_EXIT);

    return NVTEVT_CONSUME;
}
