//This source code is generated by UI Designer Studio.

#ifndef MENUCOMMONITEM_H
#define MENUCOMMONITEM_H

#include "UIFramework.h"

extern VControl MenuCommonItemCtrl;//Panel type 

extern VControl MenuCommonItem_ListCtrl;//List type 

typedef enum
{
MenuCommonItem_List_ICON_SETUP_DATE,
MenuCommonItem_List_ICON_SETUP_AUDIO,
MenuCommonItem_List_ICON_SETUP_CYCLIC,
MenuCommonItem_List_ICON_SETUP_VOLUME,
MenuCommonItem_List_ICON_SETUP_URGSENSE,
MenuCommonItem_List_ICON_SETUP_PARK,
MenuCommonItem_List_ICON_SETUP_ALARM,
MenuCommonItem_List_ICON_SETUP_ANFA_ADAS,
MenuCommonItem_List_ICON_MENU_BL,
MenuCommonItem_List_ICON_SETUP_FORMAT,
MenuCommonItem_List_ICON_SETUP_RESET,
MenuCommonItem_List_ICON_SETUP_ABOUT,
MenuCommonItem_List_MAX
}MenuCommonItem_List_Setting;

extern VControl MenuCommonItem_Panel_OperateCtrl;//Panel type 

extern VControl MenuCommonItem_BTN_ReturnCtrl;//Button type 

extern VControl MenuCommonItem_BTN_ExitCtrl;//Button type 

//---------------------MenuCommonItemCtrl User Export---------------------------
#endif
