//This source code is generated by UI Designer Studio.

#ifndef MENUCOMMONPLAYMENU_H
#define MENUCOMMONPLAYMENU_H

#include "UIFramework.h"

extern VControl MenuCommonPlayMenuCtrl;//Panel type 

extern VControl MenuCommonPlayMenu_Panel_OperateCtrl;//Panel type 

extern VControl MenuCommonPlayMenu_BTN_ReturnCtrl;//Button type 



extern VControl MenuCommonPlayMenu_BTN_ExitCtrl;//Button type 

extern VControl MenuCommonPlayMenu_ListCtrl;//Panel type 

extern VControl Status_loopCCtrl;//Status type 

typedef enum
{
Status_loopC_ICON_PBMENU_LOOP,
Status_loopC_ICON_PBMENU_LOOP_F,
Status_loopC_MAX
}Status_loopC_Setting;

extern VControl Status_EMRCCtrl;//Status type 

typedef enum
{
Status_EMRC_ICON_PBMENU_URG,
Status_EMRC_ICON_PBMENU_URG_F,
Status_EMRC_MAX
}Status_EMRC_Setting;

extern VControl Status_PHOTOCtrl;//Status type 

typedef enum
{
Status_PHOTO_ICON_PBMENU_PHOTO,
Status_PHOTO_ICON_PBMENU_PHOTO_F,
Status_PHOTO_MAX
}Status_PHOTO_Setting;

extern VControl MenuCommonPlayMenu_StaticTXT_TitleCtrl;//Static type 

//---------------------MenuCommonPlayMenuCtrl User Export---------------------------
#endif
