//This source code is generated by UI Designer Studio.

#ifndef MENUCOMMONOPTION_H
#define MENUCOMMONOPTION_H

#include "UIFramework.h"

extern VControl MenuCommonOptionCtrl;//Panel type 

extern VControl MenuCommonOption_Static_TitleCtrl;//Static type 

extern VControl MenuCommonOption_MenuCtrl;//Menu type 

typedef enum
{
MenuCommonOption_Menu_STRID_A0,
MenuCommonOption_Menu_STRID_A1,
MenuCommonOption_Menu_STRID_A2,
MenuCommonOption_Menu_STRID_A3,
MenuCommonOption_Menu_MAX
}MenuCommonOption_Menu_Setting;

extern VControl MenuCommonOption_Panel_OperateCtrl;//Panel type 

extern VControl MenuCommonOption_BTN_ReturnCtrl;//Button type 

extern VControl MenuCommonOption_BTN_ExitCtrl;//Button type 

//---------------------MenuCommonOptionCtrl User Export---------------------------
#endif
