//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "MenuCommonPlayMenuRes.c"
#include "MenuCommonPlayMenu.h"
#include "PrjCfg.h"

#include "UIFlow.h"
#include "PlaybackTsk.h"
//---------------------MenuCommonPlayMenuCtrl Debug Definition -----------------------------
#define _MENUCOMMONPLAYMENU_ERROR_MSG        1
#define _MENUCOMMONPLAYMENU_TRACE_MSG        0

#if (_MENUCOMMONPLAYMENU_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define MenuCommonPlayMenuErrMsg(...)            debug_msg ("^R MenuCommonPlayMenu: "__VA_ARGS__)
#else
#define MenuCommonPlayMenuErrMsg(...)
#endif

#if (_MENUCOMMONPLAYMENU_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define MenuCommonPlayMenuTraceMsg(...)          debug_msg ("^B MenuCommonPlayMenu: "__VA_ARGS__)
#else
#define MenuCommonPlayMenuTraceMsg(...)
#endif
#include "UIAppPlay.h"
extern void UIPlay_SetRootDirType(UIPLAY_ROOTDIR_TYPE uiType);

//---------------------MenuCommonPlayMenuCtrl Global Variables -----------------------------

//---------------------MenuCommonPlayMenuCtrl Prototype Declaration  -----------------------

//---------------------MenuCommonPlayMenuCtrl Public API  ----------------------------------

//---------------------MenuCommonPlayMenuCtrl Private API  ---------------------------------
//---------------------MenuCommonPlayMenuCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonPlayMenu)
CTRL_LIST_ITEM(MenuCommonPlayMenu_Panel_Operate)
CTRL_LIST_ITEM(MenuCommonPlayMenu_List)
CTRL_LIST_ITEM(MenuCommonPlayMenu_StaticTXT_Title)
CTRL_LIST_END

//----------------------MenuCommonPlayMenuCtrl Event---------------------------
INT32 MenuCommonPlayMenu_OnOpen(VControl *, UINT32, UINT32 *);
INT32 MenuCommonPlayMenu_OnClose(VControl *, UINT32, UINT32 *);
INT32 MenuCommonPlayMenu_OnChildClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonPlayMenu)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,MenuCommonPlayMenu_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,MenuCommonPlayMenu_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,MenuCommonPlayMenu_OnChildClose)
EVENT_END
// Movie mode key mask
#define PLAY_KEY_PRESS_MASK         (FLGKEY_SHUTTER2|FLGKEY_RIGHT|FLGKEY_LEFT|FLGKEY_CUSTOM1|FLGKEY_UP|FLGKEY_DOWN)
#define PLAY_KEY_RELEASE_MASK      (FLGKEY_SHUTTER2|FLGKEY_RIGHT|FLGKEY_LEFT|FLGKEY_CUSTOM1|FLGKEY_UP|FLGKEY_DOWN)


static char g_StringPlaybackTitle[64] = {0};
static UINT32  g_uiMaskKeyPress      = PLAY_KEY_PRESS_MASK;
static UINT32  g_uiMaskKeyRelease    = PLAY_KEY_RELEASE_MASK;

INT32 MenuCommonPlayMenu_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
CHKPNT;
	Ux_FlushEventByRange(NVTEVT_KEY_EVT_START, NVTEVT_KEY_EVT_END);
	/* Init window key mask variables & set key and key released mask */
	g_uiMaskKeyPress = PLAY_KEY_PRESS_MASK;
	g_uiMaskKeyRelease = PLAY_KEY_RELEASE_MASK;
	Input_SetKeyMask(KEY_PRESS, g_uiMaskKeyPress);
	Input_SetKeyMask(KEY_RELEASE, g_uiMaskKeyPress);
	Input_SetKeyMask(KEY_CONTINUE, g_uiMaskKeyPress);

	memset(g_StringPlaybackTitle, 0, 64);
	snprintf(g_StringPlaybackTitle, sizeof(g_StringPlaybackTitle), "Photo");// Txt_Pointer(g_StringPlaybackTitle)
	UxCtrl_SetShow(&Status_PHOTOCtrl, TRUE);
	UxStatic_SetData(&MenuCommonPlayMenu_StaticTXT_TitleCtrl,STATIC_VALUE,STRID_PHOTOALBUM);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 MenuCommonPlayMenu_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{	
		UINT32  uiSoundMask;
		uiSoundMask = Input_GetKeySoundMask(KEY_PRESS);
		uiSoundMask &= ~FLGKEY_ENTER;
		Input_SetKeySoundMask(KEY_PRESS, uiSoundMask);

		g_uiMaskKeyPress = PLAY_KEY_PRESS_MASK;
		g_uiMaskKeyRelease = PLAY_KEY_RELEASE_MASK;
		Input_SetKeyMask(KEY_PRESS, g_uiMaskKeyPress);
		Input_SetKeyMask(KEY_RELEASE, g_uiMaskKeyRelease);
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 MenuCommonPlayMenu_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32  uiSoundMask;
		uiSoundMask = Input_GetKeySoundMask(KEY_PRESS);
		uiSoundMask &= ~FLGKEY_ENTER;
		Input_SetKeySoundMask(KEY_PRESS, uiSoundMask);

		g_uiMaskKeyPress = PLAY_KEY_PRESS_MASK;
		g_uiMaskKeyRelease = PLAY_KEY_RELEASE_MASK;
		Input_SetKeyMask(KEY_PRESS, g_uiMaskKeyPress);
		Input_SetKeyMask(KEY_RELEASE, g_uiMaskKeyRelease);
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------MenuCommonPlayMenu_ListCtrl Event---------------------------
INT32 MenuCommonPlayMenu_List_OnTouchPanelClick(VControl *, UINT32, UINT32 *);


INT32 MenuCommonPlayMenu_List_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 CurItem ;
	CurItem = UxList_GetData(&MenuCommonPlayMenu_ListCtrl,LST_CURITM);
	debug_msg("curitem:%d \r\n",CurItem);
		
/*
	switch (CurItem)
	{
		case MenuCommonPlayMenu_List_ICON_WIFI_ON_M: //cyc video
			UIPlay_SetRootDirType(ROOTDIR_TYPE_MOVIE );//CYCREC
			Ux_SendEvent(0, NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_PLAYBACK);

			//Ux_OpenWindow(&UIFlowWndPlayCtrl,1,CYCREC);//UIFlowWndPlayThumbCtrl
			break;
			
		case MenuCommonPlayMenu_List_ICON_WIFI_OFF_M:// emer video
			UIPlay_SetRootDirType(ROOTDIR_TYPE_MOVIE_EMR );//EMERREC
			Ux_SendEvent(0, NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_PLAYBACK);

//			Ux_OpenWindow(&UIFlowWndPlayCtrl,1,EMERREC);
			break;
			

	}
	*/
    	return NVTEVT_CONSUME;

}
//----------------------MenuCommonPlayMenu_Static_TitleCtrl Event---------------------------
EVENT_BEGIN(MenuCommonPlayMenu_Static_Title)
EVENT_END

//---------------------MenuCommonPlayMenu_Panel_OperateCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonPlayMenu_Panel_Operate)
CTRL_LIST_ITEM(MenuCommonPlayMenu_BTN_Return)
//CTRL_LIST_ITEM(MenuCommonPlayMenu_BTN_Del)
//CTRL_LIST_ITEM(MenuCommonPlayMenu_BTN_Play)
CTRL_LIST_ITEM(MenuCommonPlayMenu_BTN_Exit)
CTRL_LIST_END

//----------------------MenuCommonPlayMenu_Panel_OperateCtrl Event---------------------------
EVENT_BEGIN(MenuCommonPlayMenu_Panel_Operate)
EVENT_END

//----------------------MenuCommonPlayMenu_BTN_ReturnCtrl Event---------------------------

INT32 MenuCommonPlayMenu_BTN_Return_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);
INT32 MenuCommonPlayMenu_BTN_Return_OnTouchPanelPress(VControl *, UINT32, UINT32 *);
INT32 MenuCommonPlayMenu_BTN_Return_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonPlayMenu_BTN_Return)
EVENT_ITEM(NVTEVT_USER_RELEASE,MenuCommonPlayMenu_BTN_Return_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_PRESS,MenuCommonPlayMenu_BTN_Return_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_USER_PRESS,MenuCommonPlayMenu_BTN_Return_OnTouchPanelPress)	
EVENT_ITEM(NVTEVT_CLICK,MenuCommonPlayMenu_BTN_Return_OnTouchPanelClick)
EVENT_END

INT32 MenuCommonPlayMenu_BTN_Return_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(0, NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);
    return NVTEVT_CONSUME;
}

INT32 MenuCommonPlayMenu_BTN_Return_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	        UxButton_SetItemData(&MenuCommonPlayMenu_BTN_ReturnCtrl, 0, BTNITM_ICONID, ICON_OPERATE_RETURN_F );

	return NVTEVT_CONSUME;
}

INT32 MenuCommonPlayMenu_BTN_Return_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	        UxButton_SetItemData(&MenuCommonPlayMenu_BTN_ReturnCtrl, 0, BTNITM_ICONID, ICON_OPERATE_RETURN);

	return NVTEVT_CONSUME;
}

//----------------------MenuCommonPlayMenu_BTN_DelCtrl Event---------------------------
INT32 MenuCommonPlayMenu_BTN_Del_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonPlayMenu_BTN_Del)
EVENT_ITEM(NVTEVT_CLICK,MenuCommonPlayMenu_BTN_Del_OnTouchPanelClick)
EVENT_END

INT32 MenuCommonPlayMenu_BTN_Del_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------MenuCommonPlayMenu_BTN_PlayCtrl Event---------------------------
INT32 MenuCommonPlayMenu_BTN_Play_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonPlayMenu_BTN_Play)
EVENT_ITEM(NVTEVT_CLICK,MenuCommonPlayMenu_BTN_Play_OnTouchPanelClick)
EVENT_END

INT32 MenuCommonPlayMenu_BTN_Play_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}



//----------------------MenuCommonPlayMenu_BTN_ExitCtrl Event---------------------------
INT32 MenuCommonPlayMenu_BTN_Exit_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);
INT32 MenuCommonPlayMenu_BTN_Exit_OnTouchPanelPress(VControl *, UINT32, UINT32 *);

INT32 MenuCommonPlayMenu_BTN_Exit_OnTouchPanelClick(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonPlayMenu_BTN_Exit)
EVENT_ITEM(NVTEVT_CLICK,MenuCommonPlayMenu_BTN_Exit_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_USER_RELEASE,MenuCommonPlayMenu_BTN_Exit_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_PRESS,MenuCommonPlayMenu_BTN_Exit_OnTouchPanelPress)
EVENT_ITEM(NVTEVT_USER_PRESS,MenuCommonPlayMenu_BTN_Exit_OnTouchPanelPress)	

EVENT_END

INT32 MenuCommonPlayMenu_BTN_Exit_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(0, NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);

    return NVTEVT_CONSUME;
}
INT32 MenuCommonPlayMenu_BTN_Exit_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	        UxButton_SetItemData(&MenuCommonPlayMenu_BTN_ExitCtrl, 0, BTNITM_ICONID, ICON_OPERATE_EXIT_F );

	return NVTEVT_CONSUME;
}

INT32 MenuCommonPlayMenu_BTN_Exit_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	        UxButton_SetItemData(&MenuCommonPlayMenu_BTN_ExitCtrl, 0, BTNITM_ICONID, ICON_OPERATE_EXIT);

	return NVTEVT_CONSUME;
}
//---------------------MenuCommonPlayMenu_ListCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonPlayMenu_List)
CTRL_LIST_ITEM(Status_loopC)
CTRL_LIST_ITEM(Status_EMRC)
CTRL_LIST_ITEM(Status_PHOTO)
CTRL_LIST_END

//----------------------MenuCommonPlayMenu_ListCtrl Event---------------------------
EVENT_BEGIN(MenuCommonPlayMenu_List)
EVENT_END

//----------------------Status_loopCCtrl Event---------------------------
INT32 Status_loopC_OnTouchPanelClick(VControl *, UINT32 , UINT32 *);
INT32 Status_loopC_OnTouchPanelRelease(VControl *, UINT32 , UINT32 *);
INT32 Status_loopC_OnTouchPanelPress(VControl *, UINT32 , UINT32 *);
INT32 Status_loopC_OnTouchPanelPress(VControl *, UINT32 , UINT32 *);
EVENT_BEGIN(Status_loopC)
EVENT_ITEM(NVTEVT_CLICK,Status_loopC_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_USER_RELEASE,Status_loopC_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_USER_PRESS,Status_loopC_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_PRESS,Status_loopC_OnTouchPanelPress)

EVENT_END

BOOL PlayMenu_Close = 0;
extern BOOL           g_bUIFlowWndPlayNoImgWndOpened ;
INT32 Status_loopC_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	CHKPNT;
	if (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE) {
		Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, UIFlowWndWrnMsg_StatusTXT_Msg_STRID_PLEASE_INSERT_SD, FLOWWRNMSG_TIMER_2SEC);
		return NVTEVT_CONSUME;
	}
	
	  UIPlay_SetRootDirType(ROOTDIR_TYPE_MOVIE);//CYCREC

	  Ux_SendEvent(0, NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_PLAYBACK); //选定之后切 play mode，显示九宫格 	
		return NVTEVT_CONSUME;
	
}
INT32 Status_loopC_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
CHKPNT;
    UxState_SetData(&Status_loopCCtrl, STATE_CURITEM, Status_loopC_ICON_PBMENU_LOOP_F );


	return NVTEVT_CONSUME;
}

INT32 Status_loopC_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
CHKPNT;
    UxState_SetData(&Status_loopCCtrl, STATE_CURITEM, Status_loopC_ICON_PBMENU_LOOP );

		return NVTEVT_CONSUME;
}

//----------------------Status_EMRCCtrl Event---------------------------
INT32 Status_EMRC_OnTouchPanelClick(VControl *, UINT32 , UINT32 *);
INT32 Status_EMRC_OnTouchPanelPress(VControl *, UINT32 , UINT32 *);
INT32 Status_EMRC_OnTouchPanelRelease(VControl *, UINT32 , UINT32 *);

EVENT_BEGIN(Status_EMRC)
EVENT_ITEM(NVTEVT_CLICK,Status_EMRC_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_USER_RELEASE,Status_EMRC_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_USER_PRESS,Status_EMRC_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_PRESS,Status_EMRC_OnTouchPanelPress)

EVENT_END
INT32 Status_EMRC_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	if (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE) {
		Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, UIFlowWndWrnMsg_StatusTXT_Msg_STRID_PLEASE_INSERT_SD, FLOWWRNMSG_TIMER_3SEC);
		return NVTEVT_CONSUME;
	}
	
	
	  	  UIPlay_SetRootDirType(ROOTDIR_TYPE_MOVIE_EMR);//CYCREC

	  Ux_SendEvent(0, NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_PLAYBACK); //选定之后切 play mode，显示九宫格 	

	return NVTEVT_CONSUME;
}
INT32 Status_EMRC_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
      UxState_SetData(&Status_EMRCCtrl, STATE_CURITEM, Status_EMRC_ICON_PBMENU_URG_F );

	return NVTEVT_CONSUME;
}

INT32 Status_EMRC_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
      UxState_SetData(&Status_EMRCCtrl, STATE_CURITEM, Status_EMRC_ICON_PBMENU_URG );
		return NVTEVT_CONSUME;
}

//----------------------Status_PHOTOCtrl Event---------------------------
INT32 Status_PHOTO_OnTouchPanelRelease(VControl *, UINT32 , UINT32 *);
INT32 Status_PHOTO_OnTouchPanelPress(VControl *, UINT32 , UINT32 *);
INT32 Status_PHOTO_OnTouchPanelClick(VControl *, UINT32 , UINT32 *);
EVENT_BEGIN(Status_PHOTO)
EVENT_ITEM(NVTEVT_CLICK,Status_PHOTO_OnTouchPanelClick)
EVENT_ITEM(NVTEVT_USER_RELEASE,Status_PHOTO_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_USER_PRESS,Status_PHOTO_OnTouchPanelRelease)
EVENT_ITEM(NVTEVT_PRESS,Status_PHOTO_OnTouchPanelPress)

EVENT_END

INT32 Status_PHOTO_OnTouchPanelClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	if (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE) {
		Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, UIFlowWndWrnMsg_StatusTXT_Msg_STRID_PLEASE_INSERT_SD, FLOWWRNMSG_TIMER_3SEC);
		return NVTEVT_CONSUME;
	}
	
	
	  	  UIPlay_SetRootDirType(ROOTDIR_TYPE_PHOTO);//CYCREC

	  Ux_SendEvent(0, NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_PLAYBACK); //选定之后切 play mode，显示九宫格 	

	return NVTEVT_CONSUME;
}
INT32 Status_PHOTO_OnTouchPanelPress(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
      UxState_SetData(&Status_PHOTOCtrl, STATE_CURITEM, Status_PHOTO_ICON_PBMENU_PHOTO_F );

	return NVTEVT_CONSUME;
}

INT32 Status_PHOTO_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
      UxState_SetData(&Status_PHOTOCtrl, STATE_CURITEM, Status_PHOTO_ICON_PBMENU_PHOTO );
		return NVTEVT_CONSUME;
}

//----------------------MenuCommonPlayMenu_StaticTXT_TitleCtrl Event---------------------------
EVENT_BEGIN(MenuCommonPlayMenu_StaticTXT_Title)
EVENT_END

